"use client";
import {useEffect,useState} from "react";
import type {WordCard} from "@/lib/content/word-card-types";
import {savedWordCard} from "@/lib/study/saved-word-card";
import {conversationFrames,sheetQuizzes} from "@/lib/study/sheet-topics";
import {conversationTags,conversationLines,conversationBookmark,readConversationBookmark,spellingName,spellingCard,spellingUtterance,spellingAlphabet,type SpeakerRole} from "@/lib/study/conversation-learning";
import {GermanText,SaveButton} from "./StudyProvider";
import {LineAudio} from "./StudyAudio";
import {useStudyScope,StudyScopeNotice} from "./StudyScope";
import {OverviewPanel} from "./OverviewPanel";
import "./ConversationWorkshop.css";
import "./CheatSheetPrint.css";

const helpPhrases=[{de:"Wie bitte?",en:"Pardon? / Could you repeat that?"},{de:"Wie schreibt man das?",en:"How do you spell that?"},{de:"Noch einmal, bitte.",en:"Once more, please."},{de:"Ich verstehe das nicht.",en:"I do not understand that."},{de:"Was bedeutet das?",en:"What does that mean?"},{de:"Langsam, bitte.",en:"Slowly, please."}];

export function ConversationWorkshop({cards,speech}:{cards:WordCard[];speech:Record<string,string>}){
  const {matches}=useStudyScope();
  const [topic,setTopic]=useState("name"),[formal,setFormal]=useState(false),[role,setRole]=useState<SpeakerRole>("answer");
  const [practice,setPractice]=useState(false),[revealed,setRevealed]=useState(false);
  const [letter,setLetter]=useState("A"),[name,setName]=useState("Sara");
  useEffect(()=>{const restore=()=>{const context=readConversationBookmark(window.location.hash);if(context){setTopic(context.id);setFormal(context.formal);setRole(context.role);setPractice(false);setRevealed(false);requestAnimationFrame(()=>document.getElementById("conversation-flow")?.scrollIntoView({block:"start"}));}};restore();window.addEventListener("hashchange",restore);return()=>window.removeEventListener("hashchange",restore);},[]);
  const frames=conversationFrames.filter(frame=>matches(conversationTags(frame.id)));
  const frame=conversationFrames.find(frame=>frame.id===topic)!;
  const lines=conversationLines(frame,formal);
  const position=frames.indexOf(frame);
  const choose=(id:string)=>{setTopic(id);setRevealed(false);};
  const say=(text:string)=><span className="sheet-spoken"><GermanText text={text}/><LineAudio text={text} src={speech[text]} compact/></span>;
  const spelling=spellingName(name),letterCard=spellingCard(letter,cards),cue=letterCard?.rows[0]?.singular;
  return <>
    <section className="sheet-workshop" id="conversation-flow"><p className="study-eyebrow">Foundation dialogues · Lessons 1–3</p><h2>A conversation in your pocket.</h2><p>Choose a purpose. Practise as the asker or the responder.</p><StudyScopeNotice tags={conversationTags(frame.id)} subject="This dialogue"/>
      <div className="sheet-controls"><label>Conversation topic<select value={topic} onChange={event=>choose(event.target.value)}>{!frames.includes(frame)&&<option value={frame.id}>{frame.label} · outside selection</option>}{frames.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label><div className="study-chips" role="group" aria-label="Conversation register"><button type="button" aria-pressed={!formal} onClick={()=>{setFormal(false);setRevealed(false);}}>Friendly · du</button><button type="button" aria-pressed={formal} onClick={()=>{setFormal(true);setRevealed(false);}}>Formal · Sie</button></div></div>
      <div className="conversation-purpose"><b>{frame.label}</b><span>{formal?"Use Sie for formal address; keep the capital S.":"Use du with someone you address informally."}</span></div>
      <div className="conversation-turns" aria-live="polite">{([{id:"ask",label:"1 · Speaker A asks",de:lines.question,en:frame.en},{id:"answer",label:"2 · Speaker B responds",de:lines.answer,en:frame.answerEn}] as const).map(turn=><article key={turn.id} data-turn={turn.id}><small>{turn.label}{practice&&role===turn.id?" · your turn":""}</small><p>{turn.en}</p>{practice&&role===turn.id&&!revealed?<div className="conversation-prompt"><strong>Say your line aloud.</strong><p>Use the meaning above. Then compare with the example.</p><button type="button" className="study-secondary" onClick={()=>setRevealed(true)}>Reveal my line</button></div>:<h3>{say(turn.de)}</h3>}</article>)}</div>
      <p className="sheet-note">{frame.cue}</p><div className="sheet-controls"><label>Your role<select value={role} onChange={event=>{setRole(event.target.value as SpeakerRole);setRevealed(false);}}><option value="ask">Speaker A · ask</option><option value="answer">Speaker B · answer</option></select></label><button type="button" className="study-secondary" aria-pressed={practice} onClick={()=>{setPractice(!practice);setRevealed(false);}}>{practice?"Show both lines":"Hide my line & practise"}</button><SaveButton item={{id:`sheet-conversation-${topic}-${formal?"formal":"casual"}`,title:`${lines.question} ${lines.answer}`,meaning:`${frame.en} ${frame.answerEn}`,kind:"phrase",href:`/cheat-sheets/conversation${conversationBookmark(topic,formal,role)}`,studyTags:conversationTags(topic),audio:speech[lines.answer]??null}}/></div>
      <p>Self-check: compare your spoken line with the example. Use your own details when practising.</p>{frames.length>1&&<div className="study-row"><span>{position>=0?`Dialogue ${position+1} / ${frames.length}`:"Reference dialogue outside selection"}</span><button type="button" className="study-primary" onClick={()=>choose(frames[(position+1)%frames.length]!.id)}>Next dialogue →</button></div>}{!frames.length&&<p role="status">No foundation dialogues match your selection. This labelled reference stays available; the card practice follows your selected material.</p>}
    </section>
    <OverviewPanel title="Everyday questions, at a glance"><div className="conversation-atlas">{frames.map(item=><button type="button" key={item.id} aria-pressed={topic===item.id} onClick={()=>{choose(item.id);document.getElementById("conversation-flow")?.scrollIntoView({block:"start"});}}><small>{item.label}</small><strong lang="de">{conversationLines(item,formal).question}</strong><span lang="de">{conversationLines(item,formal).answer}</span><span>{item.en}</span></button>)}</div>{!frames.length&&<p>No matching foundation dialogues. Choose Lessons 1–3 to explore these examples.</p>}</OverviewPanel>
    <section className="sheet-workshop" id="conversation-help"><h2>When you need a little help.</h2><div className="sheet-rule-grid">{helpPhrases.map(phrase=><article key={phrase.de}><h3>{say(phrase.de)}</h3><p>{phrase.en}</p><SaveButton compact item={{id:`conversation-help-${phrase.de}`,title:phrase.de,meaning:phrase.en,kind:"phrase",href:"/cheat-sheets/conversation#conversation-help",audio:speech[phrase.de]??null,studyTags:{lessons:[1,2,3],concepts:["conversation","classroom"],source:"study-extra"}}}/></article>)}</div></section>
    <section className="sheet-workshop" id="conversation-spelling"><p className="study-eyebrow">A name → its letters → their German sounds</p><h2>Spell it out.</h2><StudyScopeNotice tags={{lessons:[1],concepts:["introductions","conversation"],source:"course"}} subject="This alphabet reference"/><p>Choose a letter or use its speaker. The selected cue helps you remember the sound: V → vau, W → we, J → jot.</p><label>Choose a letter<select value={letter} onChange={event=>setLetter(event.target.value)}>{spellingAlphabet.map(symbol=><option key={symbol} value={symbol}>{symbol}</option>)}</select></label><div className="spelling-focus"><strong lang="de">{letter}</strong><div><small>German letter name</small><p lang="de">{cue?.text??letter}</p><LineAudio text={cue?.text??letter} src={cue?.audio??speech[letter]} label={`letter ${letter}`}/>{letterCard&&<SaveButton item={savedWordCard(letterCard)}/>}</div></div>
      <div className="spelling-name"><label>Name to spell<input value={name} onChange={event=>setName(event.target.value)} maxLength={80} autoComplete="off" spellCheck={false}/></label>{spelling.error?<p role="status">{spelling.error}</p>:<><p className="spelling-name-letters" lang="de" aria-label="Letters in your name">{spelling.letters.join(" · ")}</p><LineAudio text={spellingUtterance(spelling.letters,cards)} label="name spelling"/><p>Custom names use device-generated German speech. Spaces and hyphens separate names; they are not spoken. Your typed name is not saved.</p></>}</div>
      <div className="spelling-soundboard">{spellingAlphabet.map(symbol=>{const form=spellingCard(symbol,cards)?.rows[0]?.singular;return <div key={symbol}><button type="button" aria-label={`Choose letter ${symbol}`} aria-pressed={letter===symbol} onClick={()=>setLetter(symbol)} lang="de">{symbol}</button><LineAudio compact label={`letter ${symbol}`} text={form?.text??symbol} src={form?.audio??speech[symbol]}/></div>;})}</div>
    </section>
    <details className="sheet-sources"><summary>Eight useful conversation patterns</summary><div className="sheet-rule-grid">{sheetQuizzes.conversation.map(quiz=><article key={quiz.q}><h3>{quiz.q}</h3><p>{say(quiz.answer)}</p><p>{quiz.why}</p></article>)}</div></details>
  </>;
}

export function ConversationPrintSummary({cards}:{cards:WordCard[]}){return <div className="sheet-print-summary"><section className="sheet-print-page conversation-print"><header><span>06 · Conversation & spelling</span><h2>Ask. Listen. Answer. Ask back.</h2><p>Foundation dialogues: du/Sie and useful replies. Change the fictional details to your own.</p></header><div className="conversation-print-pairs">{conversationFrames.map(frame=><section key={frame.id}><h3>{frame.label}</h3><p lang="de"><b>du:</b> {frame.casual}<br/><b>Sie:</b> {frame.formal}</p><p lang="de"><b>Reply:</b> {frame.answer}{frame.formalAnswer&&<><br/><b>Formal reply:</b> {frame.formalAnswer}</>}</p></section>)}</div><h3>When the conversation gets stuck</h3><p lang="de">Wie bitte? · Noch einmal, bitte. · Langsam, bitte.<br/>Wie schreibt man das? · Was bedeutet das? · Ich verstehe das nicht.</p><h3>Letter → German sound cue</h3><div className="conversation-print-alphabet">{spellingAlphabet.map(letter=><div key={letter}><b lang="de">{letter}</b><span lang="de">{spellingCard(letter,cards)?.rows[0]?.singular.text??letter}</span></div>)}</div><p><b>Recall:</b> cover one side of an exchange. Say it, compare, switch roles, then practise the formal version. Spell your name one letter at a time.</p><footer>Based on Momente A1.1 introductions, personal details, family and alphabet material, © Hueber Verlag. Dialogue combinations and role practice are study aids. Letter cues are reminders; listen to the sounds online.</footer></section></div>;}
