"use client";
import {useEffect,useRef,useState} from "react";
import geography from "@/generated/country-map.json";
import {countries,countryGroups,countryName,countryFrom,type CountryGroup} from "@/lib/study/countries";
import {CountryFlag} from "./CountryFlag";
import {LineAudio} from "./StudyAudio";
import {SaveButton} from "./StudyProvider";

const groups:CountryGroup[]=["neuter","female","male","plural"];
const views={world:"0 0 1000 410",europe:"445 35 165 150",asia:"595 68 295 245",americas:"35 12 355 390",africa:"432 120 250 230"};
export function CountryOverview({selected,onSelect,speech}:{selected:string;onSelect:(id:string)=>void;speech:Record<string,string>}) {
  const [view,setView]=useState<keyof typeof views>("world");
  const [chartOnly,setChartOnly]=useState(false);
  const [full,setFull]=useState(false);
  const modal=useRef<HTMLDialogElement>(null);
  const launch=useRef<HTMLButtonElement>(null);
  const previousFull=useRef(false);
  useEffect(()=>{if(full)modal.current?.showModal();else{modal.current?.close();if(previousFull.current)launch.current?.focus();}previousFull.current=full;},[full]);
  const current=countries.find(c=>c.id===selected)!;
  const choose=(id:string)=>onSelect(id);
  const content=<div className={`country-atlas-content${chartOnly?" chart-only":""}`}>
    <div className="country-atlas-controls"><div className="country-atlas-mode" role="group" aria-label="Overview layout"><button type="button" aria-pressed={!chartOnly} onClick={()=>setChartOnly(false)}>Map + chart</button><button type="button" aria-pressed={chartOnly} onClick={()=>setChartOnly(true)}>Chart only</button></div>{full&&<button type="button" className="study-secondary" onClick={()=>setFull(false)}>Close overview</button>}</div>
    {!chartOnly&&<div className="country-atlas-map-layout"><div className="country-atlas-map"><div className="country-map-zooms" role="group" aria-label="Map region">{(Object.keys(views) as (keyof typeof views)[]).map(key=><button type="button" key={key} aria-pressed={view===key} onClick={()=>setView(key)}>{key[0]!.toUpperCase()+key.slice(1)}</button>)}</div><svg viewBox={views[view]} role="group" aria-label="Interactive world map of the 41 study country names" className="country-world-map"><rect x="0" y="0" width="1000" height="410" fill="#edf3f2"/><g className="country-map-background" aria-hidden="true">{geography.background.map((path,i)=><path key={i} d={path}/>)}</g>{[...geography.countries].sort((a,b)=>Number(a.id==="GB-ENG")-Number(b.id==="GB-ENG")).map(shape=>{const c=countries.find(c=>c.id===shape.id)!;return <g key={c.id} className={`country-map-shape study-tone-${c.group}${selected===c.id?" is-selected":""}`} data-map-country={c.id} role="button" tabIndex={0} aria-pressed={selected===c.id} aria-label={`${countryName(c)}: ${countryFrom(c)}`} onClick={()=>choose(c.id)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();choose(c.id);}}}><title>{`${countryName(c)} · ${countryFrom(c)}`}</title><path d={shape.path}/>{shape.marker&&<circle cx={shape.center[0]} cy={shape.center[1]} r={view==="world"?4:1.8}/>}</g>;})}<g className={`country-map-pin study-tone-${current.group}`} aria-hidden="true"><circle cx={geography.countries.find(c=>c.id===selected)!.center[0]} cy={geography.countries.find(c=>c.id===selected)!.center[1]} r={view==="world"?6:2.5}/></g></svg><p className="country-map-caption">Only your study countries are colored. Dots keep small countries visible. Zoom into Europe or choose any flag below.</p></div><aside className={`country-map-selection study-tone-${current.group}`} aria-live="polite"><CountryFlag id={current.id} label={current.en}/><small>{countryGroups[current.group].label}</small><h3 lang="de">{countryName(current)}</h3><p className="country-map-origin" lang="de">{countryFrom(current)}</p><p>{current.en} · {current.languages.join(" / ")}</p><div className="study-row"><LineAudio text={`Ich komme ${countryFrom(current)}.`} src={speech[`Ich komme ${countryFrom(current)}.`]} compact/><SaveButton item={{id:`country-${current.id}`,title:`Ich komme ${countryFrom(current)}.`,meaning:`${current.en} · ${countryGroups[current.group].label} · ${current.languages.join(", ")}`,kind:"concept",href:`/cheat-sheets#country-${current.id}`,audio:speech[`Ich komme ${countryFrom(current)}.`]??null}}/></div></aside></div>}
    <div className="country-memory-chart" aria-label="All 41 country names grouped by article and gender">{groups.map(group=><section key={group} className={`country-chart-group study-tone-${group}`} data-chart-group={group}><header><div><span>{countryGroups[group].label}</span><strong lang="de">{group==="neuter"?"∅":group==="male"?"der":"die"} → {countryGroups[group].from}</strong></div><small>{group==="neuter"?"The big green group: travel without an article.":group==="female"?"Two pink names. The country stays feminine.":group==="male"?"One blue anchor: Iran → deM.":"Purple means plural. Remember deN."}</small></header><div className="country-chart-flags">{countries.filter(c=>c.group===group).map(c=><button type="button" key={c.id} data-chart-country={c.id} aria-pressed={selected===c.id} aria-label={`Remember ${countryName(c)}: ${countryFrom(c)}`} onClick={()=>choose(c.id)} title={`${countryName(c)} · ${countryFrom(c)}`}><CountryFlag id={c.id} label={c.en}/><span lang="de">{c.name}</span></button>)}</div></section>)}</div>
    <p className="country-atlas-note"><b>Memory anchors:</b> pink Switzerland + Turkey; blue Iran; purple USA + Netherlands + Maldives. The remaining names use no article. Iran also allows <b lang="de">aus Iran</b>. Great Britain combines England, Scotland and Wales; its flag tile uses the UK’s Union flag.</p>
    <p className="country-atlas-credit">Map: <a href="https://www.naturalearthdata.com/about/terms-of-use/" target="_blank" rel="noreferrer">Natural Earth</a> · Flags: <a href="https://github.com/lipis/flag-icons" target="_blank" rel="noreferrer">flag-icons</a>. Colors show German grammar.</p>
  </div>;
  return <section id="country-overview" className="country-overview" aria-labelledby="country-overview-title"><div className="study-section-heading"><div><p className="study-eyebrow">41 names · four memory groups</p><h2 id="country-overview-title">See the whole pattern.</h2></div><button ref={launch} type="button" className="study-secondary" onClick={()=>setFull(true)}>Open full-screen overview</button></div><p>Choose a country on the map or flag chart. Its article, origin phrase and language stay together.</p>{!full&&content}<dialog className="country-atlas-dialog" ref={modal} aria-label="Full-screen country overview" onCancel={()=>setFull(false)} onClose={()=>setFull(false)}>{full&&content}</dialog></section>;
}
