"use client";
import {useState} from 'react';
import Link from 'next/link';
import type {WordCard} from '@/lib/content/word-card-types';
import {foodModels,foodModes,foodSentence,foodMeaning,foodSaveId,foodReply,foodCompounds,type FoodMode} from '@/lib/study/food-sheet';
import {CheatSheetNav} from './CheatSheetNav';
import {GermanText,SaveButton} from './StudyProvider';
import {LineAudio} from './StudyAudio';
import {useStudyScope} from './StudyScope';
import {WordFamilyPreview} from '../word-cards/WordFamilyPreview';
export function FoodCheatSheet({cards,speech}:{cards:WordCard[];speech:Record<string,string>}){
 const [food,setFood]=useState(1),[mode,setMode]=useState<FoodMode>('wish'),[negative,setNegative]=useState(false),[english,setEnglish]=useState(true),[compound,setCompound]=useState(0),[speakerLikes,setSpeakerLikes]=useState(true),[youLike,setYouLike]=useState(true);
 const {matches}=useStudyScope();const f=foodModels[food]!,sentence=foodSentence(food,mode,negative),meaning=foodMeaning(food,mode,negative),c=foodCompounds[compound]!,reply=foodReply(speakerLikes,youLike),start=speakerLikes?'Ich mag Tee.':'Ich mag keinen Tee.';
 const say=(text:string)=><span className="sheet-spoken"><GermanText text={text}/><LineAudio compact text={text} src={speech[text]}/></span>;
 const shown=cards.filter(w=>w.studyTags&&matches(w.studyTags));
 return <div className="study-workspace food-sheet"><CheatSheetNav current="food"/><header className="study-page-header"><div><p className="study-eyebrow">Lesson 9 · Food, preferences & ordering</p><h1>From “I like” to “I’d like.”</h1><p>Give food an article colour. Give your order the right ending.</p></div></header><nav className="sheet-jump" aria-label="Food sheet sections"><Link href="#food-board">Food & articles</Link><Link href="#food-lab">Preference or order?</Link><Link href="#food-replies">Four replies</Link><Link href="#food-compounds">Build a compound</Link><Link href="#food-words">Word cards</Link></nav>
 <section id="food-board"><h2>Pick something from the menu.</h2><p>Blue <b>der</b>, pink <b>die</b>, green <b>das</b>, amber <b>plural die</b>. The article remains written on every card.</p><div className="food-board">{foodModels.map((item,i)=><button type="button" key={item.de} data-gender={item.tone} aria-pressed={food===i} onClick={()=>setFood(i)}><span aria-hidden="true">{item.icon}</span><strong lang="de">{item.de}</strong><small>{item.en}</small></button>)}</div><p><b>Two accepted genders:</b> <span className="food-male" lang="de">der Ketchup</span> / <span className="food-neuter" lang="de">das Ketchup</span>. The full word card includes both.</p></section>
 <section id="food-lab"><h2>A preference is different from an order.</h2><div className="food-intent-map"><article><small>USUALLY / IN GENERAL</small><h3 lang="de">Ich mag …</h3><p>I like it.</p><p lang="de">Ich esse / trinke gern …</p><p>I enjoy eating / drinking it.</p></article><article><small>A REQUEST NOW</small><h3 lang="de">Ich möchte …</h3><p>I would like it.</p><p lang="de">Ich nehme …</p><p>I will have it.</p></article></div><div className="food-mode" aria-label="Choose a food sentence">{foodModes.map(m=><button type="button" key={m.id} aria-pressed={mode===m.id} onClick={()=>setMode(m.id)}>{m.label}</button>)}</div><div className="sheet-controls"><label><input type="checkbox" checked={negative} onChange={e=>setNegative(e.target.checked)}/> Make it negative</label><label><input type="checkbox" checked={english} onChange={e=>setEnglish(e.target.checked)}/> Show English</label></div><div className="food-output" data-gender={mode==='wish'||mode==='take'?f.orderTone:[0,5,7,8,11].includes(food)?'plural':f.tone} aria-live="polite"><p>{say(sentence)}</p>{english&&<p>{meaning}</p>}<SaveButton item={{id:foodSaveId(food,mode,negative),title:sentence,meaning,kind:'phrase',lesson:9,href:'/cheat-sheets/food#food-lab',audio:speech[sentence]??null}}/></div><p><b>General preference:</b> food or plural nouns often have no article. <b>Ordering:</b> name a serving. A portion chooses its own article: <span lang="de">das Stück → ein Stück Käse</span>, <span lang="de">die Portion → eine Portion Fleisch</span>.</p><div className="food-case-map"><article data-gender="male"><b>der → einen / keinen</b><span lang="de">einen Salat</span></article><article data-gender="female"><b>die → eine / keine</b><span lang="de">eine Suppe</span></article><article data-gender="neuter"><b>das → ein / kein</b><span lang="de">ein Brötchen</span></article><article data-gender="plural"><b>plural → — / keine</b><span lang="de">Pommes / keine Pommes</span></article></div></section>
 <section id="food-replies"><h2>Four replies. Check what came before.</h2><div className="food-reply-map"><article><b>The other person likes it.</b><p lang="de">Ich auch. = me too.</p><p lang="de">Ich nicht. = I do not.</p></article><article><b>The other person does not like it.</b><p lang="de">Ich schon. = I do.</p><p lang="de">Ich auch nicht. = me neither.</p></article></div><div className="sheet-controls"><label>Other person<select aria-label="Other person's preference" value={String(speakerLikes)} onChange={e=>setSpeakerLikes(e.target.value==='true')}><option value="true">Likes tea</option><option value="false">Does not like tea</option></select></label><label>Your preference<select aria-label="Your preference" value={String(youLike)} onChange={e=>setYouLike(e.target.value==='true')}><option value="true">I like tea</option><option value="false">I do not like tea</option></select></label></div><div className="food-dialogue" aria-live="polite"><p><small>THE OTHER PERSON</small>{say(start)}</p><p><small>YOU</small>{say(reply)}</p><SaveButton item={{id:`l9-reply-${speakerLikes}-${youLike}`,title:`${start} – ${reply}`,meaning:`The other person ${speakerLikes?'likes':'does not like'} tea; you ${youLike?'like':'do not like'} tea.`,kind:'concept',lesson:9,href:'/cheat-sheets/food#food-replies',audio:speech[reply]??null}}/></div></section>
 <section id="food-compounds"><h2>The last word decides the article.</h2><label>Choose a word pair<select aria-label="Choose a compound" value={compound} onChange={e=>setCompound(Number(e.target.value))}>{foodCompounds.map((item,i)=><option key={item.result} value={i}>{item.left} + {item.right}</option>)}</select></label><div className="food-compound" aria-live="polite"><div><small>DESCRIBES THE KIND</small><strong lang="de">{c.left}</strong></div><span aria-hidden="true">+</span><div data-gender={c.tone}><small>CHOOSES THE ARTICLE</small><strong lang="de">{c.right}</strong></div><span aria-hidden="true">→</span><div data-gender={c.tone}><small>THE NEW WORD</small><strong>{say(c.result)}</strong></div></div><p>{c.en}. {c.cue}</p><SaveButton item={{id:`l9-compound-${compound}`,title:`${c.left} + ${c.right} → ${c.result}`,meaning:c.cue,kind:'concept',lesson:9,href:'/cheat-sheets/food#food-compounds',audio:speech[c.result]??null}}/><p><b>Listen for stress:</b> compound nouns usually stress the first part. Compare the workbook’s original pronunciation recording in <Link href="/book?page=workbook-57">Exercise 14</Link>.</p></section>
 <section id="food-words"><h2>Build your food vocabulary.</h2><p>{shown.length} word families match your selection.</p><div className="card-grid">{shown.map(card=><WordFamilyPreview key={card.id} card={card} href={card.path} lessonIds={card.lessons.map(n=>`lesson:${n.padStart(2,'0')}`)}/>)}</div></section><Link href="/lessons/09#practice">Practise the whole lesson →</Link><p className="muted">Based on Momente A1.1 KB 55–64 and partner activities 165–166, AB 54–65 and the Lesson 9 glossary. Diagrams and practice combinations are authored learning aids.</p></div>;
}
