"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import type {WordCard} from "@/lib/content/word-card-types";
import {hobbyModels,hobbyPeople,abilityLevels,frequencyWords,abilityParts,abilitySentence,abilityMeaning,frequencySentence,frequencyMeaning} from "@/lib/study/hobbies-sheet";
import {CheatSheetNav} from "./CheatSheetNav";
import {GermanText,SaveButton} from "./StudyProvider";
import {LineAudio} from "./StudyAudio";
import {StudyScopeNotice} from "./StudyScope";
import {tagsForLesson} from "@/lib/study/scope";
import {hobbyContrastSaveId,hobbyContrasts,hobbyBookmark,readHobbyBookmark} from "@/lib/study/hobby-learning";
import {HobbyIllustration,FrequencyWeek,HobbyContrastPractice} from "./HobbyTools";
import {HobbiesPrintSummary} from "./HobbyTimePrint";
import {SheetWordIndex} from "./SheetWordIndex";
export function HobbiesCheatSheet({cards,speech}:{cards:WordCard[];speech:Record<string,string>}){
 const [hobby,setHobby]=useState(0),[person,setPerson]=useState(0),[level,setLevel]=useState(0),[question,setQuestion]=useState(false),[frequency,setFrequency]=useState(1),[english,setEnglish]=useState(true);
 useEffect(()=>{const restore=()=>{const state=readHobbyBookmark(window.location.hash);if(state){setHobby(state.hobby);setPerson(state.person);setLevel(state.level);setQuestion(state.question);setFrequency(state.frequency);requestAnimationFrame(()=>document.getElementById(state.section==="contrast"?"hobby-contrast-practice":`${state.section}-lab`)?.scrollIntoView({block:"start"}));}};restore();window.addEventListener("hashchange",restore);return()=>window.removeEventListener("hashchange",restore);},[]);
 const parts=abilityParts(hobby,person,level,question),sentence=abilitySentence(hobby,person,level,question),meaning=abilityMeaning(hobby,person,level,question),often=frequencySentence(hobby,frequency);
 const say=(text:string)=><span className="sheet-spoken"><GermanText text={text}/><LineAudio compact text={text} src={speech[text]}/></span>;
 return <div className="study-workspace hobbies-sheet"><CheatSheetNav current="hobbies"/><header className="study-page-header"><div><p className="study-eyebrow">Lesson 7 · Hobbies, abilities & frequency</p><h1>Can do. Like doing. How often?</h1><p>Three different meanings. Give each one its own place in your memory.</p></div><button type="button" className="study-secondary" onClick={()=>window.print()}>Print cheat sheet</button></header><nav className="sheet-jump" aria-label="Hobbies sheet sections"><Link href="#hobby-map">Three meanings</Link><Link href="#ability-lab">Build a verb frame</Link><Link href="#frequency-lab">How often?</Link><Link href="#hobby-vowels">Vowel changes</Link><Link href="#hobby-words">Word cards</Link><Link href="#hobby-contrast-practice">Can / like / often practice</Link><Link href="#sheet-practice">Card practice</Link></nav>
 <section id="hobby-map"><h2>Keep these three questions apart.</h2><StudyScopeNotice tags={tagsForLesson(7)} subject="This hobby reference"/><div className="hobby-selection"><HobbyIllustration index={hobby}/><label>Activity to explore<select value={hobby} onChange={event=>setHobby(Number(event.target.value))}>{hobbyModels.map((item,index)=><option key={item.id} value={index}>{item.de}</option>)}</select></label></div><div className="hobby-meaning-map">{hobbyContrasts(hobby).map((m,i)=><article key={m.kind} data-meaning={i}><small>{i===0?"How well?":i===1?"Do I enjoy it?":"How often?"}</small><h3>{m.label}</h3><p>{say(m.de)}</p><p>{m.en}</p><b>{m.cue}</b><SaveButton item={{id:hobbyContrastSaveId(hobby,i),title:m.de,meaning:m.en,kind:"concept",lesson:7,href:`/cheat-sheets/hobbies#hobby-contrast-${hobby}-${i}`,audio:speech[m.de]??null}}/></article>)}</div></section>
 <section id="ability-lab" className="hobby-lab"><h2>Open the frame. Close it with the infinitive.</h2><p><b>Statement:</b> können in position 2. <b>Yes/no question:</b> können first. The activity verb stays at the end, without <span lang="de">zu</span>.</p><details><summary>Eight illustrated activities</summary><div className="hobby-pickers">{hobbyModels.map((h,i)=><button type="button" key={h.id} aria-pressed={hobby===i} onClick={()=>setHobby(i)}><HobbyIllustration index={i}/><span lang="de">{h.de}</span></button>)}</div></details><div className="sheet-controls"><label>Person<select aria-label="Choose a person" value={person} onChange={e=>setPerson(Number(e.target.value))}>{hobbyPeople.map((p,i)=><option key={p.de} value={i}>{p.de} · {p.en}</option>)}</select></label><label><input type="checkbox" checked={question} onChange={e=>setQuestion(e.target.checked)}/> Make it a question</label><label><input type="checkbox" checked={english} onChange={e=>setEnglish(e.target.checked)}/> Show English</label></div><div className="hobby-ability-scale" role="group" aria-label="Ability scale">{abilityLevels.map((ability,index)=><button type="button" key={ability.de} aria-pressed={level===index} onClick={()=>setLevel(index)}><b lang="de">{ability.de}</b><small>{ability.en}</small></button>)}</div><div className="hobby-frame" aria-live="polite">{parts.map((part,i)=><div key={i} data-part={i===(question?0:1)?"modal":i===3?"infinitive":"middle"}><small>{i===(question?0:1)?"KÖNNEN":i===3?"INFINITIVE · END":`BLOCK ${i+1}`}</small><span lang="de">{part}</span></div>)}</div><div className="hobby-result"><p>{say(sentence)}</p>{english&&<p>{meaning}</p>}<SaveButton item={{id:`l7-ability-${hobby}-${person}-${level}-${question}`,title:sentence,meaning,kind:"phrase",lesson:7,href:`/cheat-sheets/hobbies${hobbyBookmark({hobby,person,level,question,frequency})}`,audio:speech[sentence]??null}}/></div><div className="modal-person-map">{hobbyPeople.map((p,i)=><button type="button" key={p.de} aria-pressed={person===i} onClick={()=>setPerson(i)}><span lang="de">{p.de}</span><strong lang="de">{p.modal}</strong></button>)}</div><p>Singular: <b lang="de">kann · kannst · kann</b>. Plural: <b lang="de">können · könnt · können</b>. No <span lang="de">-e</span> for <span lang="de">ich</span>; no <span lang="de">-t</span> for <span lang="de">er</span>.</p></section>
 <section id="frequency-lab"><h2>A different scale: how often?</h2><p>Use the selected hobby. Tap a frequency word. The middle words have no fixed percentages.</p><div className="frequency-map">{frequencyWords.map((f,i)=><button type="button" key={f.de} aria-pressed={frequency===i} onClick={()=>setFrequency(i)}><strong lang="de">{f.de}</strong><span>{f.en}</span></button>)}</div><FrequencyWeek frequency={frequency}/><div className="hobby-frequency" aria-live="polite"><p>{say(often)}</p>{english&&<p>{frequencyMeaning(hobby,frequency)}</p>}<SaveButton item={{id:`l7-frequency-${hobby}-${frequency}`,title:often,meaning:frequencyMeaning(hobby,frequency),kind:"phrase",lesson:7,href:`/cheat-sheets/hobbies${hobbyBookmark({hobby,person,level,question,frequency},"frequency")}`,audio:speech[often]??null}}/></div></section>
 <section id="hobby-vowels"><h2>The vowel changes with du and er.</h2><div className="hobby-vowels">{[{de:"lesen",a:"liest",b:"liest",cue:"e → ie"},{de:"treffen",a:"triffst",b:"trifft",cue:"e → i"},{de:"fahren",a:"fährst",b:"fährt",cue:"a → ä"}].map(v=><article key={v.de}><strong>{v.cue}</strong><h3 lang="de">{v.de}</h3><p lang="de">du {v.a}<br/>er / sie / es {v.b}</p><p>After <span lang="de">können</span>: {say(`Du kannst ${v.de==="treffen"?"Freunde treffen":v.de}.`)}</p></article>)}</div><Link href="/lessons/07#practice">Test the whole lesson →</Link></section>
 <HobbyContrastPractice key={hobby} hobby={hobby} speech={speech}/><SheetWordIndex cards={cards} speech={speech} path="/cheat-sheets/hobbies" id="hobby-words" title="Build your hobby vocabulary."/><p className="muted">Based on Momente A1.1 KB 47–50, partner activities 162–163 and 194, AB 46–49 and the Lesson 7 glossary. Diagrams, examples and practice combinations are authored learning aids.</p><HobbiesPrintSummary/></div>;
}
