import {hobbyModels,hobbyPeople,abilityLevels,frequencyWords} from "@/lib/study/hobbies-sheet";
import {hobbyContrasts} from "@/lib/study/hobby-learning";
import {clockWords,weekDays,dayParts} from "@/lib/study/time-sheet";
import {HobbyIllustration} from "./HobbyTools";
import {ClockFace} from "./TimeTools";
import "./CheatSheetPrint.css";
import "./HobbyTimeLearning.css";

export function HobbiesPrintSummary(){return <div className="sheet-print-summary"><div className="sheet-print-page"><header><span>10 · Hobbies, abilities & frequency</span><h2>Can do. Like doing. How often?</h2><p>Use the same activity to remember three different meanings.</p></header><div className="hobby-print-patterns">{hobbyContrasts(1).map(item=><div key={item.kind}><h3>{item.label}</h3><p lang="de">{item.de}</p><p>{item.en}</p><p>{item.cue}</p></div>)}</div><div className="hobby-print-grid">{hobbyModels.map((item,index)=><article key={item.id}><HobbyIllustration index={index}/><strong lang="de">{item.de}</strong><p>{item.ing}</p><p lang="de">{hobbyContrasts(index)[0]!.de}</p></article>)}</div><h3>The verb frame</h3><p lang="de"><b>Ich | kann | gut Rad | fahren.</b><br/><b>Kannst | du | gut Rad | fahren?</b></p><p>Statement: können in position 2. Yes/no question: können first. The activity infinitive stays at the end, without zu.</p><table><caption>Person → können</caption><tbody><tr>{hobbyPeople.map(person=><th key={person.de} lang="de">{person.de}</th>)}</tr><tr>{hobbyPeople.map(person=><td key={person.de} lang="de">{person.modal}</td>)}</tr></tbody></table><h3>Ability: how well?</h3><p>{abilityLevels.map(level=>`${level.de} = ${level.en}`).join(" · ")}</p><h3>Frequency: how often?</h3><p>{frequencyWords.map(word=>`${word.de} = ${word.en}`).join(" · ")}</p><p>Oft and manchmal have no fixed percentage or number of days. Ability, enjoyment and frequency do not imply each other.</p><h3>Changing vowels belong to the finite activity verb</h3><p lang="de">du liest · du triffst · du fährst<br/>After können: Du kannst lesen. · Du kannst Freunde treffen. · Du kannst fahren.</p><p><b>Recall:</b> cover the examples. Say one sentence about what you can do, one about what you enjoy, and one about how often you do it.</p><footer>Based on Momente A1.1 Lesson 7, © Hueber Verlag. Illustrations, example combinations and memory diagrams are study aids.</footer></div></div>;}

export function TimePrintSummary(){return <div className="sheet-print-summary time-print-summary"><div className="sheet-print-page"><header><span>11 · Time, weekdays & plans</span><h2>Halfway to the next hour.</h2><p>Read the clock, choose a day and put the verb in the right position.</p></header><div className="time-print-clocks">{[0,15,30,45].map(minute=><div key={minute}><ClockFace hour={3} minute={minute}/><p><b>3:{String(minute).padStart(2,"0")}</b></p><p lang="de">{clockWords(3,minute,"everyday")}</p></div>)}</div><div className="print-time-note"><h3 lang="de">halb vier = 3:30</h3><p>Halfway to four. Name the NEXT hour: 3:00 → 3:30 → 4:00.</p><p lang="de">3:25 → fünf vor halb vier · 3:35 → fünf nach halb vier</p></div><table><thead><tr><th>Use</th><th>German</th><th>Remember</th></tr></thead><tbody><tr><th>Clock time</th><td lang="de">um drei Uhr</td><td>At three o’clock</td></tr><tr><th>Day</th><td lang="de">am Montag</td><td>On Monday</td></tr><tr><th>Day part</th><td lang="de">am Morgen · am Abend</td><td>In the morning/evening</td></tr><tr><th>Night</th><td lang="de">in der Nacht</td><td>The night exception</td></tr><tr><th>Today</th><td lang="de">heute Abend</td><td>No preposition before heute</td></tr><tr><th>Duration*</th><td lang="de">eine Stunde · zwei Stunden</td><td>How long, not what time</td></tr></tbody></table><p>*Duration wording is an extra comparison to separate Uhr (clock time) from Stunde (an hour).</p><h3>Seven weekdays: der → am</h3><p lang="de">{weekDays.join(" · ")}</p><p lang="de">das Wochenende → am Wochenende</p><h3>Day parts</h3><p lang="de">{dayParts.map(part=>part.de).join(" · ")}</p><h3>One time phrase. Verb still second.</h3><div className="print-time-note"><p lang="de"><b>Am Montag um fünfzehn Uhr dreißig | gehen | wir | ins Kino.</b><br/>Wir | gehen | am Montag um fünfzehn Uhr dreißig | ins Kino.</p></div><p lang="de">in das → ins · in eine Ausstellung · in einen Klub</p><h3>Everyday versus official</h3><p lang="de">15:30 → halb vier / fünfzehn Uhr dreißig<br/>1:00 → ein Uhr · 1:15 → Viertel nach eins</p><p>Everyday twelve-hour wording needs morning/evening context. Regional time expressions can differ.</p><p><b>Recall:</b> cover the words below a clock and say the time. Then make a weekday plan and move the entire time phrase to the front.</p><footer>Based on Momente A1.1 Lesson 8, © Hueber Verlag. Clock diagrams, plan combinations and the labelled duration comparison are study aids.</footer></div></div>;}
