"use client";
import {useState} from "react";
import Link from "next/link";
import type {WordCard} from "@/lib/content/word-card-types";
import {hobbyModels,hobbyPeople,abilityLevels,frequencyWords,abilityParts,abilitySentence,abilityMeaning,frequencySentence,frequencyMeaning} from "@/lib/study/hobbies-sheet";
import {CheatSheetNav} from "./CheatSheetNav";
import {GermanText,SaveButton} from "./StudyProvider";
import {LineAudio} from "./StudyAudio";
import {useStudyScope} from "./StudyScope";
import {WordFamilyPreview} from "../word-cards/WordFamilyPreview";
export function HobbiesCheatSheet({cards,speech}:{cards:WordCard[];speech:Record<string,string>}){
 const [hobby,setHobby]=useState(0),[person,setPerson]=useState(0),[level,setLevel]=useState(0),[question,setQuestion]=useState(false),[frequency,setFrequency]=useState(1),[english,setEnglish]=useState(true);
 const {matches}=useStudyScope();
 const parts=abilityParts(hobby,person,level,question),sentence=abilitySentence(hobby,person,level,question),meaning=abilityMeaning(hobby,person,level,question),often=frequencySentence(hobby,frequency);
 const say=(text:string)=><span className="sheet-spoken"><GermanText text={text}/><LineAudio compact text={text} src={speech[text]}/></span>;
 const shown=cards.filter(c=>c.studyTags&&matches(c.studyTags));
 return <div className="study-workspace hobbies-sheet"><CheatSheetNav current="hobbies"/><header className="study-page-header"><div><p className="study-eyebrow">Lesson 7 · Hobbies, abilities & frequency</p><h1>Can do. Like doing. How often?</h1><p>Three different meanings. Give each one its own place in your memory.</p></div></header><nav className="sheet-jump" aria-label="Hobbies sheet sections"><Link href="#hobby-map">Three meanings</Link><Link href="#ability-lab">Build a verb frame</Link><Link href="#frequency-lab">How often?</Link><Link href="#hobby-vowels">Vowel changes</Link><Link href="#hobby-words">Word cards</Link></nav>
 <section id="hobby-map"><h2>Keep these three questions apart.</h2><div className="hobby-meaning-map">{[{title:"CAN · ability",q:"How well?",de:"Ich kann gut kochen.",en:"I can cook well.",cue:"können + infinitive"},{title:"LIKE · enjoyment",q:"Do I enjoy it?",de:"Ich koche gern.",en:"I like cooking.",cue:"conjugated verb + gern"},{title:"OFTEN · frequency",q:"How often?",de:"Ich koche oft.",en:"I often cook.",cue:"conjugated verb + frequency"}].map((m,i)=><article key={m.title} data-meaning={i}><small>{m.q}</small><h3>{m.title}</h3><p>{say(m.de)}</p><p>{m.en}</p><b>{m.cue}</b><SaveButton item={{id:`l7-meaning-${i}`,title:m.de,meaning:m.en,kind:"concept",lesson:7,href:"/cheat-sheets/hobbies#hobby-map",audio:speech[m.de]??null}}/></article>)}</div></section>
 <section id="ability-lab" className="hobby-lab"><h2>Open the frame. Close it with the infinitive.</h2><p><b>Statement:</b> können in position 2. <b>Yes/no question:</b> können first. The activity verb stays at the end, without <span lang="de">zu</span>.</p><div className="hobby-pickers">{hobbyModels.map((h,i)=><button type="button" key={h.id} aria-pressed={hobby===i} onClick={()=>setHobby(i)}><span aria-hidden="true">{h.icon}</span><span lang="de">{h.de}</span></button>)}</div><div className="sheet-controls"><label>Person<select aria-label="Choose a person" value={person} onChange={e=>setPerson(Number(e.target.value))}>{hobbyPeople.map((p,i)=><option key={p.de} value={i}>{p.de} · {p.en}</option>)}</select></label><label>Ability<select aria-label="Choose an ability level" value={level} onChange={e=>setLevel(Number(e.target.value))}>{abilityLevels.map((a,i)=><option key={a.de} value={i}>{a.de} · {a.en}</option>)}</select></label><label><input type="checkbox" checked={question} onChange={e=>setQuestion(e.target.checked)}/> Make it a question</label><label><input type="checkbox" checked={english} onChange={e=>setEnglish(e.target.checked)}/> Show English</label></div><div className="hobby-frame" aria-live="polite">{parts.map((part,i)=><div key={i} data-part={i===(question?0:1)?"modal":i===3?"infinitive":"middle"}><small>{i===(question?0:1)?"KÖNNEN":i===3?"INFINITIVE · END":`BLOCK ${i+1}`}</small><span lang="de">{part}</span></div>)}</div><div className="hobby-result"><p>{say(sentence)}</p>{english&&<p>{meaning}</p>}<SaveButton item={{id:`l7-ability-${hobby}-${person}-${level}-${question}`,title:sentence,meaning,kind:"phrase",lesson:7,href:"/cheat-sheets/hobbies#ability-lab",audio:speech[sentence]??null}}/></div><div className="modal-person-map">{hobbyPeople.map((p,i)=><button type="button" key={p.de} aria-pressed={person===i} onClick={()=>setPerson(i)}><span lang="de">{p.de}</span><strong lang="de">{p.modal}</strong></button>)}</div><p>Singular: <b lang="de">kann · kannst · kann</b>. Plural: <b lang="de">können · könnt · können</b>. No <span lang="de">-e</span> for <span lang="de">ich</span>; no <span lang="de">-t</span> for <span lang="de">er</span>.</p></section>
 <section id="frequency-lab"><h2>A different scale: how often?</h2><p>Use the selected hobby. Tap a frequency word. The middle words have no fixed percentages.</p><div className="frequency-map">{frequencyWords.map((f,i)=><button type="button" key={f.de} aria-pressed={frequency===i} onClick={()=>setFrequency(i)}><strong lang="de">{f.de}</strong><span>{f.en}</span></button>)}</div><div className="hobby-frequency" aria-live="polite"><p>{say(often)}</p>{english&&<p>{frequencyMeaning(hobby,frequency)}</p>}<SaveButton item={{id:`l7-frequency-${hobby}-${frequency}`,title:often,meaning:frequencyMeaning(hobby,frequency),kind:"phrase",lesson:7,href:"/cheat-sheets/hobbies#frequency-lab",audio:speech[often]??null}}/></div></section>
 <section id="hobby-vowels"><h2>The vowel changes with du and er.</h2><div className="hobby-vowels">{[{de:"lesen",a:"liest",b:"liest",cue:"e → ie"},{de:"treffen",a:"triffst",b:"trifft",cue:"e → i"},{de:"fahren",a:"fährst",b:"fährt",cue:"a → ä"}].map(v=><article key={v.de}><strong>{v.cue}</strong><h3 lang="de">{v.de}</h3><p lang="de">du {v.a}<br/>er / sie / es {v.b}</p><p>After <span lang="de">können</span>: {say(`Du kannst ${v.de==="treffen"?"Freunde treffen":v.de}.`)}</p></article>)}</div><Link href="/lessons/07#practice">Test the whole lesson →</Link></section>
 <section id="hobby-words"><h2>Build your hobby vocabulary.</h2><p>{shown.length} word families match your selection.</p><div className="card-grid">{shown.map(c=><WordFamilyPreview key={c.id} card={c} href={c.path} lessonIds={c.lessons.map(n=>`lesson:${n.padStart(2,"0")}`)}/>)}</div></section><p className="muted">Based on Momente A1.1 KB 47–50, partner activities 162–163 and 194, AB 46–49 and the Lesson 7 glossary. Diagrams, examples and practice combinations are authored learning aids.</p></div>;
}
