"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {homeWords,homeLabels,homePronouns,homeExample,homePronounExample,homeAdjectives,homePhrases,type HomeTone,type HomeWord} from "@/lib/study/home";
import {GermanText,SaveButton,useStudy} from "./StudyProvider";
import {LineAudio} from "./StudyAudio";
import {HomeIllustration} from "./HomeIllustration";
import {CheatSheetNav} from "./CheatSheetNav";
import type {SavedItem} from "@/lib/study/types";

const roomIds=["bild","fenster","regal","lampe","sessel","sofa","tisch","teppich"];
const questions=[
  {q:"___ Stuhl",options:["der","das","die"],answer:"der",why:"Masculine: der Stuhl → er. Remember the blue chair.",id:"stuhl"},
  {q:"Die Lampe ist schön. ___ ist modern.",options:["Er","Es","Sie"],answer:"Sie",why:"Die Lampe is feminine, so it becomes sie even though it is an object.",id:"lampe"},
  {q:"One chair → several chairs",options:["die Stuhle","die Stühle","die Stuhlen"],answer:"die Stühle",why:"Stuhl → Stühle adds an umlaut and -e.",id:"stuhl"},
  {q:"Das Bett ist groß. ___ ist modern.",options:["Sie","Er","Es"],answer:"Es",why:"Neuter: das Bett → es.",id:"bett"},
  {q:"Die Möbel ___ modern.",options:["ist","sind","bist"],answer:"sind",why:"Furniture is plural in German: die Möbel sind …",id:"moebel"},
  {q:"Two shelving units",options:["die Regalen","die Regale","die Regals"],answer:"die Regale",why:"Regal → Regale adds -e. Learn the plural with the noun.",id:"regal"},
  {q:"The wardrobe is TOO small.",options:["Der Schrank ist sehr klein.","Der Schrank ist zu klein.","Der Schrank ist so klein."],answer:"Der Schrank ist zu klein.",why:"zu = too; sehr = very; so = so. Small is a description; too small is a problem.",id:"schrank"},
  {q:"I am at home.",options:["Ich bin zu Hause.","Ich bin das Zuhause.","Ich bin nach Hause."],answer:"Ich bin zu Hause.",why:"zu Hause means at home. Das Zuhause is the noun meaning home.",id:"zuhause"},
];

export function HomeCheatSheet({speech,cardLinks,saveIds}:{speech:Record<string,string>;cardLinks:Record<string,string>;saveIds:Record<string,string>}) {
  const study=useStudy();
  const [chosen,setChosen]=useState("stuhl");
  const [query,setQuery]=useState("");
  const [filter,setFilter]=useState<HomeTone|"all"|"saved">("all");
  const [scope,setScope]=useState("all");
  const [recall,setRecall]=useState(false);
  const [revealed,setRevealed]=useState<string[]>([]);
  const [position,setPosition]=useState(0);
  const [answer,setAnswer]=useState<string|null>(null);
  const [score,setScore]=useState(0);
  const [slow,setSlow]=useState(false);
  const current=homeWords.find(w=>w.id===chosen)!;
  const savedItem=(w:HomeWord):SavedItem=>({id:saveIds[w.id]??`home-${w.id}`,title:w.de,meaning:`${w.en}${w.plural?` · Plural: ${w.plural}`:""}`,kind:"word",href:cardLinks[w.id]??`/cheat-sheets/home#home-${w.id}`,audio:speech[w.de]??null});
  const clip=(text:string)=><LineAudio text={text} src={speech[text]} compact rate={slow ? 0.8 : 1}/>;
  const visible=homeWords.filter(w=>(filter==="all"||(filter==="saved"?study?.state.saved[saveIds[w.id]??`home-${w.id}`]:w.tone===filter))&&(scope==="all"||(scope==="book"?w.book.length:w.image))&&`${w.de} ${w.en} ${w.plural??""}`.toLocaleLowerCase("de").includes(query.trim().toLocaleLowerCase("de")));
  useEffect(()=>{const followHash=()=>{const id=window.location.hash.replace(/^#home-/,"");if(!homeWords.some(w=>w.id===id))return;setChosen(id);setFilter("all");setScope("all");setQuery("");setRecall(false);requestAnimationFrame(()=>document.getElementById(`home-${id}`)?.scrollIntoView());};followHash();window.addEventListener("hashchange",followHash);return()=>window.removeEventListener("hashchange",followHash);},[]);
  const question=questions[position];
  return <div className="home-sheet">
    <CheatSheetNav current="home"/>
    <header className="home-heading"><div><p className="study-eyebrow">Cheat sheets · 02 / The memory room</p><h1>A home for every word.</h1><p>See it. Say its article. Remember its plural.</p></div><button className="study-secondary" type="button" onClick={()=>{setFilter("all");setScope("all");setQuery("");setRecall(false);requestAnimationFrame(()=>window.print());}}>Print cheat sheet</button></header>
    <nav className="home-jump" aria-label="Home cheat sheet sections"><a href="#memory-room">Explore the room</a><a href="#home-patterns">Article → pronoun</a><a href="#home-index">All 30 words</a><a href="#home-describe">Describe & buy</a><a href="#home-practice">Test yourself</a></nav>
    <section className="home-room-layout" id="memory-room" aria-labelledby="room-title">
      <div className="home-room"><div className="home-room-heading"><p className="study-eyebrow">Your visual anchor</p><h2 id="room-title">Step into the memory room.</h2><p>Tap an object. Keep its color when you say its name.</p></div><div className="home-room-objects">{roomIds.map(id=>{const w=homeWords.find(w=>w.id===id)!;return <button type="button" key={id} onClick={()=>setChosen(id)} aria-pressed={chosen===id} aria-label={`Explore ${w.de}`} className={`study-tone-${w.tone}`}><HomeIllustration id={id}/><span lang="de">{w.de}</span></button>;})}</div><p className="home-room-foot">Blue der · Pink die · Green das · Purple plural</p></div>
      <div className={`home-focus study-tone-${current.tone}`}><label className="study-field">Explore a word<select aria-label="Explore a word" value={chosen} onChange={e=>setChosen(e.target.value)}>{homeWords.map(w=><option value={w.id} key={w.id}>{w.de} · {w.en}</option>)}</select></label><HomeIllustration id={current.id}/><p className="study-eyebrow">{homeLabels[current.tone]}</p><h2><GermanText text={current.de}/>{clip(current.de)}</h2><p className="home-focus-meaning">{current.en}</p><p className="home-focus-plural"><small>{current.tone==="plural"?"Plural only":current.plural?"More than one":"Normally used in the singular"}</small>{current.plural&&<><GermanText text={current.plural}/>{clip(current.plural)}</>}</p><p className="home-focus-cue">{current.cue}</p><div className="home-focus-sentence"><GermanText text={homeExample(current)}/>{clip(homeExample(current))}<br/><GermanText text={homePronounExample(current)}/>{clip(homePronounExample(current))}</div><div className="study-row"><SaveButton item={savedItem(current)}/>{cardLinks[current.id]&&<Link href={cardLinks[current.id]!}>Full vocabulary card →</Link>}</div></div>
    </section>
    <section id="home-patterns" className="home-patterns"><p className="study-eyebrow">The Lesson 4 shortcut</p><h2>The article leaves a color trail.</h2><p>German objects can become <b lang="de">er</b>, <b lang="de">sie</b> or <b lang="de">es</b>. Follow the noun’s grammatical gender.</p><div className="home-pronoun-map">{(["male","female","neuter","plural"] as const).map(tone=>{const w=homeWords.find(w=>w.id===({male:"stuhl",female:"lampe",neuter:"bett",plural:"moebel"}[tone]))!;return <div key={tone} className={`study-tone-${tone}`}><small>{homeLabels[tone]}</small><strong lang="de">{tone==="male"?"der":tone==="neuter"?"das":"die"} <span aria-hidden="true">→</span> {homePronouns[tone]}</strong><p><GermanText text={homeExample(w)}/>{clip(homeExample(w))}</p><p><GermanText text={homePronounExample(w)}/>{clip(homePronounExample(w))}</p></div>;})}</div><p className="home-note"><b>Plural has its own lane.</b> All plural nouns use <b lang="de">die</b> and <b lang="de">sie</b>. That does not make them feminine. <b lang="de">Die Möbel sind schön.</b></p>
      <div className="home-mini-rules"><div><h3>Plural memory hooks</h3><p lang="de"><b>+ umlaut + e</b> · Stuhl → Stühle · Schrank → Schränke</p><p lang="de"><b>+ s</b> · Sofa → Sofas · Radio → Radios</p><p lang="de"><b>Same spelling</b> · Sessel · Spiegel · Zimmer · Kissen</p><p>These are memory groups for these words. Always learn each noun with its own plural.</p></div><div><h3>The last noun runs the word.</h3><p lang="de">die Möbel + <b>das Geschäft</b><br/>→ <b className="study-tone-neuter">das Möbelgeschäft</b></p><p lang="de">das Hotel + <b>das Zimmer</b><br/>→ <b className="study-tone-neuter">das Hotelzimmer</b></p><p>A compound takes its gender from its last noun.</p></div></div>
    </section>
    <section id="home-index"><div className="study-section-heading"><div><p className="study-eyebrow">Your illustrated vocabulary wall</p><h2>30 words. One familiar world.</h2></div><button type="button" className="study-secondary" aria-pressed={recall} onClick={()=>{setRecall(!recall);setRevealed([]);}}>{recall?"Show all answers":"Hide answers & recall"}</button></div><div className="home-controls"><label className="study-field">Find a word<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="chair, Schrank, die Bücher…"/></label><label className="study-field">Word collection<select aria-label="Word collection" value={scope} onChange={e=>setScope(e.target.value)}><option value="all">Image + book additions</option><option value="image">Your image + its heading</option><option value="book">Mentioned in Lessons 1–4</option></select></label><button type="button" className="study-secondary" aria-pressed={slow} onClick={()=>setSlow(!slow)}>{slow?"Slow audio on":"Slow audio off"}</button></div><div className="study-chips" role="group" aria-label="Home word filter">{(["all","male","female","neuter","plural","saved"] as const).map(tone=><button type="button" key={tone} aria-pressed={filter===tone} onClick={()=>setFilter(tone)}>{tone==="all"?"All words":tone==="saved"?"Saved for review":homeLabels[tone]}</button>)}</div><p role="status" className="muted">{visible.length} words · {recall?"Name the picture, say its article, then reveal.":"Tap a German word for its meaning."}</p><div className="home-word-grid">{visible.map(w=>{const hidden=recall&&!revealed.includes(w.id);return <article key={w.id} id={`home-${w.id}`} data-home-word={w.id} className={`home-word-card${hidden?" is-hidden":` study-tone-${w.tone}`}`}><div className="home-card-top"><HomeIllustration id={w.id}/><SaveButton compact item={savedItem(w)}/></div>{hidden?<><h3>{w.en}</h3><button type="button" className="study-secondary" onClick={()=>setRevealed([...revealed,w.id])} aria-label={`Reveal ${w.en}`}>Reveal article & plural</button></>:<><small>{homeLabels[w.tone]}</small><h3><GermanText text={w.de}/>{clip(w.de)}</h3><p>{w.en}</p><div className="home-plural">{w.plural?<><GermanText text={w.plural}/>{clip(w.plural)}</>:w.tone==="plural"?"Plural only · takes sind":"Usually singular"}</div><details><summary>Memory cue & card</summary><p>{w.cue}</p>{cardLinks[w.id]&&<Link href={cardLinks[w.id]!}>Full vocabulary card →</Link>}</details></>}<p className="home-word-source">{w.book.length?w.book.join(" · "):w.id==="zuhause"?"Your image · heading":"Your image · extra vocabulary"}</p></article>;})}</div>{!visible.length&&<p className="home-empty">No words match. Choose All words or clear your search.</p>}</section>
    <section id="home-describe" className="home-describe"><p className="study-eyebrow">Use what you know · Lessons 2–4</p><h2>Give the room a voice.</h2><div className="home-adjectives">{homeAdjectives.map(a=><article key={a.de}><span aria-hidden="true">{a.symbol}</span><small>{a.cue}</small><p><GermanText text={a.de}/>{clip(a.de)}{a.opposite&&<> <span aria-hidden="true">↔</span> <GermanText text={a.opposite}/>{clip(a.opposite)}</>}</p><p>{a.en}{a.oppositeEn?` ↔ ${a.oppositeEn}`:""}</p></article>)}</div><div className="home-note"><b>Turn the volume up carefully:</b> <span lang="de">schön → sehr schön</span> = beautiful → very beautiful. <span lang="de">klein → zu klein</span> = small → too small. After <b lang="de">ist</b>, these adjectives keep their basic form: <b lang="de">Die Lampe ist schön.</b></div><div className="home-phrase-grid">{homePhrases.map((p,i)=><article key={p.de}><small>{p.cue}</small><p><GermanText text={p.de}/>{clip(p.de)}</p><p>{p.en}</p><SaveButton compact item={{id:`home-phrase-${i}`,title:p.de,meaning:p.en,kind:"phrase",href:"/cheat-sheets/home#home-describe",audio:speech[p.de]??null}}/></article>)}</div><p className="home-note"><b lang="de">das Zuhause</b> = home, the noun. <b lang="de">zu Hause</b> = at home, the phrase in Lesson 4. <b lang="de">zuhause</b> is also a correct spelling of the phrase. <a href="https://www.duden.de/sprachwissen/sprachratgeber/zu-Hause-oder-Zuhause" target="_blank" rel="noreferrer">Duden ↗</a></p></section>
    <section id="home-practice" className="home-practice"><div><p className="study-eyebrow">A quick room check</p><h2>Can you name it and use it?</h2><p>Try eight questions. Save a difficult word and revisit it in My review.</p></div>{question?<div className="home-quiz"><small>Question {position+1} / {questions.length}</small><h3>{question.q}</h3><div className="home-quiz-options">{question.options.map(option=><button type="button" key={option} lang="de" disabled={answer!==null} aria-pressed={answer===option} data-answer={answer===null?undefined:option===question.answer?"correct":option===answer?"wrong":undefined} onClick={()=>{setAnswer(option);if(option===question.answer)setScore(score+1);}}>{option}</button>)}</div>{answer!==null&&<div className="home-feedback" role="status"><strong>{answer===question.answer?"Exactly.":"Keep this pattern:"}</strong><p>{question.why}</p><div className="study-row"><SaveButton item={savedItem(homeWords.find(w=>w.id===question.id)!)}/><button type="button" className="study-primary" onClick={()=>{setPosition(position+1);setAnswer(null);}}>Next →</button></div></div>}</div>:<div className="home-quiz" role="status"><h3>{score} / {questions.length}</h3><p>{score===questions.length?"The room is yours. Try the hidden-answer vocabulary wall next.":"Keep the tricky words in My review and try again."}</p><button type="button" className="study-primary" onClick={()=>{setPosition(0);setAnswer(null);setScore(0);}}>Practise again</button></div>}</section>
    <details className="home-sources"><summary>Coverage & sources</summary><p>All 20 labelled objects and the Zuhause heading from your supplied easydeutsch image, plus related words from Momente A1.1 Lessons 1–4: Bild, Sessel, Möbel, Geschäft, Möbelgeschäft, Hotel, Hotelzimmer, Wohnort and Buch. Items from the image that occur later in the course are labelled as extra vocabulary here. The book additions include vocabulary from exercise instructions.</p><p>Book patterns: KB 15–18, 29–32; AB 26–29; German–English glossary pp. 5–6. Momente © Hueber Verlag. Illustrations, memory cues and example combinations were created for this sheet. Audio uses existing pronunciation clips where available, with synthesized speech for additions.</p><Link href="/references">Course sources & credits →</Link></details><p className="home-credit">Reference vocabulary: your easydeutsch image + Momente A1.1 Lessons 1–4, © Hueber Verlag. Original line illustrations and learning notes.</p>
  </div>;
}
