"use client";
import {seasons,monthEnglish,journeyActivities,journeyPeople} from "@/lib/study/journey-sheet";
import {journeyStages,yearChunks} from "@/lib/study/journey-learning";
import "./JourneyLearning.css";

export function SeasonWheel({month,onChoose}:{month:string;onChoose:(month:string)=>void}){
 const selected=seasons.find(season=>season.months.some(value=>value===month))??seasons[0];
 return <div><p>A three-month learning calendar for Germany. Colour marks the season; every month and season here uses <b lang="de">der</b>.</p><div className="season-wheel" role="group" aria-label="Choose a season"><svg viewBox="0 0 360 360" aria-hidden="true"><path d="M180 180V20A160 160 0 0 1 340 180Z" fill="#dfecdc"/><path d="M180 180H340A160 160 0 0 1 180 340Z" fill="#fff0be"/><path d="M180 180V340A160 160 0 0 1 20 180Z" fill="#f8e1cf"/><path d="M180 180H20A160 160 0 0 1 180 20Z" fill="#dfecf6"/><circle cx="180" cy="180" r="160" fill="none" stroke="#789aa8" strokeWidth="2"/></svg>{seasons.map((season,index)=><button type="button" key={season.name} data-season={index} aria-pressed={selected.name===season.name} onClick={()=>onChoose(season.months[0])}><b lang="de">der {season.name}</b><span>{season.en}</span></button>)}<div aria-hidden="true"><b>der</b><small>im = in dem</small></div></div><div className="season-month-choice" role="group" aria-label={`${selected.en} months`}>{selected.months.map(value=><button type="button" key={value} aria-pressed={month===value} onClick={()=>onChoose(value)}><b lang="de">der {value}</b><span>{monthEnglish[value]}</span></button>)}</div></div>;
}
const tripPaths=[
 "M18 15h64v57H18ZM25 24h19v23H25Zm31 0h19v23H56ZM18 59h64M29 73l-8 15m49-15 8 15M32 63h1m34 0h1",
 "M20 84V16h58L65 32l13 16H20M12 85h34M51 69h33m-10-10 10 10-10 10",
 "M29 18a10 10 0 1 0 .1 0M73 18a10 10 0 1 0 .1 0M29 39v29l-12 20m12-20 13 20M73 39v29L61 88m12-20 13 20M29 46l23 15 21-15",
 "M15 32h70v48H15ZM29 32l7-14h28l7 14M50 42a14 14 0 1 0 .1 0M74 41h3",
];
export function JourneyEventIllustration({index}:{index:number}){return <svg className="journey-event-art" viewBox="0 0 100 100" fill="none" stroke="currentColor" strokeWidth="2.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><circle cx="50" cy="50" r="47" fill="#eaf2eb" stroke="none"/><path d={tripPaths[index]}/></svg>;}
export function JourneyTimeline({activity,onChoose}:{activity:number;onChoose:(activity:number)=>void}){return <div><p>A sample trip. Choose an event and follow its verb into the past.</p><div className="journey-stage-map">{journeyStages.map((stage,index)=><button type="button" key={stage.activity} aria-pressed={activity===stage.activity} onClick={()=>onChoose(stage.activity)}><small>{index+1} · {stage.label}</small><JourneyEventIllustration index={index}/><b lang="de">{journeyActivities[stage.activity]!.verb}</b></button>)}</div></div>;}
export function AuxiliaryTrail({activity,person}:{activity:number;person:number}){const verb=journeyActivities[activity]!,subject=journeyPeople[person]!,aux=verb.aux==="sein"?subject.be:subject.have;return <div><div className="journey-aux-trail" data-aux={verb.aux}><div><small>1 · READ THE EXACT VERB</small><strong lang="de">{verb.verb}</strong><span>{verb.base}</span></div><div><small>2 · ITS AUXILIARY HERE</small><strong lang="de">{verb.aux}</strong><span>{verb.verb==="bleiben"?"Learn bleiben separately: staying still uses sein.":"Use this auxiliary with the taught meaning shown here."}</span></div><div><small>3 · MATCH THE PERSON</small><strong lang="de">{subject.de} {aux} … {verb.part}</strong></div></div><p>These cues cover the examples here, not every use of every verb. Learn the verb and auxiliary together; movement during an activity alone does not decide.</p></div>;}
export function YearChunks({year}:{year:number}){return <div role="group" className="year-chunks" aria-label="Year pronunciation chunks">{yearChunks(year).map((chunk,index)=><span key={index} lang="de">{chunk}</span>)}</div>;}
