"use client";
import {useState} from 'react';
import Link from 'next/link';
import type {WordCard} from '@/lib/content/word-card-types';
import {seasons,monthEnglish,journeyPeople,journeyActivities,journeyParts,journeySentence,journeyMeaning,journeySaveId,seasonSentence,spokenYear,auxiliaryCases} from '@/lib/study/journey-sheet';
import {GermanText,SaveButton} from './StudyProvider';
import {LineAudio} from './StudyAudio';
import {CheatSheetNav} from './CheatSheetNav';
import {useStudyScope} from './StudyScope';
import {WordFamilyPreview} from '../word-cards/WordFamilyPreview';
export function JourneyCheatSheet({cards,speech}:{cards:WordCard[];speech:Record<string,string>}){
 const [month,setMonth]=useState('März'),[activity,setActivity]=useState(0),[person,setPerson]=useState(0),[question,setQuestion]=useState(false),[english,setEnglish]=useState(true),[reveal,setReveal]=useState(true),[year,setYear]=useState('1986'),[position,setPosition]=useState(0),[answer,setAnswer]=useState<string|null>(null);
 const {matches}=useStudyScope(),shown=cards.filter(c=>c.studyTags&&matches(c.studyTags));const sentence=journeySentence(activity,person,question),meaning=journeyMeaning(activity,person,question),a=journeyActivities[activity]!,parts=journeyParts(activity,person,question),quiz=auxiliaryCases[position]!;
 const yearValue=Number(year),yearValid=/^\d{4}$/.test(year)&&yearValue>=1900&&yearValue<=2099;
 const say=(text:string)=><span className="sheet-spoken"><GermanText text={text}/><LineAudio compact text={text} src={speech[text]}/></span>;
 return <div className="study-workspace journey-sheet"><CheatSheetNav current="journeys"/><header className="study-page-header"><div><p className="study-eyebrow">Lesson 12 · Seasons, journeys & the past</p><h1>A year of stories.</h1><p>Remember when it happened, where you went, and which verb brings the sentence together.</p></div></header><nav className="sheet-jump" aria-label="Journey sheet sections"><a href="#season-calendar">Months & seasons</a><a href="#journey-lab">Haben or sein?</a><a href="#journey-check">Quick recall</a><a href="#journey-background">War & hatte</a><a href="#journey-years">Say the year</a><a href="#journey-words">Word cards</a></nav>
 <section id="season-calendar"><h2>Twelve months. Four seasons. One article.</h2><p className="journey-gender-note"><b lang="de">DER</b> Every month and season here is masculine. <b lang="de">im = in dem</b>: <span lang="de">im März · im Frühling</span>.</p><div className="season-calendar">{seasons.map((s,i)=><article key={s.name} data-season={i}><h3><span aria-hidden="true">{s.icon}</span> {say(`der ${s.name}`)}</h3><small>{s.en} · {say(`im ${s.name}`)}</small><div>{s.months.map(m=><button type="button" key={m} aria-pressed={month===m} onClick={()=>setMonth(m)}><span lang="de">der {m}</span><small>{monthEnglish[m]}</small></button>)}</div></article>)}</div><div className="season-output" aria-live="polite"><p>{say(seasonSentence(month))}</p><span>I traveled to Hamburg in {monthEnglish[month]}.</span></div><div className="journey-time-map"><article><b lang="de">im</b><p>Month or season</p><span lang="de">im März · im Frühling</span></article><article><b lang="de">am</b><p>Day or day part</p><span lang="de">am Montag · am Abend</span></article><article><b lang="de">um</b><p>Clock time</p><span lang="de">um acht Uhr</span></article><article><b lang="de">seit</b><p>From then until now</p><span lang="de">seit 1977</span></article></div><p><b>Seit wann?</b> asks when an ongoing situation began: <span lang="de">Das Fest gibt es seit 1977.</span> The date comes from the book’s festival text.</p></section>
 <section id="journey-lab"><h2>The action chooses haben or sein.</h2><div className="journey-aux-map"><article data-aux="sein"><h3 lang="de">SEIN → bin · bist · ist …</h3><p>Going, arriving and changing location in these examples.</p><p lang="de">ist gefahren · ist angekommen</p><b>Remember separately:</b><p>{say('ist geblieben')} · {say('ist passiert')} · {say('ist gewesen')}</p></article><article data-aux="haben"><h3 lang="de">HABEN → habe · hast · hat …</h3><p>Other actions during the trip keep haben.</p><p lang="de">hat besucht · hat gefeiert · hat fotografiert</p><b>The verb matters:</b><p lang="de">ist Fahrrad gefahren<br/>hat eine Radtour gemacht</p></article></div><div className="sheet-controls"><label>Action<select aria-label="Journey action" value={activity} onChange={e=>setActivity(Number(e.target.value))}>{journeyActivities.map((a,i)=><option value={i} key={a.verb}>{a.verb} · {a.detail||a.base}</option>)}</select></label><label>Person<select aria-label="Journey person" value={person} onChange={e=>setPerson(Number(e.target.value))}>{journeyPeople.map((p,i)=><option value={i} key={p.de}>{p.de}{p.de==='Sie'?' · formal you':''}</option>)}</select></label></div><div className="sheet-controls"><label><input type="checkbox" checked={question} onChange={e=>setQuestion(e.target.checked)}/> Make a yes/no question</label><label><input type="checkbox" checked={english} onChange={e=>setEnglish(e.target.checked)}/> Show English</label><label><input type="checkbox" checked={reveal} onChange={e=>setReveal(e.target.checked)}/> Reveal the auxiliary</label></div><div className="journey-sentence" data-aux={a.aux} aria-live="polite"><div className="journey-parts" aria-label="Journey sentence word order">{parts.map((p,i)=><span key={i} data-role={p.role}><small>{p.role==='auxiliary'?'AUXILIARY':p.role==='participle'?'PAST PARTICIPLE':p.role.toUpperCase()}</small><strong lang="de">{p.role==='auxiliary'&&!reveal?'…':p.text}</strong></span>)}</div>{reveal?<p className="journey-result">{say(sentence)}</p>:<button className="study-secondary" type="button" onClick={()=>setReveal(true)}>Reveal the complete sentence</button>}{english&&<p>{meaning}</p>}<SaveButton item={{id:journeySaveId(activity,person,question),title:sentence,meaning,kind:'phrase',lesson:12,href:'/cheat-sheets/journeys#journey-lab',audio:speech[sentence]??null}}/></div><p><Link href="/cheat-sheets/past#past-patterns">Need the participle itself? Review the four patterns →</Link></p></section>
 <section id="journey-check"><h2>Choose before you reveal.</h2><div className="journey-quiz"><small>{position+1} / {auxiliaryCases.length}</small><h3 lang="de">{quiz.de}</h3><div className="study-row">{quiz.choices.map(c=><button className="study-secondary" type="button" key={c} disabled={answer!==null} onClick={()=>setAnswer(c)}>{c}</button>)}</div>{answer!==null&&<div role="status"><p>{answer===quiz.answer?'Correct.':`Use ${quiz.answer}.`} {quiz.why}</p>{say(quiz.de.replace('___',quiz.answer))}</div>}<button className="study-primary" type="button" onClick={()=>{setPosition((position+1)%auxiliaryCases.length);setAnswer(null);}}>Next contrast →</button></div></section>
 <section id="journey-background"><h2>War and hatte: the background in one verb.</h2><div className="journey-background"><article><h3 lang="de">sein → war</h3><p lang="de">ich war · du warst · er/sie/es war<br/>wir waren · ihr wart · sie/Sie waren</p>{say('Die Reise war sehr schön.')}</article><article><h3 lang="de">haben → hatte</h3><p lang="de">ich hatte · du hattest · er/sie/es hatte<br/>wir hatten · ihr hattet · sie/Sie hatten</p>{say('Wir hatten viel Spaß.')}</article></div><p>These Präteritum forms are common in conversation. They stand alone: <span lang="de">Ich war in Berlin.</span> Perfekt uses two parts: <span lang="de">Ich bin in Berlin gewesen.</span></p><p><b>Destination:</b> <span lang="de">nach Hamburg / Österreich</span>, but <span lang="de">in die Schweiz / in den Iran</span>. <Link href="/cheat-sheets#country-overview">See the country article map →</Link></p></section>
 <section id="journey-years"><h2>Hear the year in chunks.</h2><label>Year, 1900–2099<input aria-label="Year to pronounce" inputMode="numeric" pattern="[0-9]*" value={year} onChange={e=>setYear(e.target.value)}/></label><div className="journey-year-output" aria-live="polite">{yearValid?<><p>{say(spokenYear(yearValue))}</p><small>{yearValue<2000?'neunzehnhundert + the last two digits':'zweitausend + the last two digits'}</small></>:<p role="alert">Enter a year from 1900 to 2099.</p>}</div></section>
 <section id="journey-words"><h2>Your Lesson 12 words.</h2><p>{shown.length} word families match your selection.</p><div className="card-grid">{shown.map(c=><WordFamilyPreview key={c.id} card={c} href={c.path} lessonIds={c.lessons.map(n=>`lesson:${n.padStart(2,'0')}`)}/>)}</div></section><Link href="/lessons/12#practice">Practise the final lesson →</Link><p className="muted">Based on Momente A1.1 KB 73–82 and 170–171, AB 74–85 and 92, and glossary pages 16–17. Sentence combinations, diagrams and drills are authored learning aids.</p></div>;
}
