"use client";
import {Fragment,useEffect,useState} from "react";
import type {WordCard} from "@/lib/content/word-card-types";
import {germanNumber,germanPrice,sheetQuizzes} from "@/lib/study/sheet-topics";
import {listeningNumbers,numberParts,type NumberRange} from "@/lib/study/number-learning";
import {wordStudyTags} from "@/lib/study/tags";
import {savedWordCard} from "@/lib/study/saved-word-card";
import {GermanLookup,GermanText,SaveButton} from "./StudyProvider";
import {StudyScopeNotice} from "./StudyScope";
import {LineAudio} from "./StudyAudio";
import {OverviewPanel} from "./OverviewPanel";
import "./NumbersWorkshop.css";
import "./CheatSheetPrint.css";

const numberGroups=[{title:"Start here · 0–12",values:[0,1,2,3,4,5,6,7,8,9,10,11,12]},{title:"The teens · 13–19",values:[13,14,15,16,17,18,19]},{title:"The tens · 20–90",values:[20,30,40,50,60,70,80,90]},{title:"Go bigger",values:[100,200,1000,10000,100000,1000000]}];
const extensionTags={lessons:[4],concepts:["numbers"] as const,source:"course" as const};

function NumberListening({cards,speech,range}:{cards:WordCard[];speech:Record<string,string>;range:NumberRange}){
  const pool=listeningNumbers(cards,range);
  const [position,setPosition]=useState(0),[typed,setTyped]=useState(""),[checked,setChecked]=useState(false),[score,setScore]=useState(0);
  const item=pool[position];
  if(!pool.length)return <p role="status">No numbers in this range match your study selection and card filters. Choose another range or clear the filters.</p>;
  if(!item)return <div role="status"><h3>{score} / {pool.length} heard correctly</h3><p>Try the difficult numbers again, or change the range.</p><button type="button" className="study-secondary" onClick={()=>{setPosition(0);setScore(0);setTyped("");setChecked(false);}}>Listen again</button></div>;
  const form=item.card.rows[0]!.singular;
  const correct=/^\d+$/.test(typed.trim())&&Number(typed)===item.value;
  return <div className="number-listening-task"><p>Recording {position+1} / {pool.length}</p><LineAudio key={item.value} text={form.text} src={form.audio??speech[form.text]} label="practice number"/>
    <form onSubmit={event=>{event.preventDefault();if(!checked&&typed.trim()){setChecked(true);if(correct)setScore(score+1);}}}><label>What number did you hear?<input inputMode="numeric" autoComplete="off" value={typed} disabled={checked} onChange={event=>setTyped(event.target.value)} maxLength={6}/></label><button type="submit" className="study-primary" disabled={checked||!typed.trim()}>Check number</button></form>
    {checked&&<div role="status"><h3>{correct?"Exactly.":"Listen once more, then compare."}</h3><p><b>{item.value}</b> · <GermanText text={form.text}/></p><p>{item.card.tip}</p><div className="study-row"><SaveButton item={savedWordCard(item.card)}/><button type="button" className="study-primary" onClick={()=>{setPosition(position+1);setTyped("");setChecked(false);}}>Next number →</button></div></div>}
  </div>;
}

export function NumbersWorkshop({cards,allCards,speech}:{cards:WordCard[];allCards:WordCard[];speech:Record<string,string>}){
  const [number,setNumber]=useState("21"),[price,setPrice]=useState("24,50"),[phone,setPhone]=useState("0176"),[range,setRange]=useState<NumberRange>("all");
  useEffect(()=>{const restore=()=>{const hash=window.location.hash;const numberMatch=hash.match(/^#number-(\d{1,7})$/);if(numberMatch&&Number(numberMatch[1])<=1000000){setNumber(numberMatch[1]!);requestAnimationFrame(()=>document.getElementById("number-builder")?.scrollIntoView({block:"start"}));}else if(hash.startsWith("#price-")){try{const raw=decodeURIComponent(hash.slice(7));if(germanPrice(raw)){setPrice(raw);requestAnimationFrame(()=>document.getElementById("number-price")?.scrollIntoView({block:"start"}));}}catch{/* Ignore malformed saved links. */}}};restore();window.addEventListener("hashchange",restore);return()=>window.removeEventListener("hashchange",restore);},[]);
  const valid=/^\d{1,7}$/.test(number)&&Number(number)<=1000000,value=valid?Number(number):0,word=valid?germanNumber(value):null;
  const card=allCards.find(card=>card.id===`N${String(value).padStart(3,"0")}`);
  const tags=card?wordStudyTags(card):{...extensionTags,concepts:[...extensionTags.concepts]};
  const priceText=germanPrice(price),digits=phone.replace(/[\s()+-]/g,"");
  const phoneText=/^\d{1,20}$/.test(digits)?[...digits].map(n=>germanNumber(Number(n))).join(", "):null;
  const spoken=(text:string)=><span className="sheet-spoken"><GermanText text={text}/><LineAudio text={text} src={speech[text]} compact/></span>;
  const parts=valid?numberParts(value):[];
  return <>
    <section className="sheet-workshop" id="number-builder"><p className="study-eyebrow">See the digits. Follow the spoken order.</p><h2>The German number builder.</h2><p>Explore any number here. The listening and card practice below follow your study selection.</p><label className="sheet-number-input">Type a whole number from 0 to 1,000,000<input inputMode="numeric" value={number} onChange={event=>setNumber(event.target.value)} maxLength={7}/></label>
      {word?<><StudyScopeNotice tags={tags} subject="This number example"/><div className="number-stage" aria-live="polite"><strong>{value.toLocaleString("de-DE")}</strong><p lang="de"><span className="sheet-spoken number-word"><GermanLookup text={word}>{parts.map((part,index)=><Fragment key={index}>{index>0&&<wbr/>}<span data-role={part.role}>{part.spoken}</span></Fragment>)}</GermanLookup><LineAudio text={word} src={speech[word]} compact/></span></p></div><div role="group" className="number-reading-order" aria-label="German spoken order">{parts.map((part,index)=><div key={index} data-role={part.role}><small>{index+1} · {part.label}</small><b>{part.digits}</b><strong lang="de">{part.spoken}</strong></div>)}</div><p className="sheet-note">{value===1000000?"Million is a noun: capital M, feminine eine.":value>=100?"Read thousands and hundreds first. In a final two-digit block above twenty, say the units before the tens.":value>=20&&value%10?"The digits show tens then units; German says units + und + tens. Write these chunks as one word.":"Learn this foundation word as a whole."} Teal marks units and amber marks tens here; these colors describe number parts, not noun gender.</p><SaveButton item={{id:`number-example-${value}`,title:word,meaning:`${value.toLocaleString("de-DE")} · ${parts.map(part=>part.spoken).join(" + ")}`,kind:"concept",href:`/cheat-sheets/numbers#number-${value}`,studyTags:tags,audio:speech[word]??card?.rows[0]?.singular.audio??null}}/></>:<p role="alert">Enter a whole number from 0 to 1,000,000.</p>}
      <div className="study-chips">{[16,17,21,30,60,70,99,452,1000,1000000].map(n=><button type="button" key={n} onClick={()=>setNumber(String(n))}>{n.toLocaleString("de-DE")}</button>)}</div>
    </section>
    <OverviewPanel title="The number ladder"><div className="number-ladder">{numberGroups.map(group=><div key={group.title}><h3>{group.title}</h3>{group.values.map(n=><button type="button" key={n} onClick={()=>setNumber(String(n))}><b>{n.toLocaleString("de-DE")}</b><span lang="de">{germanNumber(n)}</span></button>)}</div>)}</div><p className="sheet-note"><b>Shortcuts:</b> sechzehn, siebzehn, sechzig, siebzig. <b>Spelling:</b> dreißig. <b>One:</b> eins alone → einundzwanzig → ein Euro → eine Million.</p></OverviewPanel>
    <section className="sheet-workshop" id="number-listening"><p className="study-eyebrow">Hear → type → check</p><h2>Can you hear the difference?</h2><p>Practise up to eight numbers from the visible card selection. Replay as often as you need; change the shared audio speed in Settings.</p><label>Listening range<select value={range} onChange={event=>setRange(event.target.value as NumberRange)}><option value="all">Mixed · 0–100</option><option value="foundation">Foundation · 0–12</option><option value="teens">Teens · 13–19</option><option value="tens">Tens and combinations · 20–100</option></select></label><NumberListening key={`${range}:${cards.map(card=>card.id).join(",")}`} cards={cards} speech={speech} range={range}/></section>
    <section className="sheet-rule-grid"><article id="number-price"><h2>Read the price.</h2><StudyScopeNotice tags={{...extensionTags,concepts:[...extensionTags.concepts]}} subject="This price example"/><label>Price in euros<input inputMode="decimal" value={price} onChange={event=>setPrice(event.target.value)} maxLength={7}/></label><div className="number-price-tag" aria-live="polite">{priceText?<><strong>{Number(price.trim().replace(",",".")).toLocaleString("de-DE",{minimumFractionDigits:2,maximumFractionDigits:2})} €</strong><p>{spoken(priceText)}</p><SaveButton item={{id:`number-price-${Number(price.trim().replace(",",".")).toFixed(2)}`,title:priceText,meaning:`${price} € · read euros, then cents.`,kind:"concept",href:`/cheat-sheets/numbers#price-${encodeURIComponent(price.trim())}`,studyTags:{...extensionTags,concepts:[...extensionTags.concepts]},audio:speech[priceText]??null}}/></>:<p>Use a price such as 24,50 (up to 9999,99).</p>}</div><div className="study-chips">{["1,00","0,50","24,50"].map(example=><button type="button" key={example} onClick={()=>setPrice(example)}>{example} €</button>)}</div><p>The comma separates euros and cents. In conversation, <span lang="de">vierundzwanzig fünfzig</span> is also common when the currency is clear.</p>{spoken("Was kostet das?")}<p>How much does that cost?</p></article>
    <article><h2>Phone numbers: one digit at a time.</h2><label>Practice digits<input inputMode="tel" value={phone} onChange={event=>setPhone(event.target.value)} maxLength={25}/></label><p aria-live="polite">{phoneText?spoken(phoneText):"Enter up to 20 digits. Spaces, +, (), and hyphens are separators."}</p><p>Keep the zero at the start. This tool reads the digits only; it does not place a call or save your number.</p></article></section>
    <details className="sheet-sources"><summary>Eight common number and price traps</summary><div className="sheet-rule-grid">{sheetQuizzes.numbers.map(quiz=><article key={quiz.q}><h3>{quiz.q}</h3><p>{spoken(quiz.answer)}</p><p>{quiz.why}</p></article>)}</div></details>
  </>;
}

export function NumbersPrintSummary(){return <div className="sheet-print-summary"><section className="sheet-print-page number-print"><header><span>05 · Numbers & prices</span><h2>Digits left to right. Units before tens.</h2><p>Common numbers, reading order and prices · complete builder and listening recall online.</p></header><div className="number-print-groups">{numberGroups.map(group=><section key={group.title}><h3>{group.title}</h3>{group.values.map(n=><p key={n}><b>{n.toLocaleString("de-DE")}</b><span lang="de">{germanNumber(n)}</span></p>)}</section>)}</div><h3>See 4–5–2. Say 400 → 2 → and → 50.</h3><div className="number-reading-order">{numberParts(452).map((part,index)=><div key={index} data-role={part.role}><small>{part.label}</small><b>{part.digits}</b><strong lang="de">{part.spoken}</strong></div>)}</div><p lang="de"><b>452 = vierhundertzweiundfünfzig</b></p><p>Thousands and hundreds come first. The units-before-tens pattern applies inside the remaining two-digit block. Write ordinary whole numbers below a million as one word.</p><h3>One changes with its job</h3><p lang="de">1 → <b>eins</b> · 21 → <b>ein</b>undzwanzig · 1,00 € → <b>ein</b> Euro · 1.000.000 → <b>eine</b> Million</p><h3>Read a price tag</h3><p lang="de">24,50 € → vierundzwanzig Euro fünfzig Cent<br/>0,50 € → fünfzig Cent · 1,01 € → ein Euro ein Cent</p><p>The comma separates euros and cents. In a clear price context, vierundzwanzig fünfzig is also common.</p><h3>Phone numbers keep their first zero</h3><p lang="de">0176 → null · eins · sieben · sechs</p><p><b>Recall:</b> cover the German column, say the number, then check. Compare 13/30, 16/60 and 17/70 using the listening activity.</p><footer>Based on Momente A1.1 number and price patterns, © Hueber Verlag. Diagrams and practice combinations are study aids. Teal/amber distinguish units/tens, separate from noun-gender colors.</footer></section></div>;}
