import {objectModels,colourSwatches,materialModels} from "@/lib/study/object-sheet";
import {officeModels,pluralFamilies,phoneSteps} from "@/lib/study/office-sheet";
import {ObjectIllustration,OfficeIllustration} from "./ObjectIllustration";
import "./CheatSheetPrint.css";
import "./ObjectLearning.css";

export function ObjectPrintSummary(){return <div className="sheet-print-summary"><div className="sheet-print-page"><header><span>08 · Objects, colours & materials</span><h2>One noun. One article trail.</h2><p>Name it with ein/eine. Correct a guess with kein/keine. Refer to it with er/es/sie.</p></header><div className="object-print-grid">{objectModels.map((item,index)=><article key={item.de} data-gender={item.gender}><ObjectIllustration index={index} colour={colourSwatches.find(row=>row[0]===item.colour)![2]}/><strong lang="de">{item.de}</strong><small>{item.en}</small><p lang="de">{item.article} → {item.indefinite} → {item.negative} → {item.pronoun}</p><p lang="de">Das ist {item.indefinite} {item.noun}.<br/>{item.pronoun[0]!.toUpperCase()+item.pronoun.slice(1)} ist {item.colour}.</p></article>)}</div><div className="object-print-rules"><h3>Nominative after Das ist …</h3><p lang="de">Das ist ein Tisch. · Das ist ein Buch. · Das ist eine Uhr.</p><p>Correct the wrong name, then give the right one:</p><p lang="de">Das ist kein Buch. Das ist eine Uhr.</p></div><table className="object-print-table"><caption>Material: aus + material name, usually without an article</caption><tbody>{materialModels.map(([de,en,sentence])=><tr key={de}><th lang="de">aus {de}</th><td>{en}</td><td lang="de">{sentence}</td></tr>)}</tbody></table><h3>Colour after ist: no extra ending</h3><p>{colourSwatches.map(([de,en])=>`${de} = ${en}`).join(" · ")}</p><p lang="de">hellbraun = light brown · dunkelgrün = dark green</p><h3>Recall aloud</h3><p>Cover a noun’s trail. Say its article, a new thing, a correction and its pronoun. Describe the material and colour.</p><footer>Based on Momente A1.1 Lesson 5, © Hueber Verlag. Illustrations, descriptions and practice combinations are study aids. Object paint colour and grammatical gender colour have different jobs.</footer></div></div>;}

export function OfficePrintSummary(){return <div className="sheet-print-summary"><div className="sheet-print-page"><header><span>09 · Office, plurals & accusative</span><h2>Only masculine singular changes here.</h2><p>Name a thing → have it, need it or look for it. Keep its gender and learn its plural.</p></header><table><thead><tr><th>Gender</th><th>Nominative</th><th>Accusative</th></tr></thead><tbody><tr data-gender="male"><th>Masculine</th><td lang="de">der · ein · kein</td><td lang="de">den · einen · keinen</td></tr><tr data-gender="neuter"><th>Neuter</th><td lang="de">das · ein · kein</td><td lang="de">das · ein · kein</td></tr><tr data-gender="female"><th>Feminine</th><td lang="de">die · eine · keine</td><td lang="de">die · eine · keine</td></tr><tr data-gender="plural"><th>Plural</th><td lang="de">die · — · keine</td><td lang="de">die · — · keine</td></tr></tbody></table><div className="object-print-rules"><p lang="de">Das ist ein Kalender. → Ich brauche einen Kalender.<br/>Das ist eine Maus. → Ich habe eine Maus.<br/>Das sind Stifte. → Ich suche keine Stifte.</p></div><div className="object-print-grid">{officeModels.map((item,index)=><article key={item.de} data-gender={item.gender}><OfficeIllustration index={index}/><strong lang="de">{item.de}</strong><small>{item.meaning}</small><p className="office-plural" lang="de">die {item.plural}</p></article>)}</div><table className="object-print-table"><caption>Five plural families: learn each pair, not a universal rule</caption><tbody>{pluralFamilies.map(family=><tr key={family.ending}><th>{family.ending}</th><td lang="de">{family.example}</td></tr>)}</tbody></table><h3>On the phone</h3><p lang="de">{phoneSteps[2]!.de} · {phoneSteps[3]!.de}<br/>Einen Moment bitte. · Auf Wiederhören.</p><p><b>Recall:</b> point to an object. Name it, make a sentence with brauche, then make it negative or plural.</p><footer>Based on Momente A1.1 Lesson 6, © Hueber Verlag. Scene illustrations, sentence combinations and phone-role practice are study aids.</footer></div></div>;}
