"use client";
import {useState} from "react";
import Link from "next/link";
import type {WordCard} from "@/lib/content/word-card-types";
import type {StudyUnit} from "@/lib/study/course-lessons";
import {objectModels,objectSentences,colourSwatches,materialModels} from "@/lib/study/object-sheet";
import {tagsForLesson} from "@/lib/study/scope";
import {CheatSheetNav} from "./CheatSheetNav";
import {GermanText,SaveButton} from "./StudyProvider";
import {LineAudio} from "./StudyAudio";
import {StudyTagList,useStudyScope} from "./StudyScope";
import {WordFamilyPreview} from "../word-cards/WordFamilyPreview";
import {CoursePatterns} from "./CourseStudy";

export function ObjectCheatSheet({cards,speech,unit}:{cards:WordCard[];speech:Record<string,string>;unit:StudyUnit}){
  const [index,setIndex]=useState(0),[negative,setNegative]=useState(false),[query,setQuery]=useState("");
  const {matches}=useStudyScope();
  const item=objectModels[index]!,sentences=objectSentences(index);
  const say=(text:string)=><div className="study-row"><GermanText text={text}/><LineAudio text={text} src={speech[text]} compact/></div>;
  const shown=cards.filter(c=>c.studyTags&&matches(c.studyTags)&&`${c.searchText} ${c.title}`.toLocaleLowerCase("de").includes(query.toLocaleLowerCase("de")));
  return <div className="study-workspace object-sheet"><CheatSheetNav current="objects"/><header className="study-page-header"><div><p className="study-eyebrow">Lesson 5 · Objects, colours & materials</p><h1>One object. One colour trail.</h1><p>Learn the noun with its article. Follow the same gender through ein, kein and the pronoun.</p><StudyTagList tags={tagsForLesson(5)}/></div></header>
    <nav className="study-row" aria-label="Object sheet sections"><a href="#article-map">Article map</a><a href="#object-lab">Try it</a><a href="#materials">Colours & materials</a><a href="#object-words">Word cards</a><Link href="/lessons/05#practice">Quiz →</Link></nav>
    <section id="article-map"><h2>Remember three trails.</h2><p>These are <strong>nominative</strong> forms: use them after <span lang="de">Das ist …</span>.</p><div className="article-trails">{objectModels.slice(0,3).map(m=><article key={m.de} data-gender={m.gender}><small>{m.gender==="male"?"MASCULINE":m.gender==="neuter"?"NEUTER":"FEMININE"}</small><h3 lang="de">{m.de}</h3><div className="article-trail" lang="de"><b>{m.article}</b><span>→</span><b>{m.indefinite}</b><span>→</span><b>{m.negative}</b><span>→</span><b>{m.pronoun}</b></div><p>{m.gender==="female"?"The feminine trail keeps the e: eine → keine.":"Masculine and neuter share ein and kein here."}</p><SaveButton item={{id:`l5-trail-${m.gender}`,title:`${m.de}: ${m.indefinite} → ${m.negative} → ${m.pronoun}`,meaning:`${m.en}. Nominative after Das ist …`,kind:"concept",lesson:5,href:"/cheat-sheets/objects#article-map"}}/></article>)}</div><p className="object-memory">A new thing: <b>ein / eine</b> · Correct a guess: <b>kein / keine</b> · Talk about it again: <b>er / es / sie</b></p></section>
    <section id="object-lab" className="object-lab"><div><p className="study-eyebrow">Tap, change, say it</p><h2>Build a description.</h2><div className="object-pickers">{objectModels.map((m,i)=><button type="button" aria-pressed={index===i} key={m.de} data-gender={m.gender} onClick={()=>setIndex(i)}>{m.de}<small>{m.en}</small></button>)}</div><label className="object-toggle"><input type="checkbox" checked={negative} onChange={e=>setNegative(e.target.checked)}/> Correct a guess with kein / keine</label></div><div className="object-result" data-gender={item.gender} aria-live="polite"><small>{negative?"CORRECT THE GUESS":"INTRODUCE IT"}</small><h3>{say(sentences[negative?1:0]!)}</h3>{!negative&&<>{say(sentences[2]!)}{say(sentences[3]!)}</>}<p>{negative?`That is not a ${item.en}.`:`Introduce the ${item.en}, name its material, then use ${item.pronoun} for its colour.`}</p><SaveButton item={{id:`l5-description-${index}-${negative}`,title:sentences[negative?1:0]!,meaning:negative?`That is not a ${item.en}.`:`This is a ${item.en}.`,kind:"phrase",lesson:5,href:"/cheat-sheets/objects#object-lab",audio:speech[sentences[negative?1:0]!]??null}}/></div></section>
    <section id="materials"><h2>Colour stays simple. Material follows aus.</h2><p><span lang="de">Die Tasche ist rot.</span> The colour after <i>ist</i> has no extra ending. For material, usually leave out the article: <span lang="de">aus Holz</span>.</p><div className="colour-palette">{colourSwatches.map(([de,en,colour])=><article key={de}><span className="colour-swatch" style={{background:colour}} aria-hidden="true"/>{say(de)}<small>{en}</small></article>)}</div><p><b lang="de">hell-</b> = light: <span lang="de">hellbraun</span> · <b lang="de">dunkel-</b> = dark: <span lang="de">dunkelgrün</span>. These describe actual colours; the article colours show grammatical gender.</p><div className="material-grid">{materialModels.map(([de,en,sentence])=><article key={de}><h3 lang="de">aus {de}</h3><small>{en}</small>{say(sentence)}</article>)}</div></section>
    <section><h2>Keep the conversation going.</h2><div className="material-grid">{[["Wie heißt das auf Deutsch?","What is that called in German?"],["Wie schreibt man das?","How do you spell that?"],["Noch einmal, bitte.","Once again, please."],["Vielen Dank!","Thank you very much!"],["Bitte schön.","You are welcome."]].map(([de,en])=><article key={de}>{say(de!)}<p>{en}</p><SaveButton item={{id:`l5-help-${de}`,title:de!,meaning:en!,kind:"phrase",lesson:5,href:"/cheat-sheets/objects"}}/></article>)}</div></section>
    <details><summary>More Lesson 5 grammar and examples</summary><CoursePatterns units={[unit]} section="grammar" speech={speech}/></details>
    <section id="object-words"><h2>Your Lesson 5 word cards.</h2><label>Find an object, colour or expression<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Flasche, blue, material…"/></label><p>{shown.length} word families match your selection.</p><div className="card-grid">{shown.map(c=><WordFamilyPreview key={c.id} card={c} href={c.path} lessonIds={c.lessons.map(n=>`lesson:${n.padStart(2,"0")}`)}/>)}</div></section>
    <p className="muted">Based on Momente A1.1 KB 33–36, AB 30–33 and the Lesson 5 glossary. Descriptions, diagrams and quizzes are learning aids. Tap German words or select a phrase for meaning.</p>
  </div>;
}
