"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import type {WordCard} from "@/lib/content/word-card-types";
import {pluralFamilies,phoneSteps} from "@/lib/study/office-sheet";
import {CheatSheetNav} from "./CheatSheetNav";
import {LineAudio} from "./StudyAudio";
import {GermanText,SaveButton} from "./StudyProvider";
import {StudyScopeNotice} from "./StudyScope";
import {tagsForLesson} from "@/lib/study/scope";
import {SheetWordIndex} from "./SheetWordIndex";
import {OfficePhoneDetails} from "./OfficePhoneDetails";
import {OfficeBuilder} from "./ObjectBuilders";
import {OfficePrintSummary} from "./ObjectPrintSummaries";

export function OfficeCheatSheet({cards,speech,alphabet}:{cards:WordCard[];alphabet:WordCard[];speech:Record<string,string>}){
 const [step,setStep]=useState(0),[showEnglish,setShowEnglish]=useState(true),[phoneRecall,setPhoneRecall]=useState(false);
 useEffect(()=>{const restore=()=>{const match=window.location.hash.match(/^#phone-turn-(\d+)$/);if(match&&phoneSteps[Number(match[1])]){setStep(Number(match[1]));setPhoneRecall(false);requestAnimationFrame(()=>document.getElementById("phone-lab")?.scrollIntoView({block:"start"}));}};restore();window.addEventListener("hashchange",restore);return()=>window.removeEventListener("hashchange",restore);},[]);
 const call=phoneSteps[step]!;
 const say=(text:string)=><div className="study-row"><GermanText text={text}/><LineAudio compact text={text} src={speech[text]}/></div>;
 return <div className="study-workspace object-sheet office-sheet"><CheatSheetNav current="office"/><header className="study-page-header"><div><p className="study-eyebrow">Lesson 6 · Office, plurals & accusative</p><h1>The masculine article makes the move.</h1><p>Identify a thing. Then have it, need it or look for it. Watch the article change when the noun becomes the object.</p></div><button type="button" className="study-secondary" onClick={()=>window.print()}>Print cheat sheet</button></header><nav className="study-row" aria-label="Office sheet sections"><Link href="#case-map">Case map</Link><Link href="#office-lab">Build a sentence</Link><Link href="#plural-map">Plurals</Link><Link href="#phone-lab">Phone practice</Link><Link href="#office-words">Word cards</Link><Link href="#sheet-practice">Test yourself</Link></nav>
 <section id="case-map"><StudyScopeNotice tags={tagsForLesson(6)} subject="This case reference"/><h2>Three singular trails. One changes.</h2><p><b>Nominative:</b> who or what is it? <b>Accusative:</b> what do I have, need, see, find or look for?</p><div className="article-trails">{[{gender:"male",title:"der Kalender",from:"der · ein · kein",to:"den · einen · keinen",cue:"Masculine: add the n ending in the accusative.",q:"Wo ist der Kalender?",a:"Ich habe den Kalender."},{gender:"neuter",title:"das Tablet",from:"das · ein · kein",to:"das · ein · kein",cue:"Neuter: these article forms stay the same.",q:"Wo ist das Tablet?",a:"Ich habe das Tablet."},{gender:"female",title:"die Maus",from:"die · eine · keine",to:"die · eine · keine",cue:"Feminine: these article forms stay the same.",q:"Wo ist die Maus?",a:"Ich habe die Maus."}].map(m=><article key={m.gender} data-gender={m.gender}><small>{m.gender==="male"?"MASCULINE":m.gender==="neuter"?"NEUTER":"FEMININE"}</small><h3 lang="de">{m.title}</h3><div className="case-transition"><span><small>NOMINATIVE</small><b lang="de">{m.from}</b></span><strong aria-hidden="true">↓</strong><span><small>ACCUSATIVE</small><b lang="de">{m.to}</b></span></div><p>{m.cue}</p>{say(m.q)}{say(m.a)}<SaveButton item={{id:`l6-case-${m.gender}`,title:`${m.from} → ${m.to}`,meaning:m.cue,kind:"concept",lesson:6,href:"/cheat-sheets/office#case-map"}}/></article>)}</div><div className="object-memory"><b>Plural keeps die / keine.</b> There is no plural indefinite article: <span lang="de">Ich habe Stifte.</span> For none: <span lang="de">Ich habe keine Stifte.</span></div></section>
 <OfficeBuilder speech={speech}/>
 <section id="plural-map"><h2>Five plural families. Learn the pair.</h2><p>The ending cannot always be predicted. Store each noun as a pair: article + singular → die + plural.</p><div className="plural-families">{pluralFamilies.map(p=><article key={p.ending}><strong>{p.ending}</strong>{say(p.example)}<p>{p.cue}</p><SaveButton item={{id:`l6-plural-${p.ending}`,title:p.example,meaning:p.cue,kind:"concept",lesson:6,href:"/cheat-sheets/office#plural-map"}}/></article>)}</div></section>
 <section id="phone-lab" className="phone-lab"><div><p className="study-eyebrow">A complete call, one turn at a time</p><h2>Your turn on the phone.</h2><p>Choose a turn, hide the German and say that speaker’s line aloud. The names and company here are practice examples.</p><label className="object-toggle"><input type="checkbox" checked={showEnglish} onChange={e=>setShowEnglish(e.target.checked)}/> Show English</label><Link href="/listening?lesson=6">Listen to the original course calls →</Link></div><div className="phone-turn" aria-live="polite"><small>{step+1} / {phoneSteps.length} · {call.speaker}</small>{phoneRecall?<p>Say this line in German, then compare with the example.</p>:<h3>{say(call.de)}</h3>}<button type="button" className="study-secondary" aria-pressed={phoneRecall} onClick={()=>setPhoneRecall(!phoneRecall)}>{phoneRecall?"Reveal phone line":"Hide phone line & practise"}</button>{showEnglish&&<p>{call.en}</p>}<div className="study-row"><button type="button" className="study-secondary" disabled={step===0} onClick={()=>setStep(step-1)}>← Previous turn</button><button type="button" className="study-primary" onClick={()=>setStep(step===phoneSteps.length-1?0:step+1)}>{step===phoneSteps.length-1?"Start again":"Next turn →"}</button><SaveButton item={{id:`l6-phone-${step}`,title:call.de,meaning:call.en,kind:"phrase",lesson:6,href:`/cheat-sheets/office#phone-turn-${step}`,audio:speech[call.de]??null}}/></div></div></section>
 <OfficePhoneDetails alphabet={alphabet} speech={speech}/>
 <SheetWordIndex cards={cards} speech={speech} path="/cheat-sheets/office" id="office-words" title="Office words and useful expressions."/><p className="muted">Based on Momente A1.1 KB 37–46, partner activities p. 161, AB 34–45 and the Lesson 6 glossary. Diagrams, examples and practice combinations are learning aids.</p><OfficePrintSummary/></div>;
}
