"use client";
import {useEffect,useState} from 'react';
import Link from 'next/link';
import type {WordCard} from '@/lib/content/word-card-types';
import {studyUnits} from '@/lib/study/course-lessons';
import {pastActivities,pastPeople,pastModes,pastGroups,pastParts,pastSentence,pastMeaning,pastSaveId,openingHours,lastTimeChunks,type PastMode} from '@/lib/study/past-sheet';
import {GermanText,SaveButton} from './StudyProvider';
import {LineAudio} from './StudyAudio';
import {CheatSheetNav} from './CheatSheetNav';
import {StudyScopeNotice} from './StudyScope';
import {tagsForLesson} from '@/lib/study/scope';
import {pastBookmark,readPastBookmark} from '@/lib/study/past-learning';
import {PastDayTimeline,OpeningHoursSign} from './PastTools';
import {PastPrintSummary} from './PastPrintSummary';
import {SheetWordIndex} from './SheetWordIndex';
export function PastCheatSheet({cards,speech}:{cards:WordCard[];speech:Record<string,string>}){
 const [activity,setActivity]=useState(0),[person,setPerson]=useState(0),[mode,setMode]=useState<PastMode>('statement'),[english,setEnglish]=useState(true),[reveal,setReveal]=useState(true),[patternReveal,setPatternReveal]=useState(true),[hours,setHours]=useState(1),[pattern,setPattern]=useState(0);
 useEffect(()=>{const restore=()=>{const state=readPastBookmark(window.location.hash);if(state){setActivity(state.activity);setPerson(state.person);setMode(state.mode);setHours(state.hours);setPattern(state.pattern);setReveal(true);setPatternReveal(true);requestAnimationFrame(()=>document.getElementById(state.section==='patterns'?`past-pattern-${pastGroups[state.pattern]!.id}`:`past-${state.section}`)?.scrollIntoView({block:'start'}));}};restore();window.addEventListener('hashchange',restore);return()=>window.removeEventListener('hashchange',restore);},[]);
 const settings={activity,person,mode,hours,pattern};
 const sentence=pastSentence(activity,person,mode),meaning=pastMeaning(activity,person,mode),parts=pastParts(activity,person,mode);
 const verbs=studyUnits.find(u=>u.number===11)!.verbs.filter(v=>v.participle);
 const say=(text:string)=><span className="sheet-spoken"><GermanText text={text}/><LineAudio compact text={text} src={speech[text]}/></span>;
 return <div className="study-workspace past-sheet"><CheatSheetNav current="past"/><header className="study-page-header"><div><p className="study-eyebrow">Lesson 11 · Yesterday & opening hours</p><h1>Tell the story of yesterday.</h1><p>Haben changes with the person. The past participle finishes the action.</p></div><button type="button" className="study-secondary" onClick={()=>window.print()}>Print cheat sheet</button></header><nav className="sheet-jump" aria-label="Past sheet sections"><Link href="#past-lab">Build a past sentence</Link><Link href="#past-patterns">Four participle patterns</Link><Link href="#past-time">Last week or last year?</Link><Link href="#past-hours">Opening hours</Link><Link href="#past-words">Word cards</Link><Link href="#sheet-practice">Card practice</Link></nav>
 <section id="past-lab"><h2>One action. Two connected parts.</h2><StudyScopeNotice tags={tagsForLesson(11)} subject="This past-tense reference"/><PastDayTimeline activity={activity} onChoose={setActivity}/><p>{say('Was hast du gestern gemacht?')}</p><div className="sheet-controls"><label>Activity<select aria-label="Past activity" value={activity} onChange={e=>setActivity(Number(e.target.value))}>{pastActivities.map((a,i)=><option value={i} key={a.verb}>{a.verb}{a.detail?` · ${a.detail}`:''}</option>)}</select></label><label>Person<select aria-label="Past sentence person" value={person} onChange={e=>setPerson(Number(e.target.value))}>{pastPeople.map((p,i)=><option value={i} key={p.de}>{p.de}{p.de==='Sie'?' · formal you':''}</option>)}</select></label><label>Word order<select aria-label="Past sentence type" value={mode} onChange={e=>setMode(e.target.value as PastMode)}>{pastModes.map(m=><option value={m.id} key={m.id}>{m.label}</option>)}</select></label></div><div className="sheet-controls"><label><input type="checkbox" checked={english} onChange={e=>setEnglish(e.target.checked)}/> Show English</label><label><input type="checkbox" checked={reveal} onChange={e=>setReveal(e.target.checked)}/> Reveal final participle</label></div><div className="past-sentence" aria-live="polite"><p className="past-cue">{mode==='question'?'Haben first: ask a yes/no question.':'Haben stays in position 2, even when gestern comes first.'} The participle stays last.</p><div className="past-parts" aria-label="Past sentence word order">{parts.map((p,i)=><span data-role={p.role} key={i}><small>{p.role==='auxiliary'?'HABEN':p.role==='participle'?'PAST PARTICIPLE':p.role.toUpperCase()}</small><strong lang="de">{p.role==='participle'&&!reveal?'…':p.text}</strong></span>)}</div>{reveal?<p className="past-result">{say(sentence)}</p>:<button className="study-secondary" type="button" onClick={()=>setReveal(true)}>Reveal the complete sentence</button>}{english&&<p>{meaning}</p>}<SaveButton item={{id:pastSaveId(activity,person,mode),title:sentence,meaning,kind:'phrase',lesson:11,href:`/cheat-sheets/past${pastBookmark(settings)}`,audio:speech[sentence]??null}}/></div></section>
 <section id="past-patterns"><h2>Four patterns to remember.</h2><label><input type="checkbox" checked={patternReveal} onChange={e=>setPatternReveal(e.target.checked)}/> Show participles in the pattern cards</label><div className="past-pattern-grid">{pastGroups.map((g,index)=><article key={g.id} id={`past-pattern-${g.id}`} data-pattern={g.id} data-selected={pattern===index}><small>{g.cue}</small><h3>{g.label}</h3><p lang="de" className="past-formula">{g.example}</p><p>{g.note}</p><SaveButton item={{id:`l11-pattern-${g.id}`,title:pastActivities.find(a=>a.group===g.id)!.part,meaning:g.note,kind:"concept",lesson:11,href:`/cheat-sheets/past${pastBookmark({...settings,pattern:index},"patterns")}`,audio:speech[pastActivities.find(a=>a.group===g.id)!.part]??null}}/><details><summary>Explore the verbs in this pattern</summary><dl>{verbs.filter(v=>v.pastGroup===g.id).map(v=><div key={v.verb}><dt lang="de">{v.verb}</dt><dd>{patternReveal?say(v.participle!):<span aria-label="Hidden participle">…</span>}</dd></div>)}</dl></details></article>)}</div><p>These Lesson 11 participles use <b>haben</b>. This is not a rule for every German verb; Lesson 12 introduces <b>sein</b> with movement and other verbs.</p></section>
 <section id="past-time"><h2>Last: let the noun choose the ending.</h2><div className="past-last-grid">{lastTimeChunks.map(c=><article key={c.de} data-gender={c.tone}><small lang="de">{c.article}</small><strong>{say(c.de)}</strong><span>{c.en}</span></article>)}</div><p>No preposition: <span lang="de">letzten Samstag</span>, <span lang="de">letztes Wochenende</span>, <span lang="de">letzte Woche</span>. Keep the ending attached to its time noun.</p></section>
 <section id="past-hours"><h2>A time, an interval, or a starting point?</h2><div className="past-hour-options">{openingHours.map((h,i)=><button type="button" key={h.id} aria-pressed={hours===i} onClick={()=>setHours(i)}><strong lang="de">{h.label}</strong><span>{h.cue}</span></button>)}</div><OpeningHoursSign key={hours} state={settings} speech={speech}/><p>{say('Wann ist die Praxis geöffnet?')}</p><p>{say('Ab wann ist die Praxis wieder geöffnet?')}</p><p><b>Geöffnet</b> = open. <b>Geschlossen</b> = closed. <Link href="/book?page=coursebook-169">Practise with the book’s opening-hour signs →</Link></p></section>
 <SheetWordIndex cards={cards} speech={speech} path="/cheat-sheets/past" id="past-words" title="Your Lesson 11 words."/><Link href="/lessons/11#practice">Practise the whole lesson →</Link><p className="muted">Based on Momente A1.1 KB 69–72, partner pages 168/169/196/197, AB 70–73 and 92, and glossary pages 15–16. Diagrams, sentence combinations and explanations are authored learning aids.</p><PastPrintSummary/></div>;
}
