"use client";

import Link from "next/link";
import {useEffect,useState} from "react";
import {questionBuilders,questionQuiz,questionReplyCases,questionWords} from "@/lib/study/questions";
import {CheatSheetNav} from "./CheatSheetNav";
import {OverviewPanel} from "./OverviewPanel";
import {GermanText,SaveButton} from "./StudyProvider";
import {LineAudio} from "./StudyAudio";

export function QuestionCheatSheet({speech}:{speech:Record<string,string>}){
  const [selected,setSelected]=useState("woher"),[extras,setExtras]=useState(false),[reveal,setReveal]=useState(true);
  const [builder,setBuilder]=useState("home"),[formal,setFormal]=useState(false),[yesNo,setYesNo]=useState(false);
  const [negative,setNegative]=useState(false),[trueReply,setTrueReply]=useState(true);
  const [position,setPosition]=useState(0),[answer,setAnswer]=useState<string|null>(null),[score,setScore]=useState(0);
  useEffect(()=>{
    const restore=()=>{
      const id=window.location.hash.replace(/^#question-/,"");
      if(!questionWords.some(w=>w.id===id))return;
      setSelected(id);setReveal(true);
      requestAnimationFrame(()=>document.getElementById("question-word")?.scrollIntoView({block:"start"}));
    };
    restore();window.addEventListener("hashchange",restore);
    return()=>window.removeEventListener("hashchange",restore);
  },[]);
  const word=questionWords.find(w=>w.id===selected)!;
  const model=questionBuilders.find(b=>b.id===builder)!;
  const parts=yesNo?(formal?model.yesFormal:model.yes):(formal?model.formal:model.w);
  const question=parts.join(" ");
  const reply=questionReplyCases[negative?1:0]!;
  const response=trueReply?reply.yes:reply.no;
  const quiz=questionQuiz[position];
  const say=(text:string)=><span className="sheet-spoken"><GermanText text={text}/><LineAudio compact text={text} src={speech[text]}/></span>;
  const save=(id:string,title:string,meaning:string,lesson?:number)=><SaveButton item={{id:`question-${id}`,title,meaning,kind:"concept",href:`/cheat-sheets/questions#${id.startsWith("builder-")?"question-builder":id.startsWith("reply-")?"question-replies":id.startsWith("quiz-")?"question-practice":`question-${id}`}`,audio:speech[title]??null,...(lesson?{lesson}:{})}}/>;
  return <div className="collection-sheet questions-sheet">
    <CheatSheetNav current="questions"/>
    <header className="collection-heading"><div><p className="study-eyebrow">Cheat sheet 07 · Questions & answers</p><h1>Ask for the missing piece.</h1><p>A person, a place, a price? Choose the question word. Then put the verb in its place.</p></div><button type="button" className="study-secondary" onClick={()=>window.print()}>Print cheat sheet</button></header>
    <nav className="sheet-jump" aria-label="Sheet sections"><a href="#question-map">Question map</a><a href="#question-builder">Word order</a><a href="#question-replies">Ja · nein · doch</a><a href="#question-practice">Test yourself</a></nav>
    <div id="question-map"><OverviewPanel title="One map for the missing information"><p>The symbol tells you what belongs in the answer. Tap a tile to see a complete question and response.</p><div className="question-map">{questionWords.filter(w=>w.lesson!==null).map(w=><button type="button" key={w.id} data-family={w.family} aria-pressed={selected===w.id} onClick={()=>{setSelected(w.id);setReveal(true);}}><span className="question-symbol" aria-hidden="true">{w.icon}</span><strong lang="de">{w.word}</strong><span>{w.meaning}</span><small>{w.sourceLabel??`Lesson ${w.lesson}`}</small></button>)}</div></OverviewPanel></div>
    <section className="question-focus" id="question-word" data-family={word.family}>
      <div className="study-section-heading"><div><p className="study-eyebrow">{word.lesson?`Course pattern · ${word.sourceLabel??`Lesson ${word.lesson}`}`:"Study extra · a preview of the wider question family"}</p><h2>{say(word.word)} <small>{word.meaning}</small></h2></div>{save(word.id,word.question,`${word.translation} — ${word.cue}`,word.lesson??undefined)}</div>
      <p className="question-memory">{word.cue}</p><div className="question-example"><div><small>Ask</small><p>{say(word.question)}</p><p>{word.translation}</p></div><div><small>Answer</small>{reveal?<><p>{say(word.answer)}</p><p>{word.answerMeaning}</p></>:<p>Say a possible answer aloud, then reveal the example.</p>}<button type="button" className="study-secondary" onClick={()=>setReveal(!reveal)}>{reveal?"Hide example answer":"Reveal example answer"}</button></div></div>
    </section>
    <section className="question-location"><h2>Three places. Three different arrows.</h2><div>{[{id:"woher",symbol:"FROM →",de:"Woher?",hint:"Origin",reply:"aus dem Iran"},{id:"wo",symbol:"● HERE",de:"Wo?",hint:"Location",reply:"in Berlin"},{id:"wohin",symbol:"→ TO",de:"Wohin?",hint:"Destination · study extra",reply:"nach Hause"}].map(item=><button type="button" key={item.id} onClick={()=>{setSelected(item.id);setReveal(true);document.getElementById("question-word")?.scrollIntoView({block:"start",behavior:"smooth"});}}><small>{item.symbol}</small><strong lang="de">{item.de}</strong><span>{item.hint}</span><b lang="de">{item.reply}</b></button>)}</div><p>These are useful example pairs, not universal preposition rules. Destinations can also use <span lang="de">in</span> or <span lang="de">zu</span>, depending on the place. <Link href="/cheat-sheets">Open country articles and aus →</Link></p></section>
    <section id="question-builder" className="sheet-workshop"><p className="study-eyebrow">One verb. Two positions.</p><h2>Move the verb. Change the question.</h2><div className="question-legend"><span className="question-token">Question phrase</span><span className="verb-token">Conjugated verb</span><span>Person / remaining information</span></div><div className="sheet-controls"><label>Practice topic<select aria-label="Practice topic" value={builder} onChange={e=>setBuilder(e.target.value)}>{questionBuilders.map(b=><option key={b.id} value={b.id}>{b.title}</option>)}</select></label><button type="button" className="study-secondary" aria-pressed={formal} onClick={()=>setFormal(!formal)}>{formal?"Formal · Sie":"Informal · du"}</button><button type="button" className="study-secondary" aria-pressed={yesNo} onClick={()=>setYesNo(!yesNo)}>{yesNo?"Yes/no question":"W-question"}</button></div>
      <div className="question-builder-result" aria-live="polite"><p>{yesNo?"VERB FIRST → yes or no":"QUESTION PHRASE FIRST → new information"}</p><div className="question-rail">{parts.map((part,i)=><div key={`${i}-${part}`} className={i===(yesNo?0:1)?"verb-token":!yesNo&&i===0?"question-token":""}><small>Position {i+1}</small><GermanText text={part}/></div>)}</div><p>{say(question)}</p><p>{yesNo?model.yesMeaning:model.meaning}</p>{save(`builder-${builder}-${formal}-${yesNo}`,question,yesNo?"Yes/no question: conjugated verb first.":"W-question: question phrase first, conjugated verb second.",model.lesson)}</div>
      <div className="sheet-rule-grid"><article><h3>Count blocks, not words.</h3><p><b lang="de">Wie viel</b> is one question phrase. So is <b lang="de">Welche Sprachen</b>. The conjugated verb follows the whole block.</p><p>{say("Welche Sprache sprichst du?")}</p><p>Which language do you speak?</p></article><article><h3>Sometimes wer is the subject.</h3><p>{say("Wer kommt aus dem Iran?")}</p><p>Who comes from Iran? <b lang="de">Wer</b> already asks for the person doing the action. Do not add an extra <span lang="de">du</span>.</p></article><article><h3>German doesn’t insert do.</h3><p>“Do you live …?” becomes <b lang="de">Wohnst du …?</b> Use the conjugated German verb itself. Formal <b lang="de">Sie</b> stays capitalized.</p></article></div>
    </section>
    <section id="question-replies" className="sheet-workshop"><p className="study-eyebrow">A tiny word with a big job</p><h2>DOCH pushes back against NOT.</h2><p>Start with the fact: are you from Iran? Then choose the response that says that fact clearly.</p><div className="sheet-controls"><button className="study-secondary" type="button" aria-pressed={negative} onClick={()=>setNegative(!negative)}>{negative?"Negative question · nicht":"Ordinary question"}</button><button className="study-secondary" type="button" aria-pressed={trueReply} onClick={()=>setTrueReply(!trueReply)}>{trueReply?"Fact: I am from Iran":"Fact: I am not from Iran"}</button></div><div className="question-reply" aria-live="polite"><small>Question</small><p>{say(reply.question)}</p><p>{reply.translation}</p><small>Your response</small><p className={negative&&trueReply?"reply-doch":""}>{say(response)}</p><p>{trueReply?reply.yesMeaning:reply.noMeaning}</p><p>{reply.cue}</p>{save(`reply-${negative}-${trueReply}`,response,reply.cue,3)}</div></section>
    <section className="sheet-workshop"><h2>Keep these pairs apart.</h2><div className="sheet-rule-grid"><article><h3 lang="de">Wer ≠ wo</h3><p><b>Who?</b> = <b lang="de">Wer?</b> A person.<br/><b>Where?</b> = <b lang="de">Wo?</b> A place.</p></article><article><h3 lang="de">Wie viel ≠ wie viele</h3><p>An amount or price: <b lang="de">Wie viel?</b><br/>A countable plural: <b lang="de">Wie viele Kinder?</b></p></article><article><h3 lang="de">welcher · welche · welches</h3><p>“Which” changes with the noun and case. These are nominative forms:</p><p>{say("Welcher Tisch ist schön?")}</p><p>Which table is beautiful?</p><p>{say("Welches Buch ist das?")}</p><p>Which book is that?</p><p><b lang="de">welche Sprache / welche Sprachen</b> — which language / languages.</p></article></div></section>
    <section className="sheet-workshop question-extras"><button type="button" className="study-secondary" aria-expanded={extras} onClick={()=>setExtras(!extras)}>{extras?"Hide":"Explore"} the wider question family</button><p>Study extras: useful previews, not claimed as Lesson 1–4 core vocabulary. <span lang="de">wen / wem / wessen</span> introduce case patterns you can revisit later.</p>{extras&&<div className="question-map">{questionWords.filter(w=>w.lesson===null).map(w=><button type="button" key={w.id} data-family={w.family} onClick={()=>{setSelected(w.id);setReveal(true);document.getElementById("question-word")?.scrollIntoView({block:"start",behavior:"smooth"});}}><span className="question-symbol" aria-hidden="true">{w.icon}</span><strong lang="de">{w.word}</strong><span>{w.meaning}</span><small>Study extra</small></button>)}</div>}</section>
    <section id="question-practice" className="sheet-practice"><div><p className="study-eyebrow">Recall the pattern</p><h2>Eight quick questions.</h2><p>Read the explanation after every answer. Save the patterns you want to practise again.</p></div><div className="sheet-quiz">{quiz?<><small>Question {position+1} / {questionQuiz.length}</small><h3>{quiz.q}</h3><div className="sheet-quiz-options">{quiz.options.map(option=><button type="button" key={option} disabled={answer!==null} aria-pressed={answer===option} data-answer={answer===null?undefined:option===quiz.answer?"correct":option===answer?"wrong":undefined} onClick={()=>{setAnswer(option);if(option===quiz.answer)setScore(score+1);}}>{option}</button>)}</div>{answer!==null&&<div role="status"><h4>{answer===quiz.answer?"Exactly.":"Remember this:"}</h4><p>{quiz.why}</p>{save(`quiz-${position}`,`${quiz.q} → ${quiz.answer}`,quiz.why)}<button className="study-primary" type="button" onClick={()=>{setPosition(position+1);setAnswer(null);}}>Next question →</button></div>}</>:<div role="status"><h3>{score} / {questionQuiz.length}</h3><p>Revisit the word-order builder or save a question for your next review.</p><button type="button" className="study-primary" onClick={()=>{setPosition(0);setAnswer(null);setScore(0);}}>Practise again</button></div>}</div></section>
    <details className="sheet-sources"><summary>Coverage & sources</summary><p>Core patterns connect Momente A1.1 Lessons 1–4: introductions and W-questions; personal details and quantities; family, languages and ja/nein/doch; furniture and prices. Reference: coursebook pp. 11–32 the German–English glossary, Lessons 1–4, and workbook Module 1 review, p. 18. © Hueber Verlag.</p><p>This sheet’s explanations, diagrams, example personal details and quizzes are learning aids. The wider question family is explicitly marked as additional study material. Audio is synthesized German speech. Tap a German word or select a sentence for its meaning.</p><Link href="/references">Course sources & credits →</Link></details>
  </div>;
}
