"use client";
import {useState} from "react";
import type {WordCard} from "@/lib/content/word-card-types";
import {conversationFrames,germanNumber,germanPrice,grammarPatterns,spellingLetters,spokenVerb,verbModels,verbPersons,type ExtendedSheetId} from "@/lib/study/sheet-topics";
import {GermanText,SaveButton} from "./StudyProvider";
import {LineAudio} from "./StudyAudio";
import {OverviewPanel} from "./OverviewPanel";

export function SheetWorkshops({sheet,cards,speech}:{sheet:ExtendedSheetId;cards:WordCard[];speech:Record<string,string>}){
  const [person,setPerson]=useState(0),[verb,setVerb]=useState("wohnen");
  const [number,setNumber]=useState("21"),[price,setPrice]=useState("24,50"),[phone,setPhone]=useState("0176");
  const [formal,setFormal]=useState(false),[topic,setTopic]=useState("name"),[relative,setRelative]=useState("die Mutter");
  const audio=(text:string)=><LineAudio text={text} src={speech[text]} compact/>;
  const say=(text:string)=><span className="sheet-spoken"><GermanText text={text}/>{audio(text)}</span>;
  if(sheet==="people"){
    const groups=[{label:"Grandparents",de:"die Großeltern",words:["der Großvater","die Großmutter"]},{label:"Parents & their siblings",de:"die Eltern",words:["der Vater","die Mutter","der Onkel","die Tante"]},{label:"Children & siblings",de:"die Geschwister",words:["der Sohn","die Tochter","der Bruder","die Schwester"]},{label:"Grandchildren",de:"die Enkelkinder",words:["der Enkel","die Enkelin","das Enkelkind"]}];
    const found=cards.flatMap(c=>c.rows).find(r=>r.singular.text===relative);
    return <><OverviewPanel title="A family, four generations"><div className="family-tree">{groups.map((g,i)=><div className="family-generation" key={g.de}><header><span className="sheet-step">{i+1}</span><div><small>{g.label}</small><strong className="study-tone-plural" lang="de">{g.de}</strong></div></header><div>{g.words.map(w=><button type="button" key={w} className={`study-tone-${w.startsWith("der ")?"male":w.startsWith("das ")?"neuter":"female"}`} aria-pressed={relative===w} onClick={()=>setRelative(w)}>{w}</button>)}</div></div>)}</div><p className="sheet-note">A vocabulary map of generations. Family members do not need to live together. <b>Blue der · Pink die · Green das · Purple plural.</b></p></OverviewPanel>
      <div className={`sheet-focus study-tone-${found?.singular.tone??"plain"}`}><small>Selected family word</small><h2>{say(relative)}</h2><p>{found?.meaning??"grandson"}</p>{found?.plurals.map(f=><p key={f.text} className="study-tone-plural">Plural: {say(f.text)}</p>)}<p>Say the article with the word. Then say its plural.</p></div>
      <section className="sheet-workshop"><h2>Work roles: a pattern worth keeping.</h2><div className="sheet-formula"><div className="study-tone-male"><small>Masculine</small>{say("der Lehrer")}</div><span aria-hidden="true">→</span><div className="study-tone-female"><small>Feminine · add -in</small>{say("die Lehrerin")}</div><span aria-hidden="true">→</span><div className="study-tone-plural"><small>Feminine plural · -innen</small>{say("die Lehrerinnen")}</div></div><p className="sheet-note">Learn the masculine plural separately. Some pairs change more: <b lang="de">Arzt → Ärztin</b>, <b lang="de">Koch → Köchin</b>. These are grammatical word forms; a person’s preferred description matters.</p><div className="sheet-rule-grid"><article><h3>Belonging: mein / meine</h3><p className="study-tone-male">{say("mein Vater")}</p><p className="study-tone-neuter">{say("mein Kind")}</p><p className="study-tone-female">{say("meine Mutter")}</p><p className="study-tone-plural">{say("meine Eltern")}</p><p>In these subject forms, feminine and plural add -e. dein / deine follows the same pattern.</p></article><article><h3>Say what you do</h3><p>{say("Ich bin Ärztin.")}</p><p>I am a doctor.</p><p>{say("Ich arbeite als Lehrer.")}</p><p>I work as a teacher.</p><p>No article in these ordinary statements of profession.</p></article><article><h3>Describe your family</h3>{["ledig","verheiratet","geschieden","allein","zusammen"].map((s,i)=><p key={s}>{say(s)} <small>— {["single","married","divorced","alone","together"][i]}</small></p>)}</article></div></section></>;
  }
  if(sheet==="verbs"){
    const model=verbModels.find(v=>v.verb===verb)!;
    return <><section className="sheet-workshop"><p className="study-eyebrow">One person changes the whole form</p><h2>Turn the conjugation dial.</h2><div className="sheet-controls"><label>Choose a verb<select value={verb} onChange={e=>setVerb(e.target.value)}>{verbModels.map(v=><option key={v.verb} value={v.verb}>{v.verb} · {v.meaning}</option>)}</select></label><label>Choose a person<select value={person} onChange={e=>setPerson(Number(e.target.value))}>{verbPersons.map((p,i)=><option value={i} key={p}>{p}</option>)}</select></label></div><div className="verb-stage" aria-live="polite"><small>{model.meaning}</small><p><span>{verbPersons[person]}</span> <strong>{model.forms[person]}</strong>{audio(spokenVerb(person,model.forms[person]!))}</p><p>{model.tip}</p><SaveButton item={{id:`conjugation-${verb}-${person}`,title:spokenVerb(person,model.forms[person]!),meaning:`${model.meaning} · ${verbPersons[person]}`,kind:"concept",href:"/cheat-sheets/verbs#sheet-workshop",audio:speech[spokenVerb(person,model.forms[person]!)]??null}}/></div><div className="verb-person-grid">{verbPersons.map((p,i)=><button type="button" aria-pressed={person===i} key={p} onClick={()=>setPerson(i)}><small>{p}</small><strong lang="de">{model.forms[i]}</strong></button>)}</div></section>
      <OverviewPanel title="21 verbs, one selected person"><p>Currently showing <b lang="de">{verbPersons[person]}</b>. Select a verb to load its full pattern above.</p><div className="verb-atlas">{verbModels.map(v=><button type="button" key={v.verb} aria-pressed={verb===v.verb} onClick={()=>setVerb(v.verb)}><small lang="de">{v.verb}</small><strong lang="de">{v.forms[person]}</strong><span>{v.meaning}</span></button>)}</div></OverviewPanel>
      <section className="sheet-workshop"><h2>Build the sentence in three moves.</h2><p>The violet block is the conjugated verb. Watch where it goes.</p><div className="sentence-patterns">{grammarPatterns.map(p=><article key={p.id} id={`pattern-${p.id}`}><h3>{p.title}</h3><div className="sentence-rail">{p.parts.map((part,i)=><span key={i} className={(p.id==="yes-no"?i===0:i===1)?"is-verb":""} lang="de">{part}</span>)}</div><p>{audio(p.de)} {p.en}</p><p>{p.cue}</p><SaveButton compact item={{id:`sheet-pattern-${p.id}`,title:p.de,meaning:p.cue,kind:"concept",href:`/cheat-sheets/verbs#pattern-${p.id}`,audio:speech[p.de]??null}}/></article>)}</div></section></>;
  }
  if(sheet==="numbers"){
    const valid=/^\d{1,7}$/.test(number)&&Number(number)<=1000000;
    const value=valid?Number(number):0,word=valid?germanNumber(value):null;
    const priceText=germanPrice(price),digits=phone.replace(/[\s()+-]/g,"");
    const phoneText=/^\d{1,20}$/.test(digits)?[...digits].map(n=>germanNumber(Number(n))).join(", "):null;
    return <><section className="sheet-workshop"><p className="study-eyebrow">Read left. Say the units first.</p><h2>The German number builder.</h2><label className="sheet-number-input">Type a whole number from 0 to 1,000,000<input inputMode="numeric" value={number} onChange={e=>setNumber(e.target.value)} maxLength={7}/></label><div className="number-stage" aria-live="polite">{word?<><strong>{value.toLocaleString("de-DE")}</strong><p lang="de">{say(word)}</p>{value>20&&value<100&&value%10!==0?<div className="number-parts"><span><small>1 · units</small>{value%10===1?"ein":germanNumber(value%10)}</span><b>und</b><span><small>2 · tens</small>{germanNumber(Math.floor(value/10)*10)}</span></div>:<p>{value===1000000?"Million is a noun: capital M, feminine eine.":value>=100?"Hundreds and thousands come first. Inside the last two digits, units still come before tens.":"Learn this foundation word as a whole."}</p>}</>:<p role="alert">Enter a whole number from 0 to 1,000,000.</p>}</div><div className="study-chips">{[16,17,21,30,60,70,99,452,1000,1000000].map(n=><button type="button" key={n} onClick={()=>setNumber(String(n))}>{n.toLocaleString("de-DE")}</button>)}</div></section>
      <OverviewPanel title="The number ladder"><div className="number-ladder">{[{title:"Start here · 0–12",values:[0,1,2,3,4,5,6,7,8,9,10,11,12]},{title:"The teens · 13–19",values:[13,14,15,16,17,18,19]},{title:"The tens · 20–90",values:[20,30,40,50,60,70,80,90]},{title:"Go bigger",values:[100,200,1000,10000,100000,1000000]}].map(g=><div key={g.title}><h3>{g.title}</h3>{g.values.map(n=><button type="button" key={n} onClick={()=>setNumber(String(n))}><b>{n.toLocaleString("de-DE")}</b><span lang="de">{germanNumber(n)}</span></button>)}</div>)}</div><p className="sheet-note"><b>Watch the shortcuts:</b> sechzehn, siebzehn, sechzig, siebzig. <b>Watch the spelling:</b> dreißig. <b>Watch the one:</b> eins alone → einundzwanzig → ein Euro → eine Million.</p></OverviewPanel>
      <section className="sheet-rule-grid"><article><h2>Read the price.</h2><label>Price in euros<input inputMode="decimal" value={price} onChange={e=>setPrice(e.target.value)} maxLength={7}/></label><p className="sheet-price" aria-live="polite">{priceText?say(priceText):"Use a price such as 24,50 (up to 9999,99)."}</p><p>German writes a decimal comma: <b>24,50 €</b>. In conversation, <span lang="de">vierundzwanzig fünfzig</span> is also common when the currency is clear.</p>{say("Was kostet das?")}<p>How much does that cost?</p></article><article><h2>Phone numbers: one digit at a time.</h2><label>Practice digits<input inputMode="tel" value={phone} onChange={e=>setPhone(e.target.value)} maxLength={25}/></label><p aria-live="polite">{phoneText?say(phoneText):"Enter up to 20 digits. Spaces, +, (), and hyphens are separators."}</p><p>Keep the zero at the start. This tool reads the digits only; it does not place a call or save your number.</p></article></section></>;
  }
  const frame=conversationFrames.find(f=>f.id===topic)!;
  const q=formal?frame.formal:frame.casual,a=formal&&frame.formalAnswer?frame.formalAnswer:frame.answer;
  return <><section className="sheet-workshop"><div className="study-section-heading"><div><p className="study-eyebrow">Practice examples · change the details to your own</p><h2>A conversation in your pocket.</h2></div><div className="study-chips" role="group" aria-label="Conversation register"><button type="button" aria-pressed={!formal} onClick={()=>setFormal(false)}>Friendly · du</button><button type="button" aria-pressed={formal} onClick={()=>setFormal(true)}>Formal · Sie</button></div></div><div className="conversation-topics">{conversationFrames.map(f=><button type="button" key={f.id} aria-pressed={topic===f.id} onClick={()=>setTopic(f.id)}>{f.label}</button>)}</div><div className="conversation-bubbles" aria-live="polite"><article><small>ASK · {formal?"Sie":"du"}</small><h3>{say(q)}</h3><p>{frame.en}</p></article><article><small>ANSWER</small><h3>{say(a)}</h3><p>{frame.answerEn}</p><SaveButton compact item={{id:`sheet-conversation-${topic}-${formal?"formal":"casual"}`,title:`${q} ${a}`,meaning:`${frame.en} ${frame.answerEn}`,kind:"phrase",href:"/cheat-sheets/conversation#sheet-workshop",audio:speech[a]??null}}/></article></div><p className="sheet-note">{frame.cue}</p></section>
    <OverviewPanel title="Everyday questions, at a glance"><div className="conversation-atlas">{conversationFrames.map(f=><article key={f.id}><small>{f.label}</small><h3 lang="de">{formal?f.formal:f.casual}</h3><p lang="de">{formal&&f.formalAnswer?f.formalAnswer:f.answer}</p><p>{f.en}</p></article>)}</div></OverviewPanel>
    <section className="sheet-workshop"><h2>When you need a little help.</h2><div className="sheet-rule-grid">{[{de:"Wie bitte?",en:"Pardon? / Could you repeat that?"},{de:"Wie schreibt man das?",en:"How do you spell that?"},{de:"Noch einmal, bitte.",en:"Once more, please."},{de:"Ich verstehe das nicht.",en:"I do not understand that."},{de:"Was bedeutet das?",en:"What does that mean?"},{de:"Langsam, bitte.",en:"Slowly, please."}].map(p=><article key={p.de}><h3>{say(p.de)}</h3><p>{p.en}</p></article>)}</div><h2>Spell it out.</h2><p>Tap the speaker to hear a letter. German W sounds like “veh”; V like “fow”; J like “yot”. The spelling cards below include the original course audio.</p><div className="spelling-grid">{spellingLetters.map(l=><div key={l.de}><strong lang="de">{l.de}</strong>{audio(l.de)}<small>{l.en}</small></div>)}</div></section></>;
}
