"use client";
import {useState} from 'react';
import Link from 'next/link';
import type {WordCard} from '@/lib/content/word-card-types';
import {clockSaveId,clockHours,clockMinutes,clockWords,clockSentence,clockMeaning,digitalTime,weekDays,weekDaysEnglish,dayParts,timePlaces,planParts,planSentence,planMeaning,type ClockMode} from '@/lib/study/time-sheet';
import {CheatSheetNav} from './CheatSheetNav';
import {GermanText,SaveButton} from './StudyProvider';
import {LineAudio} from './StudyAudio';
import {useStudyScope} from './StudyScope';
import {WordFamilyPreview} from '../word-cards/WordFamilyPreview';

export function TimeCheatSheet({cards,speech}:{cards:WordCard[];speech:Record<string,string>}){
 const [hour,setHour]=useState(15),[minute,setMinute]=useState(30),[mode,setMode]=useState<ClockMode>('everyday'),[day,setDay]=useState(0),[place,setPlace]=useState(0),[front,setFront]=useState(true),[reveal,setReveal]=useState(true);
 const {matches}=useStudyScope();
 const sentence=clockSentence(hour,minute,mode),meaning=clockMeaning(hour,minute,mode),plan=planSentence(day,place,front),parts=planParts(day,place,front);
 const say=(text:string)=><span className="sheet-spoken"><GermanText text={text}/><LineAudio compact text={text} src={speech[text]}/></span>;
 const shown=cards.filter(c=>c.studyTags&&matches(c.studyTags));
 return <div className="study-workspace time-sheet"><CheatSheetNav current="time"/><header className="study-page-header"><div><p className="study-eyebrow">Lesson 8 · Time, weekdays & making plans</p><h1>Halfway to the next hour.</h1><p>Read the clock. Choose the day. Make a plan that sounds right.</p></div></header>
 <nav className="sheet-jump" aria-label="Time sheet sections"><a href="#time-map">am · um · in der</a><a href="#clock-lab">Interactive clock</a><a href="#week-map">Week & day</a><a href="#plan-lab">Make a plan</a><a href="#time-words">Word cards</a></nav>
 <section id="time-map"><h2>Three time signals to remember.</h2><div className="time-prepositions">{[{key:'am',title:'DAY / PART OF DAY',de:'am Wochenende',en:'at the weekend',cue:'am Montag · am Morgen · am Abend'},{key:'um',title:'CLOCK TIME',de:'um vier',en:'at four',cue:'um ein Uhr · um halb vier'},{key:'in der',title:'THE NIGHT EXCEPTION',de:'in der Nacht',en:'at night',cue:'Remember die Nacht → in der Nacht.'}].map((p,i)=><article key={p.key} data-time-kind={i}><small>{p.title}</small><h3>{p.key}</h3><p>{say(p.de)}</p><p>{p.en}</p><p>{p.cue}</p></article>)}</div><p><b>No preposition before heute:</b> {say('heute Abend')} · this evening.</p></section>
 <section id="clock-lab"><h2>Move the clock. Hear the time.</h2><div className="clock-layout"><div><svg viewBox="0 0 300 300" role="img" aria-label={`Clock showing ${digitalTime(hour,minute)}`} className="learning-clock"><circle cx="150" cy="150" r="140" fill="#fffdf8" stroke="#465a57" strokeWidth="3"/>{Array.from({length:60},(_,i)=><line key={i} x1="150" y1={i%5?18:15} x2="150" y2={i%5?23:29} stroke="#596c68" strokeWidth={i%5?1:3} transform={`rotate(${i*6} 150 150)`}/>)}{Array.from({length:12},(_,i)=>{const n=i+1,a=n*Math.PI/6;return <text key={n} x={150+108*Math.sin(a)} y={155-108*Math.cos(a)} textAnchor="middle" fontSize="20" fill="#263d3a">{n}</text>;})}<line x1="150" y1="150" x2="150" y2="75" stroke="#765194" strokeWidth="9" strokeLinecap="round" transform={`rotate(${(hour%12)*30+minute/2} 150 150)`}/><line x1="150" y1="150" x2="150" y2="42" stroke="#246b73" strokeWidth="5" strokeLinecap="round" transform={`rotate(${minute*6} 150 150)`}/><circle cx="150" cy="150" r="7" fill="#263d3a"/></svg><p className="clock-digital">{digitalTime(hour,minute)}</p><div className="sheet-controls"><label>Hour<select aria-label="Clock hour" value={hour} onChange={e=>setHour(Number(e.target.value))}>{clockHours.map(h=><option key={h} value={h}>{String(h).padStart(2,'0')}</option>)}</select></label><label>Minute<select aria-label="Clock minute" value={minute} onChange={e=>setMinute(Number(e.target.value))}>{clockMinutes.map(m=><option key={m} value={m}>{String(m).padStart(2,'0')}</option>)}</select></label></div></div>
 <div className="clock-answer"><div className="time-mode" aria-label="Clock style">{(['everyday','official'] as const).map(m=><button type="button" key={m} aria-pressed={mode===m} onClick={()=>setMode(m)}>{m==='everyday'?'Everyday · 12-hour':'Official · 24-hour'}</button>)}</div><label className="time-recall"><input type="checkbox" checked={reveal} onChange={e=>setReveal(e.target.checked)}/> Show the answer</label>{reveal?<div aria-live="polite"><h3 lang="de">{clockWords(hour,minute,mode)}</h3><p>{say(sentence)}</p><p>{meaning}</p><SaveButton item={{id:clockSaveId(hour,minute,mode),title:sentence,meaning,kind:'phrase',lesson:8,href:'/cheat-sheets/time#clock-lab',audio:speech[sentence]??null}}/></div>:<p className="clock-hidden">Say the time first, then reveal it.</p>}<aside className="half-memory"><strong lang="de">halb vier → 3:30</strong><p>Halfway <b>to four</b>. Point to the next hour.</p><div><span>3:00</span><b>3:30 →</b><span>4:00</span></div></aside><p>With <span lang="de">Uhr</span>: <b lang="de">ein Uhr</b>. Without it: <b lang="de">Viertel nach eins</b>.</p><p className="muted">Everyday time needs morning/evening context. These are the variants taught in your book; regional wording can differ.</p></div></div></section>
 <section id="week-map"><h2>Seven days. One article: der.</h2><div className="week-map">{weekDays.map((d,i)=><button type="button" key={d} aria-pressed={day===i} onClick={()=>setDay(i)}><small>der</small><strong lang="de">{d}</strong><span>{weekDaysEnglish[i]}</span><b lang="de">am {d}</b></button>)}</div><p><b lang="de">das Wochenende</b> = Saturday + Sunday → {say('am Wochenende')}</p><div className="day-map">{dayParts.map((p,i)=><article key={p.de} data-night={i===5}><small>{i+1}</small><p>{say(p.de)}</p><span>{p.en}</span></article>)}</div></section>
 <section id="plan-lab"><h2>Time first. Verb still second.</h2><p>The selected weekday carries into your plan. Tap a destination; switch the order and watch the verb stay in block 2.</p><div className="time-places">{timePlaces.map((p,i)=><button type="button" key={p.de} data-gender={p.tone} aria-pressed={place===i} onClick={()=>setPlace(i)}><b lang="de">{p.de}</b><span lang="de">{p.to}</span></button>)}</div><label className="time-recall"><input type="checkbox" checked={front} onChange={e=>setFront(e.target.checked)}/> Put the time first</label><div className="time-word-order" aria-live="polite">{parts.map((p,i)=><div key={i} data-verb={i===1}><small>{i===1?'VERB · POSITION 2':`BLOCK ${i+1}`}</small><strong lang="de">{p}</strong></div>)}</div><div className="plan-answer"><p>{say(plan)}</p><p>{planMeaning(day,place)}</p><SaveButton item={{id:`l8-plan-${day}-${place}-${front}`,title:plan,meaning:planMeaning(day,place),kind:'phrase',lesson:8,href:'/cheat-sheets/time#plan-lab',audio:speech[plan]??null}}/></div><p><b>Destination articles:</b> <span lang="de">in das → ins</span> · <span lang="de">in eine</span> · <span lang="de">in einen</span>.</p><div className="time-responses">{['Gute Idee!','Tut mir leid, ich habe keine Zeit.','Das weiß ich noch nicht.'].map(t=><p key={t}>{say(t)}</p>)}</div><Link href="/lessons/08#practice">Practise the whole lesson →</Link></section>
 <section id="time-words"><h2>Your time & plans vocabulary.</h2><p>{shown.length} word families match your selection.</p><div className="card-grid">{shown.map(c=><WordFamilyPreview key={c.id} card={c} href={c.path} lessonIds={c.lessons.map(n=>`lesson:${n.padStart(2,'0')}`)}/>)}</div></section><p className="muted">Based on Momente A1.1 KB 51–54, partner activities 163–164, AB 50–53 and the Lesson 8 glossary. Diagrams and practice combinations are authored learning aids.</p></div>;
}
