"use client";
import {useEffect,useState} from 'react';
import Link from 'next/link';
import type {WordCard} from '@/lib/content/word-card-types';
import {clockSaveId,clockHours,clockMinutes,clockWords,clockSentence,clockMeaning,digitalTime,weekDays,dayParts,timePlaces,type ClockMode} from '@/lib/study/time-sheet';
import {CheatSheetNav} from './CheatSheetNav';
import {GermanText,SaveButton} from './StudyProvider';
import {LineAudio} from './StudyAudio';
import {StudyScopeNotice} from './StudyScope';
import {tagsForLesson} from '@/lib/study/scope';
import {clockBookmark,readClockBookmark,planBookmark,readPlanBookmark,timedPlanParts,timedPlanSentence,timedPlanMeaning,timedPlanSaveId,type PlanSettings} from '@/lib/study/time-learning';
import {ClockFace,HalfHourCue,ClockListening,WeeklyPlanBoard} from './TimeTools';
import {TimePrintSummary} from './HobbyTimePrint';
import {SheetWordIndex} from './SheetWordIndex';

export function TimeCheatSheet({cards,speech}:{cards:WordCard[];speech:Record<string,string>}){
 const [hour,setHour]=useState(15),[minute,setMinute]=useState(30),[mode,setMode]=useState<ClockMode>('everyday'),[day,setDay]=useState(0),[place,setPlace]=useState(0),[front,setFront]=useState(true),[reveal,setReveal]=useState(true),[withTime,setWithTime]=useState(false);
 const restorePlan=(state:PlanSettings)=>{setDay(state.day);setPlace(state.place);setFront(state.front);setWithTime(state.withTime);setHour(state.hour);setMinute(state.minute);window.history.replaceState(window.history.state,"",`${window.location.pathname}${window.location.search}${planBookmark(state)}`);};
 useEffect(()=>{const restore=()=>{const clock=readClockBookmark(window.location.hash),plan=readPlanBookmark(window.location.hash);if(clock){setHour(clock.hour);setMinute(clock.minute);setMode(clock.mode);setReveal(true);}if(plan){setDay(plan.day);setPlace(plan.place);setFront(plan.front);setWithTime(plan.withTime);setHour(plan.hour);setMinute(plan.minute);}if(clock||plan)requestAnimationFrame(()=>document.getElementById(clock?"clock-lab":"plan-lab")?.scrollIntoView({block:"start"}));};restore();window.addEventListener("hashchange",restore);return()=>window.removeEventListener("hashchange",restore);},[]);
 const planState={day,place,front,withTime,hour,minute};
 const sentence=clockSentence(hour,minute,mode),meaning=clockMeaning(hour,minute,mode),plan=timedPlanSentence(planState),parts=timedPlanParts(planState);
 const say=(text:string)=><span className="sheet-spoken"><GermanText text={text}/><LineAudio compact text={text} src={speech[text]}/></span>;
 return <div className="study-workspace time-sheet"><CheatSheetNav current="time"/><header className="study-page-header"><div><p className="study-eyebrow">Lesson 8 · Time, weekdays & making plans</p><h1>Halfway to the next hour.</h1><p>Read the clock. Choose the day. Make a plan that sounds right.</p></div><button type="button" className="study-secondary" onClick={()=>window.print()}>Print cheat sheet</button></header>
 <nav className="sheet-jump" aria-label="Time sheet sections"><Link href="#clock-lab">Interactive clock</Link><Link href="#time-map">am · um · in der</Link><Link href="#week-map">Week & day</Link><Link href="#plan-lab">Make a plan</Link><Link href="#time-words">Word cards</Link><Link href="#clock-listening">Listen & choose</Link><Link href="#sheet-practice">Card practice</Link></nav>
 <section id="clock-lab"><h2>Move the clock. Hear the time.</h2><div className="clock-layout"><div><ClockFace hour={hour} minute={minute}/><p className="clock-digital">{digitalTime(hour,minute)}</p><div className="sheet-controls"><label>Hour<select aria-label="Clock hour" value={hour} onChange={e=>setHour(Number(e.target.value))}>{clockHours.map(h=><option key={h} value={h}>{String(h).padStart(2,'0')}</option>)}</select></label><label>Minute<select aria-label="Clock minute" value={minute} onChange={e=>setMinute(Number(e.target.value))}>{clockMinutes.map(m=><option key={m} value={m}>{String(m).padStart(2,'0')}</option>)}</select></label></div></div>
 <div className="clock-answer"><div role="group" className="time-mode" aria-label="Clock style">{(['everyday','official'] as const).map(m=><button type="button" key={m} aria-pressed={mode===m} onClick={()=>setMode(m)}>{m==='everyday'?'Everyday · 12-hour':'Official · 24-hour'}</button>)}</div><label className="time-recall"><input type="checkbox" checked={reveal} onChange={e=>setReveal(e.target.checked)}/> Show the answer</label>{reveal?<div aria-live="polite"><h3 lang="de">{clockWords(hour,minute,mode)}</h3><p>{say(sentence)}</p><p>{meaning}</p><SaveButton item={{id:clockSaveId(hour,minute,mode),title:sentence,meaning,kind:'phrase',lesson:8,href:`/cheat-sheets/time${clockBookmark({hour,minute,mode})}`,audio:speech[sentence]??null}}/></div>:<p className="clock-hidden">Say the time first, then reveal it.</p>}<HalfHourCue hour={hour} minute={minute}/><p>With <span lang="de">Uhr</span>: <b lang="de">ein Uhr</b>. Without it: <b lang="de">Viertel nach eins</b>.</p><p className="muted">Everyday time needs morning/evening context. These are the variants taught in your book; regional wording can differ.</p></div></div></section>
 <section id="time-map"><StudyScopeNotice tags={tagsForLesson(8)} subject="This time reference"/><h2>Three time signals to remember.</h2><div className="time-prepositions">{[{key:'am',title:'DAY / PART OF DAY',de:'am Wochenende',en:'at the weekend',cue:'am Montag · am Morgen · am Abend'},{key:'um',title:'CLOCK TIME',de:'um vier',en:'at four',cue:'um ein Uhr · um halb vier'},{key:'in der',title:'THE NIGHT EXCEPTION',de:'in der Nacht',en:'at night',cue:'Remember die Nacht → in der Nacht.'}].map((p,i)=><article key={p.key} data-time-kind={i}><small>{p.title}</small><h3>{p.key}</h3><p>{say(p.de)}</p><p>{p.en}</p><p>{p.cue}</p></article>)}</div><div className="time-duration-note"><h3>What time, which day, or how long?</h3><p>{say("um drei Uhr")} · at three o’clock</p><p>{say("am Montag")} · on Monday</p><p>{say("eine Stunde")} · one hour / {say("zwei Stunden")} · two hours</p><p>Duration wording is an extra comparison: Uhr names clock time; Stunde measures an hour.</p></div><p><b>No preposition before heute:</b> {say('heute Abend')} · this evening.</p></section>
 <section id="week-map"><h2>Seven days. One article: der.</h2><WeeklyPlanBoard state={planState} onChooseDay={setDay} onRestore={state=>{restorePlan(state);document.getElementById("plan-lab")?.scrollIntoView({block:"start"});}}/><p><b lang="de">das Wochenende</b> = Saturday + Sunday → {say('am Wochenende')}</p><div className="day-map">{dayParts.map((p,i)=><article key={p.de} data-night={i===5}><small>{i+1}</small><p>{say(p.de)}</p><span>{p.en}</span></article>)}</div></section>
 <section id="plan-lab"><h2>Time first. Verb still second.</h2><p>The selected weekday carries into your plan. Tap a destination; switch the order and watch the verb stay in block 2.</p><label>Plan destination<select value={place} onChange={event=>setPlace(Number(event.target.value))}>{timePlaces.map((destination,index)=><option key={destination.de} value={index}>{destination.de} · {destination.en}</option>)}</select></label><details><summary>Destination articles · all twelve places</summary><div className="time-places">{timePlaces.map((p,i)=><button type="button" key={p.de} data-gender={p.tone} aria-pressed={place===i} onClick={()=>setPlace(i)}><b lang="de">{p.de}</b><span lang="de">{p.to}</span></button>)}</div></details><div className="sheet-controls plan-time-controls"><label>Plan day<select value={day} onChange={event=>setDay(Number(event.target.value))}>{weekDays.map((value,index)=><option key={value} value={index}>{value}</option>)}</select></label><label>Plan hour<select value={hour} onChange={event=>setHour(Number(event.target.value))}>{clockHours.map(value=><option key={value} value={value}>{String(value).padStart(2,'0')}</option>)}</select></label><label>Plan minute<select value={minute} onChange={event=>setMinute(Number(event.target.value))}>{clockMinutes.map(value=><option key={value} value={value}>{String(value).padStart(2,'0')}</option>)}</select></label></div><label className="time-recall"><input type="checkbox" checked={withTime} onChange={event=>setWithTime(event.target.checked)}/> Include the clock time in this plan</label><label className="time-recall"><input type="checkbox" checked={front} onChange={e=>setFront(e.target.checked)}/> Put the time first</label><div className="time-word-order" data-with-time={withTime} aria-live="polite">{parts.map((p,i)=><div key={i} data-verb={i===1} data-time-block={withTime&&i===(front?0:2)}><small>{i===1?'VERB · POSITION 2':`BLOCK ${i+1}`}</small><strong lang="de">{p}</strong></div>)}</div><div className="plan-answer"><p>{say(plan)}</p><p>{timedPlanMeaning(planState)}</p><SaveButton item={{id:timedPlanSaveId(planState),title:plan,meaning:timedPlanMeaning(planState),kind:'phrase',lesson:8,href:`/cheat-sheets/time${planBookmark(planState)}`,audio:speech[plan]??null}}/></div><p><b>Destination articles:</b> <span lang="de">in das → ins</span> · <span lang="de">in eine</span> · <span lang="de">in einen</span>.</p><div className="time-responses">{['Gute Idee!','Tut mir leid, ich habe keine Zeit.','Das weiß ich noch nicht.'].map(t=><p key={t}>{say(t)}</p>)}</div><Link href="/lessons/08#practice">Practise the whole lesson →</Link></section>
 <ClockListening speech={speech}/><SheetWordIndex cards={cards} speech={speech} path="/cheat-sheets/time" id="time-words" title="Your time & plans vocabulary."/><p className="muted">Based on Momente A1.1 KB 51–54, partner activities 163–164, AB 50–53 and the Lesson 8 glossary. Diagrams and practice combinations are authored learning aids.</p><TimePrintSummary/></div>;
}
