"use client";
import {useState} from 'react';
import Link from 'next/link';
import type {WordCard} from '@/lib/content/word-card-types';
import {travelVerbs,travelPeople,travelModes,travelParts,travelSentence,travelMeaning,travelSaveId,travelBoard,announcementModels,type TravelMode} from '@/lib/study/travel-sheet';
import {GermanText,SaveButton} from './StudyProvider';
import {LineAudio} from './StudyAudio';
import {CheatSheetNav} from './CheatSheetNav';
import {useStudyScope} from './StudyScope';
import {WordFamilyPreview} from '../word-cards/WordFamilyPreview';
export function TravelCheatSheet({cards,speech}:{cards:WordCard[];speech:Record<string,string>}){
 const [verb,setVerb]=useState(0),[person,setPerson]=useState(1),[mode,setMode]=useState<TravelMode>('w-question'),[english,setEnglish]=useState(true),[showPrefix,setShowPrefix]=useState(true),[announcement,setAnnouncement]=useState(0),[answer,setAnswer]=useState<string|null>(null),[transcript,setTranscript]=useState(false);
 const {matches}=useStudyScope();const v=travelVerbs[verb]!,sentence=travelSentence(verb,person,mode),meaning=travelMeaning(verb,person,mode),parts=travelParts(verb,person,mode),a=announcementModels[announcement]!,shown=cards.filter(c=>c.studyTags&&matches(c.studyTags));
 const say=(text:string)=><span className="sheet-spoken"><GermanText text={text}/><LineAudio compact text={text} src={speech[text]}/></span>;
 return <div className="study-workspace travel-sheet"><CheatSheetNav current="travel"/><header className="study-page-header"><div><p className="study-eyebrow">Lesson 10 · Travel & separable verbs</p><h1>Keep the two halves connected.</h1><p>The verb tells you what happens. Its final prefix tells you the whole story.</p></div></header><nav className="sheet-jump" aria-label="Travel sheet sections"><a href="#travel-route">Get on. Change. Get off.</a><a href="#travel-bracket">Build a sentence</a><a href="#travel-board">Transport & articles</a><a href="#travel-listening">Catch the detail</a><a href="#travel-words">Word cards</a></nav>
 <section id="travel-route"><h2>Three steps through a journey.</h2><div className="travel-route">{[{word:'einsteigen',cue:'GET ON',en:'Enter the train or bus.',index:4},{word:'umsteigen',cue:'CHANGE',en:'Switch to another train or bus.',index:5},{word:'aussteigen',cue:'GET OFF',en:'Leave the train or bus.',index:6}].map((step,i)=><button type="button" key={step.word} onClick={()=>{setVerb(step.index);setMode('statement');}}><small>{i+1} · {step.cue}</small><strong lang="de">{step.word}</strong><span>{step.en}</span></button>)}</div><p><b>Departure:</b> <span lang="de">abfahren / abfliegen</span>. <b>Arrival:</b> <span lang="de">ankommen</span>. A train pulling into the station <span lang="de">fährt ein</span>.</p></section>
 <section id="travel-bracket"><h2>Build the sentence bracket.</h2><div className="travel-verb-grid">{travelVerbs.map((item,i)=><button type="button" key={item.verb} aria-pressed={verb===i} onClick={()=>setVerb(i)}><span aria-hidden="true">{item.icon}</span><strong lang="de"><mark>{item.prefix}</mark>{item.verb.slice(item.prefix.length)}</strong></button>)}</div><div className="sheet-controls"><label>Who?<select aria-label="Travel sentence person" value={person} onChange={e=>setPerson(Number(e.target.value))}>{travelPeople.map((p,i)=><option value={i} key={p.de}>{p.de}{p.de==='Sie'?' · formal you':''}</option>)}</select></label><label>Sentence type<select aria-label="Travel sentence type" value={mode} onChange={e=>setMode(e.target.value as TravelMode)}>{travelModes.map(m=><option key={m.id} value={m.id}>{m.label}</option>)}</select></label></div><div className="sheet-controls"><label><input type="checkbox" checked={english} onChange={e=>setEnglish(e.target.checked)}/> Show English</label><label><input type="checkbox" checked={showPrefix} onChange={e=>setShowPrefix(e.target.checked)}/> Reveal final verb part</label></div><div className="travel-sentence" aria-live="polite"><p className="travel-cue">{mode==='modal'?'Können is conjugated. The infinitive stays together at the end.':mode==='yes-no'?'Start with the conjugated stem. Finish with its prefix.':'The conjugated stem is second. Its prefix waits at the end.'}</p><div className="travel-parts" aria-label="Sentence word order">{parts.map((p,i)=><span key={i} data-role={p.role}><small>{p.role==='stem'?'CONJUGATED VERB':p.role==='prefix'?'FINAL PREFIX':p.role==='infinitive'?'WHOLE INFINITIVE':p.role==='person'?'PERSON':p.role==='question'?'QUESTION':'DETAIL'}</small><strong lang="de">{!showPrefix&&['prefix','infinitive'].includes(p.role)?'…':p.text}</strong></span>)}</div>{showPrefix?<p className="travel-result">{say(sentence)}</p>:<button type="button" className="study-secondary" onClick={()=>setShowPrefix(true)}>Reveal the complete sentence</button>}{english&&<p>{meaning}</p>}<SaveButton item={{id:travelSaveId(verb,person,mode),title:sentence,meaning,kind:'phrase',lesson:10,href:'/cheat-sheets/travel#travel-bracket',audio:speech[sentence]??null}}/></div><p><b>Listen to the first part:</b> {say(v.verb)}. Separable prefixes carry the stress. <b>Not every beginning separates:</b> <span lang="de">verstehen, versuchen, bestellen, besuchen, beginnen</span> keep their beginnings attached.</p></section>
 <section id="travel-board"><h2>Pack the article with the noun.</h2><div className="travel-nouns">{travelBoard.map(w=><article key={w.de} data-gender={w.tone}><span aria-hidden="true">{w.icon}</span><strong>{say(w.de)}</strong><small>{w.en}</small></article>)}</div><div className="travel-place-map"><article><h3 lang="de">der Bahnsteig</h3><p>The platform where you wait.</p>{say('Der Intercity fährt von Bahnsteig drei ab.')}</article><article><h3 lang="de">das Gleis</h3><p>The railway track, often the number shown for boarding.</p>{say('Die U-Bahn fährt an Gleis zwei ein.')}</article><article><h3 lang="de">der Ausgang</h3><p>An exit; an airport gate in these announcements.</p>{say('Das Flugzeug steht am Ausgang B48.')}</article></div><p><b>One taxi, two valid plurals:</b> <span lang="de">das Taxi → die Taxen / die Taxis</span>. Both are accepted in the word card.</p></section>
 <section id="travel-listening"><h2>Catch the detail before you look.</h2><p>These short practice clips use generated German speech. The <Link href="/book?page=coursebook-68">five original coursebook announcements</Link> and <Link href="/book?page=workbook-69">workbook announcement</Link> are in the interactive book with their publisher transcripts.</p><div className="travel-announcement"><small>ANNOUNCEMENT {announcement+1} / {announcementModels.length}</small><h3>{a.question}</h3><LineAudio text={a.de} src={speech[a.de]}/><div className="study-row">{a.choices.map(c=><button className="study-secondary" type="button" key={c} disabled={answer!==null} onClick={()=>setAnswer(c)}>{c}</button>)}</div>{answer!==null&&<p role="status">{answer===a.answer?'Correct.':`The answer is ${a.answer}`} Listen again, then compare with the transcript.</p>}<button type="button" className="study-secondary" aria-expanded={transcript} onClick={()=>setTranscript(!transcript)}>{transcript?'Hide practice transcript':'Show practice transcript'}</button>{transcript&&<div className="travel-transcript">{say(a.de)}<p>{a.en}</p></div>}<div className="study-row"><SaveButton item={{id:`l10-announcement-${announcement}`,title:a.de,meaning:a.en,kind:'phrase',lesson:10,href:'/cheat-sheets/travel#travel-listening',audio:speech[a.de]??null}}/><button type="button" className="study-primary" onClick={()=>{setAnnouncement((announcement+1)%announcementModels.length);setAnswer(null);setTranscript(false);}}>Next announcement →</button></div></div></section>
 <section id="travel-words"><h2>Your travel vocabulary.</h2><p>{shown.length} word families match your selection.</p><div className="card-grid">{shown.map(card=><WordFamilyPreview key={card.id} card={card} href={card.path} lessonIds={card.lessons.map(n=>`lesson:${n.padStart(2,'0')}`)}/>)}</div></section><Link href="/lessons/10#practice">Practise the whole lesson →</Link><p className="muted">Based on Momente A1.1 KB 65–68, partner pages 167/195, AB 66–69 and 91, and glossary pages 13–15. Sentence combinations, diagrams and listening drills are authored learning aids.</p></div>;
}
