import {expect,test} from "@playwright/test";

for(const width of [320,1440])test(`country and home word cards return to the selected item at ${width}px`,async({page})=>{
  await page.setViewportSize({width,height:1000});
  await page.goto("cheat-sheets/");
  await page.getByRole("textbox",{name:"Find a country or language",exact:true}).fill("Deutschland");
  const country=page.locator("#country-DE");
  await country.locator("summary").click();
  await country.getByRole("link",{name:"Open vocabulary card →",exact:true}).click();
  await page.getByRole("link",{name:/Back/}).first().click();
  await expect(page.getByRole("combobox",{name:"Choose a country",exact:true})).toHaveValue("DE");
  await expect(page).toHaveURL(/cheat-sheets\/?#country-DE$/);
  await page.goto("cheat-sheets/home/");
  await page.getByRole("combobox",{name:"Explore a word",exact:true}).selectOption("bett");
  await page.locator(".home-focus").getByRole("link",{name:"Full vocabulary card →",exact:true}).click();
  await page.getByRole("link",{name:/Back/}).first().click();
  await expect(page).toHaveURL(/cheat-sheets\/home\/?#home-bett$/);
  await expect(page.getByRole("combobox",{name:"Explore a word",exact:true})).toHaveValue("bett");
});

for(const width of [320,1440]) test(`country and home recall follow selection, search and saved filters at ${width}px`,async({page})=>{
  await page.setViewportSize({width,height:1000});
  await page.goto("cheat-sheets/");
  const scope=page.locator(".study-scope");
  await scope.locator("summary").click();
  await scope.getByRole("button",{name:"One lesson",exact:true}).click();
  await scope.getByRole("combobox",{name:"Selected lesson"}).selectOption("12");
  await scope.getByRole("combobox",{name:"Material source"}).selectOption("course");
  await scope.locator("summary").click();
  await page.getByRole("textbox",{name:"Find a country or language"}).fill("Deutschland");
  await expect(page.locator(".country-row")).toHaveCount(1);
  const countryQuiz=page.locator(".country-quiz");
  await expect(countryQuiz).toContainText("Question 1 / 1");
  await countryQuiz.getByRole("button",{name:"aus Deutschland",exact:true}).click();
  await expect(countryQuiz).toContainText("Exactly.");
  await expect(countryQuiz.getByRole("button",{name:"Listen: Ich komme aus Deutschland.",exact:true})).toBeVisible();
  await page.locator(".country-row").getByRole("button",{name:/^Save to review:/}).click();
  await page.goto("saved/");
  await expect(page.locator(".study-saved-card")).toHaveCount(1);
  await expect(page.locator(".study-saved-card")).toContainText("Ich komme aus Deutschland.");
  await page.reload();
  await expect(page.locator(".study-saved-card")).toHaveCount(1);
  await page.goto("cheat-sheets/");
  await page.getByRole("button",{name:"Saved for review",exact:true}).click();
  await expect(page.locator(".country-row")).toHaveCount(1);
  await expect(page.locator(".country-quiz")).toContainText("Deutschland");
  await page.locator(".country-row").getByRole("button",{name:/^Remove from review:/}).click();
  await expect(page.getByRole("heading",{name:"No matching practice items"})).toBeVisible();
  await page.goto("cheat-sheets/home/");
  await expect(page.locator(".home-word-card")).toHaveCount(0);
  await expect(page.getByRole("heading",{name:"No matching practice items"})).toBeVisible();
  await expect(page.locator(".home-focus .study-scope-notice")).toContainText("This word is outside your study selection.");
  await page.locator(".home-focus").getByRole("button",{name:"Study these lessons",exact:true}).click();
  await page.getByRole("textbox",{name:"Find a word",exact:true}).fill("Stuhl");
  await expect(page.locator(".home-word-card")).toHaveCount(1);
  await expect(page.locator(".home-quiz")).toContainText("Question 1 / 2");
  await page.locator(".home-quiz").getByRole("button",{name:"der",exact:true}).click();
  await expect(page.locator(".home-quiz")).toContainText("Exactly.");
  await page.getByRole("textbox",{name:"Find a word",exact:true}).fill("Tisch");
  await expect(page.locator(".home-quiz")).toContainText("Question 1 / 1");
  await expect(page.locator(".home-quiz")).toContainText("___ Tisch");
  await page.locator(".home-quiz").getByRole("button",{name:"der",exact:true}).click();
  await expect(page.locator(".home-quiz")).toContainText("Exactly.");
  await page.getByRole("textbox",{name:"Find a word",exact:true}).fill("nothing-matches");
  await expect(page.getByRole("heading",{name:"No matching practice items"})).toBeVisible();
  await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1);
});
