import {expect,test} from "@playwright/test";

for(const width of [320,1440])test(`object picture, description and saved settings at ${width}px`,async({page},info)=>{
 await page.setViewportSize({width,height:1000});await page.goto("cheat-sheets/objects/");const lab=page.locator("#object-lab");
 await lab.getByRole("button",{name:"die Uhr watch",exact:true}).click();await lab.getByRole("combobox",{name:"Object colour",exact:true}).selectOption("rot");await lab.getByRole("combobox",{name:"Material",exact:true}).selectOption("Kunststoff");await lab.getByRole("combobox",{name:"Shape · extra practice",exact:true}).selectOption("eckig");
 await expect(lab.locator(".object-illustration rect")).toHaveAttribute("fill","#da3848");await expect(lab.locator(".object-description")).toContainText("Die Uhr ist aus Kunststoff.");await expect(lab.locator(".object-description")).toContainText("Sie ist rot.");
 await lab.getByRole("checkbox",{name:"Correct a guess with kein / keine",exact:true}).check();await lab.getByRole("combobox",{name:"Guess to correct",exact:true}).selectOption("1");await expect(lab.locator(".object-description")).toContainText("Das ist kein Buch.");await expect(lab.locator(".object-description")).toContainText("Das ist eine Uhr.");
 await lab.getByRole("button",{name:/^Save to review:/}).click();await page.goto("saved/");await page.locator(".study-saved-card").filter({hasText:"Die Uhr ist aus Kunststoff."}).getByRole("link",{name:"Open in context →",exact:true}).click();
 await expect(lab.getByRole("combobox",{name:"Object colour",exact:true})).toHaveValue("rot");await expect(lab.getByRole("combobox",{name:"Material",exact:true})).toHaveValue("Kunststoff");await expect(lab.getByRole("combobox",{name:"Guess to correct",exact:true})).toHaveValue("1");
 await lab.getByRole("button",{name:"Hide description & recall",exact:true}).click();await expect(lab.locator(".object-description")).toHaveCount(0);await lab.getByRole("button",{name:"Reveal description",exact:true}).click();await lab.getByRole("button",{name:/^Remove from review:/}).click();
 await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1);await lab.screenshot({path:info.outputPath(`objects-${width}.png`)});
});

for(const width of [320,1440])test(`office roles, contextual return and phone listening at ${width}px`,async({page},info)=>{
 await page.setViewportSize({width,height:1000});await page.addInitScript(()=>{const NativeAudio=window.Audio;(window as unknown as {clips:HTMLAudioElement[]}).clips=[];window.Audio=class extends NativeAudio{constructor(src?:string){super(src);(window as unknown as {clips:HTMLAudioElement[]}).clips.push(this);}};});
 await page.goto("cheat-sheets/office/");const lab=page.locator("#office-lab");await lab.getByRole("combobox",{name:"Choose an office word",exact:true}).selectOption("3");await lab.getByRole("checkbox",{name:"Negate with kein",exact:true}).check();await expect(lab.locator(".office-role-trail")).toContainText("keinen Stift.");await expect(lab.locator(".office-role-trail [data-gender]")).toHaveAttribute("data-gender","male");
 await lab.getByRole("checkbox",{name:"Make it plural",exact:true}).check();await expect(lab.locator(".office-role-trail")).toContainText("keine Stifte.");await expect(lab.locator(".office-role-trail [data-gender]")).toHaveAttribute("data-gender","plural");
 await lab.getByRole("button",{name:/^Save to review:/}).click();await page.goto("saved/");await page.locator(".study-saved-card").filter({hasText:"Ich brauche keine Stifte."}).getByRole("link",{name:"Open in context →",exact:true}).click();await expect(lab.getByRole("checkbox",{name:"Make it plural",exact:true})).toBeChecked();await expect(lab.locator(".office-role-trail")).toContainText("keine Stifte.");await lab.getByRole("button",{name:/^Remove from review:/}).click();await lab.screenshot({path:info.outputPath(`office-${width}.png`)});
 if(width===320){await expect(lab.locator(".office-desk")).toBeHidden();await lab.locator(".office-desk-overview > summary").click();await expect(lab.locator(".office-desk")).toBeVisible();await lab.locator(".office-desk-overview").screenshot({path:info.outputPath("office-overview-320.png")});await lab.locator(".office-desk-overview > summary").click();}
 const details=page.locator("#phone-details");await details.getByRole("button",{name:"Listen: practice digits",exact:true}).click();await expect.poll(()=>page.evaluate(()=>{const clip=(window as unknown as {clips:HTMLAudioElement[]}).clips.at(-1);return !!clip&&clip.currentTime>0&&clip.src.includes("/audio/");})).toBe(true);
 await details.getByRole("textbox",{name:"Digits you heard",exact:true}).fill("176");await details.getByRole("button",{name:"Check digits",exact:true}).click();await expect(details.getByRole("status")).toContainText("Listen again and compare: 0176");await details.getByRole("textbox",{name:"Digits you heard",exact:true}).fill("0176");await details.getByRole("button",{name:"Check digits",exact:true}).click();await expect(details.getByRole("status")).toContainText("Exactly.");
 await details.getByRole("textbox",{name:"Name to spell",exact:true}).fill("Groß");await expect(details).toContainText("G · R · O · ß");await details.screenshot({path:info.outputPath(`office-phone-${width}.png`)});for(const input of await details.locator("input").all()){const box=await input.boundingBox();expect(box?.height).toBeGreaterThanOrEqual(44);expect((box?.x??0)+(box?.width??0)).toBeLessThanOrEqual(width);}await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1);
});

test("bounded sheet cards, filters, full-card return and saved phone turn",async({page})=>{
 await page.goto("cheat-sheets/office/");const words=page.locator("#office-words");await expect(words.locator("[data-sheet-card]")).toHaveCount(12);await words.getByRole("button",{name:"Show 12 more cards",exact:true}).click();await expect(words.locator("[data-sheet-card]")).toHaveCount(24);
 await words.getByRole("searchbox",{name:"Find a card",exact:true}).fill("Kalender");await expect(words.locator("[data-sheet-card]").first()).toBeVisible();const first=words.locator("[data-sheet-card]").first(),id=await first.getAttribute("data-sheet-card");await first.getByRole("link",{name:"Study this word family",exact:true}).click();await page.getByRole("link",{name:/Back/}).first().click();await expect(words.getByRole("searchbox",{name:"Find a card",exact:true})).toHaveValue("Kalender");await expect(page.locator(`[data-sheet-card="${id}"]`)).toBeVisible();
 await words.getByRole("button",{name:"Show saved cards",exact:true}).click();await expect(page.locator("#sheet-practice")).toContainText("No matching practice items");
 const phone=page.locator("#phone-lab");await phone.getByRole("button",{name:"Next turn →",exact:true}).click();await phone.getByRole("button",{name:/^Save to review:/}).click();await page.goto("saved/");await page.locator(".study-saved-card").filter({hasText:"mein Name ist Tom Berger"}).getByRole("link",{name:"Open in context →",exact:true}).click();await expect(phone).toContainText("2 / 7 · Caller");
});

test("object and office summaries export to A4 and Letter",async({page},info)=>{
 for(const sheet of ["objects","office"]){await page.goto(`cheat-sheets/${sheet}/`);await page.emulateMedia({media:"print"});await expect(page.locator(".sheet-print-summary")).toBeVisible();await page.evaluate(()=>document.fonts.ready);for(const format of ["A4","Letter"] as const){await page.pdf({path:info.outputPath(`${sheet}-${format}.pdf`),format,printBackground:true,margin:{top:"12mm",bottom:"12mm",left:"12mm",right:"12mm"}});}await page.emulateMedia({media:"screen"});}
});
