import {expect,test} from "@playwright/test";

for(const width of [320,1440])test(`hobby illustrations, contrasts and saved settings at ${width}px`,async({page},info)=>{
 await page.setViewportSize({width,height:1000});await page.goto("cheat-sheets/hobbies/");await page.getByRole("combobox",{name:"Activity to explore",exact:true}).selectOption("5");await expect(page.locator("#hobby-map")).toContainText("Ich fahre gern Rad.");
 const lab=page.locator("#ability-lab");await lab.getByRole("combobox",{name:"Choose a person",exact:true}).selectOption("1");await lab.getByRole("group",{name:"Ability scale",exact:true}).getByRole("button",{name:"gar nicht not at all",exact:true}).click();await lab.getByRole("checkbox",{name:"Make it a question",exact:true}).check();await expect(lab.locator(".hobby-result")).toContainText("Kannst du gar nicht Rad fahren?");
 await lab.getByRole("button",{name:/^Save to review:/}).click();await page.goto("saved/");await page.locator(".study-saved-card").filter({hasText:"Kannst du gar nicht Rad fahren?"}).getByRole("link",{name:"Open in context →",exact:true}).click();await expect(page.getByRole("combobox",{name:"Activity to explore",exact:true})).toHaveValue("5");await expect(lab.getByRole("checkbox",{name:"Make it a question",exact:true})).toBeChecked();await expect(lab.getByRole("combobox",{name:"Choose a person",exact:true})).toHaveValue("1");await lab.getByRole("button",{name:/^Remove from review:/}).click();
 const frequency=page.locator("#frequency-lab");await frequency.getByRole("button",{name:"manchmal sometimes",exact:true}).click();await expect(frequency.locator(".frequency-week > div")).toHaveCount(7);await expect(frequency).toContainText("not a definition");await expect(frequency.locator(".hobby-frequency")).toContainText("Ich fahre manchmal Rad.");await frequency.screenshot({path:info.outputPath(`hobby-frequency-${width}.png`)});
 const practice=page.locator("#hobby-contrast-practice");await practice.getByRole("button",{name:"Ich fahre gern Rad.",exact:true}).click();await expect(practice.getByRole("status")).toContainText("Keep these meanings separate");await practice.getByRole("button",{name:"Next contrast →",exact:true}).click();await practice.getByRole("button",{name:"Ich fahre gern Rad.",exact:true}).click();await expect(practice.getByRole("status")).toContainText("Exactly.");
 await page.locator("#hobby-map").screenshot({path:info.outputPath(`hobby-map-${width}.png`)});await page.getByRole("combobox",{name:"Activity to explore",exact:true}).selectOption("1");const overview=page.locator(".hobby-meaning-map article").first();await overview.getByRole("button",{name:/^Save to review:/}).click();await practice.getByRole("button",{name:"Ich kann gut kochen.",exact:true}).click();await practice.getByRole("button",{name:/^Remove from review:/}).click();await expect(overview.getByRole("button",{name:/^Save to review:/})).toBeVisible();await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1);
});

for(const width of [320,1440])test(`clock listening, weekly plans and reload at ${width}px`,async({page},info)=>{
 await page.setViewportSize({width,height:1000});await page.addInitScript(()=>{const NativeAudio=window.Audio;(window as unknown as {clips:HTMLAudioElement[]}).clips=[];window.Audio=class extends NativeAudio{constructor(src?:string){super(src);(window as unknown as {clips:HTMLAudioElement[]}).clips.push(this);}};});await page.goto("cheat-sheets/time/");
 const clock=page.locator("#clock-lab");await clock.getByRole("combobox",{name:"Clock hour",exact:true}).selectOption("0");await clock.getByRole("combobox",{name:"Clock minute",exact:true}).selectOption("30");await expect(clock.locator(".half-memory")).toContainText("halb eins → 12:30");await clock.getByRole("button",{name:/^Save to review:/}).click();await page.goto("saved/");await page.locator(".study-saved-card").filter({hasText:"Es ist halb eins."}).getByRole("link",{name:"Open in context →",exact:true}).click();await expect(clock.getByRole("combobox",{name:"Clock hour",exact:true})).toHaveValue("0");await clock.getByRole("button",{name:/^Remove from review:/}).click();await clock.screenshot({path:info.outputPath(`time-clock-${width}.png`)});
 const plan=page.locator("#plan-lab");await plan.getByRole("combobox",{name:"Plan day",exact:true}).selectOption("2");await plan.getByRole("combobox",{name:"Plan destination",exact:true}).selectOption("0");await plan.getByRole("combobox",{name:"Plan hour",exact:true}).selectOption("15");await plan.getByRole("combobox",{name:"Plan minute",exact:true}).selectOption("30");await plan.getByRole("checkbox",{name:"Include the clock time in this plan",exact:true}).check();await expect(plan.locator(".plan-answer")).toContainText("Am Mittwoch um fünfzehn Uhr dreißig gehen wir ins Kino.");await expect(plan.locator(".time-word-order > div").nth(0)).toContainText("Am Mittwoch um fünfzehn Uhr dreißig");await expect(plan.locator(".time-word-order > div").nth(1)).toContainText("gehen");await plan.getByRole("button",{name:/^Save to review:/}).click();await page.reload();await expect(page.locator(".weekly-plan-grid")).toContainText("1 saved plan");await page.locator(".weekly-plan-grid article").filter({hasText:"Mittwoch"}).locator("summary").click();await page.getByRole("button",{name:"15:30 · ins Kino Open saved plan",exact:true}).click();await expect(plan.getByRole("combobox",{name:"Plan day",exact:true})).toHaveValue("2");await expect(plan.getByRole("checkbox",{name:"Include the clock time in this plan",exact:true})).toBeChecked();await page.reload();await expect(plan.getByRole("combobox",{name:"Plan day",exact:true})).toHaveValue("2");await expect(plan.getByRole("checkbox",{name:"Include the clock time in this plan",exact:true})).toBeChecked();await expect(plan.getByRole("combobox",{name:"Plan hour",exact:true})).toHaveValue("15");await expect(plan.getByRole("combobox",{name:"Plan minute",exact:true})).toHaveValue("30");await plan.screenshot({path:info.outputPath(`time-plan-${width}.png`)});await page.locator("#week-map").screenshot({path:info.outputPath(`time-week-${width}.png`)});
 const listening=page.locator("#clock-listening");await expect(listening).not.toContainText("Es ist halb vier.");await listening.getByRole("button",{name:"Listen: time to identify",exact:true}).click();await expect.poll(()=>page.evaluate(()=>{const clip=(window as unknown as {clips:HTMLAudioElement[]}).clips.at(-1);return !!clip&&clip.currentTime>0;})).toBe(true);await listening.getByRole("button",{name:"Choose 3:30",exact:true}).click();await expect(listening.getByRole("status")).toContainText("Exactly.");await listening.screenshot({path:info.outputPath(`time-listening-${width}.png`)});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1);
});

test("hobby and time card practice respects scope and saved filters",async({page})=>{
 for(const sheet of ["hobbies","time"]){await page.goto(`cheat-sheets/${sheet}/`);await page.getByRole("button",{name:"Show saved cards",exact:true}).click();await expect(page.locator("#sheet-practice")).toContainText("No matching practice items");await page.getByRole("button",{name:"Showing saved cards",exact:true}).click();await expect(page.locator("[data-sheet-card]")).toHaveCount(12);const scope=page.locator(".study-scope");await scope.locator("summary").click();await scope.getByRole("button",{name:"One lesson",exact:true}).click();await scope.getByRole("combobox",{name:"Selected lesson",exact:true}).selectOption("1");await scope.locator("summary").click();await expect(page.locator(sheet==="hobbies"?"#hobby-map":"#time-map")).toContainText("outside your study selection");await expect(page.locator(sheet==="hobbies"?"#hobby-words":"#time-words").getByRole("status")).toContainText(`${sheet==="hobbies"?14:9} cards`);await expect(page.locator("#sheet-practice")).toContainText("Question 1 /");await page.getByRole("button",{name:"Show saved cards",exact:true}).click();await expect(page.locator("#sheet-practice")).toContainText("No matching practice items");await page.getByRole("button",{name:"Showing saved cards",exact:true}).click();await scope.locator("summary").click();await scope.getByRole("button",{name:"All lessons",exact:true}).click();await scope.locator("summary").click();}
});

test("hobbies and time print concise A4 and Letter summaries",async({page},info)=>{
 for(const sheet of ["hobbies","time"]){await page.goto(`cheat-sheets/${sheet}/`);await page.emulateMedia({media:"print"});await expect(page.locator(".sheet-print-summary")).toBeVisible();await page.evaluate(()=>document.fonts.ready);for(const format of ["A4","Letter"] as const)await page.pdf({path:info.outputPath(`${sheet}-${format}.pdf`),format,printBackground:true,margin:{top:"12mm",bottom:"12mm",left:"12mm",right:"12mm"}});await page.emulateMedia({media:"screen"});}
});
