import {expect,test} from "@playwright/test";

for(const width of [320,1440])test(`food menu, portions and saved context at ${width}px`,async({page},info)=>{
 await page.setViewportSize({width,height:1000});await page.addInitScript(()=>{const NativeAudio=window.Audio;(window as unknown as {clips:HTMLAudioElement[]}).clips=[];window.Audio=class extends NativeAudio{constructor(src?:string){super(src);(window as unknown as {clips:HTMLAudioElement[]}).clips.push(this);}};});await page.goto("cheat-sheets/food/");
 await page.locator(".food-board").getByRole("button",{name:"der Käse cheese",exact:true}).click();await expect(page.locator(".food-selected")).toHaveAttribute("data-gender","male");await page.locator(".food-selected h3").getByRole("button",{name:"Listen: der Käse",exact:true}).click();await expect.poll(()=>page.evaluate(()=>{const clip=(window as unknown as {clips:HTMLAudioElement[]}).clips.at(-1);return !!clip&&clip.currentTime>0;})).toBe(true);await expect(page.locator(".food-portion-cue")).toContainText("das Stück → ein Stück Käse");
 const lab=page.locator("#food-lab");await lab.getByRole("checkbox",{name:"Make it negative",exact:true}).check();await expect(lab.locator(".food-output")).toHaveAttribute("data-gender","neuter");await expect(lab.locator(".food-output")).toContainText("Ich möchte kein Stück Käse.");await lab.getByRole("button",{name:/^Save to review:/}).click();
 await page.goto("saved/");await page.locator(".study-saved-card").filter({hasText:"Ich möchte kein Stück Käse."}).getByRole("link",{name:"Open in context →",exact:true}).click();await expect(lab.getByRole("checkbox",{name:"Make it negative",exact:true})).toBeChecked();await expect(page.locator(".food-selected h3")).toContainText("der Käse");await lab.getByRole("button",{name:/^Remove from review:/}).click();
 const ordering=page.locator("#food-order");await ordering.getByRole("button",{name:"Reveal my turn",exact:true}).click();await expect(ordering.locator('[data-role="customer"]')).toContainText("Ich möchte ein Stück Käse.");await ordering.getByRole("button",{name:"Ich möchte eine Stück Käse.",exact:true}).click();await expect(ordering.getByRole("status")).toContainText("Look at the noun");await ordering.screenshot({path:info.outputPath(`food-order-${width}.png`)});
 await page.locator("#food-board").screenshot({path:info.outputPath(`food-menu-${width}.png`)});await page.locator(".food-selected").getByRole("link",{name:"Open full word card →",exact:true}).click();await page.getByRole("link",{name:"← Back",exact:true}).click();await expect(page.locator(".food-selected h3")).toContainText("der Käse");
 const replies=page.locator("#food-replies");await replies.getByRole("combobox",{name:"Other person's preference",exact:true}).selectOption("false");await replies.getByRole("button",{name:/^Save to review:/}).click();await page.goto("saved/");await page.locator(".study-saved-card").filter({hasText:"Ich mag keinen Tee. – Ich schon."}).getByRole("link",{name:"Open in context →",exact:true}).click();await expect(replies.getByRole("combobox",{name:"Other person's preference",exact:true})).toHaveValue("false");await expect(replies.locator(".food-dialogue")).toContainText("Ich schon.");const compounds=page.locator("#food-compounds");await compounds.getByRole("combobox",{name:"Choose a compound",exact:true}).selectOption("3");await compounds.getByRole("button",{name:/^Save to review:/}).click();await page.goto("saved/");await page.locator(".study-saved-card").filter({hasText:"die Tomate + die Suppe → die Tomatensuppe"}).getByRole("link",{name:"Open in context →",exact:true}).click();await expect(compounds.getByRole("combobox",{name:"Choose a compound",exact:true})).toHaveValue("3");
 await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1);
});

test("food groups, plurals, chosen practice and print",async({page},info)=>{
 await page.goto("cheat-sheets/food/");await page.getByRole("group",{name:"Menu category",exact:true}).getByRole("button",{name:"Drinks",exact:true}).click();await expect(page.locator(".food-board button")).toHaveCount(1);await page.locator(".food-board button").click();await expect(page.locator(".food-plural")).toContainText("die Tees");await page.getByRole("button",{name:"Show saved cards",exact:true}).click();await expect(page.locator("#sheet-practice")).toContainText("No matching practice items");await page.getByRole("button",{name:"Showing saved cards",exact:true}).click();await expect(page.locator("[data-sheet-card]")).toHaveCount(12);
 await page.emulateMedia({media:"print"});await page.evaluate(()=>document.fonts.ready);for(const format of ["A4","Letter"] as const)await page.pdf({path:info.outputPath(`food-${format}.pdf`),format,printBackground:true,margin:{top:"12mm",bottom:"12mm",left:"12mm",right:"12mm"}});
});
