import {expect,test} from "@playwright/test";

test.beforeEach(async({page})=>{
 await page.addInitScript(()=>{const NativeAudio=window.Audio;(window as unknown as {clips:HTMLAudioElement[]}).clips=[];window.Audio=class extends NativeAudio{constructor(src?:string){super(src);(window as unknown as {clips:HTMLAudioElement[]}).clips.push(this);}};});
});

for(const width of [320,1440])test(`book to transcript, meaning, review and exact return at ${width}px`,async({page},info)=>{
 await page.setViewportSize({width,height:1000});
 await page.goto("book/?page=coursebook-30");
 await page.getByRole("combobox",{name:"Page zoom",exact:true}).selectOption("150");
 await page.getByRole("combobox",{name:"Reading view",exact:true}).selectOption("read");
 await page.reload();
 await expect(page.getByRole("combobox",{name:"Reading view",exact:true})).toHaveValue("read");
 await page.getByRole("combobox",{name:"Reading view",exact:true}).selectOption("page");
 await expect(page.getByRole("combobox",{name:"Page zoom",exact:true})).toHaveValue("150");
 await page.getByRole("combobox",{name:"Page zoom",exact:true}).selectOption("0");
 if(width===320)expect((await page.locator(".book-paper").boundingBox())!.y).toBeLessThan(600);
 await page.screenshot({path:info.outputPath(`reader-first-screen-${width}.png`)});
 await expect(page.locator(".book-track")).toHaveCount(1);
 await page.getByRole("combobox",{name:"Page recording",exact:true}).selectOption("coursebook-l4-ex3-c8a4e473");
 await page.getByRole("link",{name:"Open focused listening →",exact:true}).click();
 await expect(page.locator(".book-track")).toHaveAttribute("data-recording-id","coursebook-l4-ex3-c8a4e473");
 await expect(page.locator(".recording-browser>div>button")).toHaveCount(12);
 const track=page.locator(".book-track"),original=track.locator("audio");
 await track.getByRole("button",{name:"Play from start",exact:true}).click();
 await expect.poll(()=>original.evaluate((audio:HTMLAudioElement)=>audio.currentTime)).toBeGreaterThan(0);
 await original.evaluate((audio:HTMLAudioElement)=>{audio.currentTime=6;audio.pause();});
 await expect(track.getByRole("button",{name:/Resume at 0:0[6-9]/})).toBeVisible();
 await track.getByRole("button",{name:"Repeat recording",exact:true}).click();
 await expect.poll(()=>original.evaluate((audio:HTMLAudioElement)=>audio.loop)).toBe(true);
 await track.locator("summary").click();
 const line=track.locator(".listening-transcript-lines>p").nth(1);
 const phrase=await line.locator(".study-german").getAttribute("aria-label");
 await line.locator(".study-german").evaluate(element=>{const range=document.createRange();range.selectNodeContents(element);const selection=window.getSelection()!;selection.removeAllRanges();selection.addRange(range);});
 await page.getByRole("button",{name:"Meaning of selection",exact:true}).click();
 await expect(page.getByRole("dialog",{name:"Quick dictionary"}).locator("input")).toHaveValue(phrase!);
 await page.keyboard.press("Escape");
 await line.getByRole("button",{name:/^Listen:/}).click();
 await expect.poll(()=>page.evaluate(()=>(window as unknown as {clips:HTMLAudioElement[]}).clips.at(-1)?.currentTime??0)).toBeGreaterThan(0);
 await expect.poll(()=>page.evaluate(()=>(window as unknown as {clips:HTMLAudioElement[]}).clips.at(-1)?.src??"")).toContain("/book/transcript-speech/");
 await expect.poll(()=>original.evaluate((audio:HTMLAudioElement)=>audio.paused)).toBe(true);
 await line.getByRole("button",{name:/^Save to review:/}).click();
 await page.goto("saved/");
 await page.getByRole("button",{name:"Review 1 items →",exact:true}).click();
 await page.getByRole("button",{name:"Reveal meaning",exact:true}).click();
 await page.getByRole("button",{name:"Remembered",exact:true}).click();
 await page.getByRole("button",{name:"Back to my collection",exact:true}).click();
 await page.getByRole("link",{name:"Open in context →",exact:true}).click();
 await expect(page).toHaveURL(/page=coursebook-30&track=coursebook-l4-ex3-c8a4e473&transcriptLine=1/);
 await page.reload();
 await expect(page.locator('.listening-transcript-lines>p[data-active="true"]')).toContainText(phrase!);
 await expect(page.locator(".book-track")).toHaveCount(1);
 await expect(page.getByRole("combobox",{name:"Page zoom",exact:true})).toHaveValue("0");
 await page.locator("#book-listening").screenshot({path:info.outputPath(`reader-transcript-${width}.png`)});
 await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1);
});

test("book line saves preserve source selection and answers stay deliberate",async({page})=>{
 await page.goto("book/?page=coursebook-30");
 await expect(page.locator(".book-answer-list")).toHaveCount(0);
 await page.getByRole("combobox",{name:"Reading view",exact:true}).selectOption("read");
 const line=page.locator(".book-readable-lines .book-line").first();
 const id=await line.getAttribute("data-line-id");
 await line.getByRole("button",{name:/^Save to review:/}).click();
 await page.goto("saved/");
 await page.getByRole("link",{name:"Open in context →",exact:true}).click();
 await expect(page).toHaveURL(new RegExp(`line=${encodeURIComponent(id!)}`));
 await expect(page.locator(".book-selected-line .book-line")).toHaveAttribute("data-line-id",id!);
 await expect(page.locator(".book-selected-line")).toBeInViewport();
 await expect(page.locator(".book-answer-list")).toHaveCount(0);
 await page.getByRole("button",{name:/^Show answers/}).click();
 await expect(page.locator(".book-answer-list")).toBeVisible();
 await expect(page.locator(".book-answer-list")).toContainText(/Official solution|Official sample response|From the publisher/);
 await page.getByRole("button",{name:"☷ Contents & search",exact:true}).click();
 await page.getByRole("textbox",{name:"Find text in the book",exact:true}).fill("Stuhl");
 const result=page.locator(".book-search-results button").first();
 const resultText=await result.locator("span").innerText();
 await result.click();
 await expect(page.locator(".book-selected-line .study-german")).toHaveAttribute("aria-label",resultText);
 await expect(page.locator(".book-selected-line")).toBeInViewport();
 await page.reload();
 await expect(page.locator(".book-selected-line .study-german")).toHaveAttribute("aria-label",resultText);
});
