export type StudyWord = {
  id: string;
  de: string;
  en: string;
  plural: string;
  category: string;
  example: string;
  translation: string;
};
const rows = [
  [
    "bild",
    "das Bild",
    "picture",
    "die Bilder",
    "Furniture",
    "Das Bild ist so schön.",
    "The picture is so beautiful.",
  ],
  [
    "stuhl",
    "der Stuhl",
    "chair",
    "die Stühle",
    "Furniture",
    "Der Stuhl kostet nur 59 Euro.",
    "The chair costs only 59 euros.",
  ],
  [
    "bett",
    "das Bett",
    "bed",
    "die Betten",
    "Furniture",
    "Das Bett ist modern.",
    "The bed is modern.",
  ],
  [
    "lampe",
    "die Lampe",
    "lamp",
    "die Lampen",
    "Furniture",
    "Die Lampe ist günstig.",
    "The lamp is inexpensive.",
  ],
  [
    "sessel",
    "der Sessel",
    "armchair",
    "die Sessel",
    "Furniture",
    "Wie viel kostet der Sessel?",
    "How much does the armchair cost?",
  ],
  [
    "sofa",
    "das Sofa",
    "sofa",
    "die Sofas",
    "Furniture",
    "Das Sofa ist groß.",
    "The sofa is big.",
  ],
  [
    "tisch",
    "der Tisch",
    "table",
    "die Tische",
    "Furniture",
    "Der Tisch ist praktisch.",
    "The table is practical.",
  ],
  [
    "schrank",
    "der Schrank",
    "wardrobe",
    "die Schränke",
    "Furniture",
    "Der Schrank ist zu klein.",
    "The wardrobe is too small.",
  ],
  [
    "teppich",
    "der Teppich",
    "carpet / rug",
    "die Teppiche",
    "Furniture",
    "Der Teppich ist teuer.",
    "The carpet is expensive.",
  ],
  [
    "regal",
    "das Regal",
    "shelf / shelving unit",
    "die Regale",
    "Furniture",
    "Das Regal ist sehr schön.",
    "The shelving unit is very beautiful.",
  ],
  [
    "spiegel",
    "der Spiegel",
    "mirror",
    "die Spiegel",
    "Furniture",
    "Der Spiegel ist neu.",
    "The mirror is new.",
  ],
  [
    "moebel",
    "die Möbel",
    "furniture",
    "plural only",
    "Furniture",
    "Die Möbel sind modern.",
    "The furniture is modern.",
  ],
  [
    "schoen",
    "schön",
    "beautiful / lovely",
    "",
    "Adjectives",
    "Das Zimmer ist schön.",
    "The room is beautiful.",
  ],
  [
    "haesslich",
    "hässlich",
    "ugly",
    "",
    "Adjectives",
    "Ich finde, das Bild ist hässlich.",
    "I think the picture is ugly.",
  ],
  [
    "teuer",
    "teuer",
    "expensive",
    "",
    "Adjectives",
    "Das Hotel ist teuer.",
    "The hotel is expensive.",
  ],
  [
    "guenstig",
    "günstig",
    "inexpensive / good value",
    "",
    "Adjectives",
    "Das ist aber günstig!",
    "That is really good value!",
  ],
  [
    "modern",
    "modern",
    "modern",
    "",
    "Adjectives",
    "Die Lampe ist modern.",
    "The lamp is modern.",
  ],
  [
    "praktisch",
    "praktisch",
    "practical / handy",
    "",
    "Adjectives",
    "Das Regal ist praktisch.",
    "The shelving unit is practical.",
  ],
  [
    "gross",
    "groß",
    "big / large",
    "",
    "Adjectives",
    "Der Tisch ist zu groß.",
    "The table is too big.",
  ],
  [
    "klein",
    "klein",
    "small",
    "",
    "Adjectives",
    "Das Zimmer ist klein.",
    "The room is small.",
  ],
  [
    "neu",
    "neu",
    "new",
    "",
    "Adjectives",
    "Das Bett ist neu.",
    "The bed is new.",
  ],
  [
    "kosten",
    "kosten",
    "to cost",
    "",
    "Verbs",
    "Wie viel kostet das Sofa?",
    "How much does the sofa cost?",
  ],
  [
    "finden",
    "finden",
    "to think / have an opinion",
    "",
    "Verbs",
    "Das finde ich auch.",
    "I think so too.",
  ],
  [
    "schauen",
    "schauen",
    "to look",
    "",
    "Verbs",
    "Schau doch mal, da!",
    "Just look, over there!",
  ],
  [
    "kennen",
    "kennen",
    "to know / be familiar with",
    "",
    "Verbs",
    "Kennen Sie das Hotel?",
    "Do you know the hotel?",
  ],
  [
    "shoppen",
    "shoppen",
    "to shop",
    "",
    "Verbs",
    "Wir shoppen zusammen.",
    "We go shopping together.",
  ],
  [
    "preis",
    "der Preis",
    "price",
    "die Preise",
    "Shopping",
    "Der Preis ist günstig.",
    "The price is low.",
  ],
  [
    "sonderangebot",
    "das Sonderangebot",
    "special offer",
    "die Sonderangebote",
    "Shopping",
    "Das ist ein Sonderangebot.",
    "That is a special offer.",
  ],
  [
    "euro",
    "der Euro",
    "euro",
    "die Euro",
    "Shopping",
    "Er kostet hundert Euro.",
    "It costs one hundred euros.",
  ],
  [
    "cent",
    "der Cent",
    "cent",
    "die Cent",
    "Shopping",
    "Das kostet fünfzig Cent.",
    "That costs fifty cents.",
  ],
  [
    "million",
    "die Million",
    "million",
    "die Millionen",
    "Numbers",
    "Eine Million hat sechs Nullen.",
    "One million has six zeros.",
  ],
  [
    "geschaeft",
    "das Geschäft",
    "shop",
    "die Geschäfte",
    "Shopping",
    "Das Geschäft ist groß.",
    "The shop is big.",
  ],
  [
    "glueck",
    "das Glück",
    "luck",
    "",
    "Shopping",
    "Sie haben Glück!",
    "You are in luck!",
  ],
  [
    "zimmer",
    "das Zimmer",
    "room",
    "die Zimmer",
    "Places",
    "Das Zimmer kostet vierzig Euro.",
    "The room costs forty euros.",
  ],
  [
    "hotel",
    "das Hotel",
    "hotel",
    "die Hotels",
    "Places",
    "Das Hotel ist modern.",
    "The hotel is modern.",
  ],
  [
    "stern",
    "der Stern",
    "star",
    "die Sterne",
    "Places",
    "Das Hotel hat drei Sterne.",
    "The hotel has three stars.",
  ],
  [
    "zuhause",
    "zu Hause",
    "at home",
    "",
    "Expressions",
    "Ich bin zu Hause.",
    "I am at home.",
  ],
  [
    "wieviel",
    "wie viel",
    "how much",
    "",
    "Expressions",
    "Wie viel kostet er denn?",
    "How much does it cost, then?",
  ],
  [
    "nur",
    "nur",
    "only",
    "",
    "Expressions",
    "Es kostet nur zehn Euro.",
    "It costs only ten euros.",
  ],
  [
    "wirklich",
    "wirklich",
    "really",
    "",
    "Expressions",
    "Sie ist wirklich schön.",
    "It is really beautiful.",
  ],
  [
    "zu",
    "zu",
    "too (before an adjective)",
    "",
    "Expressions",
    "Das Sofa ist zu groß.",
    "The sofa is too big.",
  ],
  [
    "da",
    "da",
    "there / over there",
    "",
    "Expressions",
    "Schau mal, da!",
    "Look, over there!",
  ],
  [
    "mal",
    "mal",
    "just (softens a request)",
    "",
    "Expressions",
    "Schau mal!",
    "Have a look!",
  ],
  [
    "denn",
    "denn",
    "then (conversational question particle)",
    "",
    "Expressions",
    "Was kostet er denn?",
    "How much does it cost, then?",
  ],
  ["oh", "oh", "oh", "", "Expressions", "Oh ja!", "Oh, yes!"],
] as const;

export const lessonFourWords: StudyWord[] = rows.map(
  ([id, de, en, plural, category, example, translation]) => ({
    id: `l4-${id}`,
    de,
    en,
    plural,
    category,
    example,
    translation,
  }),
);
export const lessonFourConcepts = [
  {
    id: "l4-articles",
    title: "Learn the noun with its article",
    de: "der Stuhl · das Bett · die Lampe",
    en: "Masculine: der. Neuter: das. Feminine: die. Learn each noun and article as one unit; English ‘the’ does not tell you the German gender.",
    examples: [
      "Der Tisch ist groß.",
      "Das Sofa ist schön.",
      "Die Lampe ist modern.",
    ],
  },
  {
    id: "l4-pronouns",
    title: "Replace the noun: er / es / sie",
    de: "Der Stuhl ist schön. Er ist günstig.",
    en: "Use er for a der noun, es for a das noun, and sie for a die noun. The pronoun follows grammatical gender, including for objects.",
    examples: [
      "Das Bett ist modern. Es ist schön.",
      "Die Lampe ist schön. Sie ist teuer.",
      "Der Schrank ist praktisch. Er ist groß.",
    ],
  },
  {
    id: "l4-adjectives",
    title: "Describe it, then give your opinion",
    de: "Das Bett ist modern. Das finde ich auch.",
    en: "An adjective after ist stays unchanged. Use Das finde ich auch to agree and Das finde ich nicht to disagree. Zu means ‘too’: zu klein, zu teuer.",
    examples: [
      "Ich finde, das Zimmer ist schön.",
      "Das finde ich nicht.",
      "Der Schrank ist zu klein.",
    ],
  },
  {
    id: "l4-prices",
    title: "Ask and answer about prices",
    de: "Wie viel kostet das Sofa? Es kostet 450 Euro.",
    en: "Ask Wie viel kostet …? or Was kostet …? Use kostet for one object and kosten for several. German prices use a decimal comma: 9,99 € is neun Euro neunundneunzig.",
    examples: [
      "Wie viel kostet der Sessel?",
      "Er kostet nur 59 Euro.",
      "Die Stühle kosten hundert Euro.",
    ],
  },
  {
    id: "l4-numbers",
    title: "Build numbers from 100 to 1,000,000",
    de: "452 = vierhundertzweiundfünfzig",
    en: "Hundreds come first; inside the last two digits, units come before tens. Numbers below a million are written as one word. Eine Million is a noun and takes a capital M.",
    examples: [
      "100: hundert",
      "1.000: tausend",
      "10.000: zehntausend",
      "210.000: zweihundertzehntausend",
      "1.000.000: eine Million",
    ],
  },
];
export const lessonFourPhrases = [
  ["Wie viel kostet das Sofa?", "How much does the sofa cost?"],
  ["Was kostet der Tisch?", "How much does the table cost?"],
  ["Er kostet nur 59 Euro.", "It costs only 59 euros."],
  ["Das ist ein Sonderangebot.", "That is a special offer."],
  ["Sie haben Glück!", "You are in luck!"],
  ["Oh, das ist aber günstig!", "Oh, that is really good value!"],
  ["Schau doch mal, da!", "Just look, over there!"],
  ["Das finde ich auch.", "I think so too."],
  ["Das finde ich nicht.", "I don’t think so."],
  ["Ich finde, das Zimmer ist schön.", "I think the room is beautiful."],
  ["Der Schrank ist zu klein.", "The wardrobe is too small."],
  ["Entschuldigung?", "Excuse me?"],
] as const;
export const lessonFourVerbs = [
  {
    verb: "kosten",
    meaning: "to cost",
    forms: ["koste", "kostest", "kostet", "kosten", "kostet", "kosten"],
    tip: "The stem ends in -t: du kostest, er kostet. For prices, practise kostet / kosten.",
  },
  {
    verb: "finden",
    meaning: "to think / find",
    forms: ["finde", "findest", "findet", "finden", "findet", "finden"],
    tip: "The stem ends in -d: add the extra e in findest and findet.",
  },
  {
    verb: "kennen",
    meaning: "to know",
    forms: ["kenne", "kennst", "kennt", "kennen", "kennt", "kennen"],
    tip: "Know a person or thing: Kennen Sie das Hotel?",
  },
  {
    verb: "schauen",
    meaning: "to look",
    forms: ["schaue", "schaust", "schaut", "schauen", "schaut", "schauen"],
    tip: "Schau mal! is the informal singular request ‘Have a look!’",
  },
];
export const lessonFourQuiz = [
  {
    q: "Choose the article: ___ Stuhl",
    options: ["der", "das", "die"],
    answer: "der",
    why: "Stuhl is masculine: der Stuhl → er.",
  },
  {
    q: "Choose the article: ___ Bett",
    options: ["der", "das", "die"],
    answer: "das",
    why: "Bett is neuter: das Bett → es.",
  },
  {
    q: "Choose the article: ___ Lampe",
    options: ["der", "das", "die"],
    answer: "die",
    why: "Lampe is feminine: die Lampe → sie.",
  },
  {
    q: "Das Sofa ist schön. ___ kostet 450 Euro.",
    options: ["Er", "Es", "Sie"],
    answer: "Es",
    why: "Use es to replace the neuter noun das Sofa.",
  },
  {
    q: "Die Lampe ist modern. ___ ist günstig.",
    options: ["Er", "Es", "Sie"],
    answer: "Sie",
    why: "Use sie for die Lampe, even though a lamp is an object.",
  },
  {
    q: "Der Schrank ist praktisch. ___ ist groß.",
    options: ["Er", "Es", "Sie"],
    answer: "Er",
    why: "Der Schrank is masculine, so its pronoun is er.",
  },
  {
    q: "How do you say ‘too expensive’?",
    options: ["sehr teuer", "zu teuer", "nicht teuer"],
    answer: "zu teuer",
    why: "Zu = too; sehr = very; nicht = not.",
  },
  {
    q: "Agree with an opinion.",
    options: [
      "Das finde ich auch.",
      "Das finde ich nicht.",
      "Wie viel kostet das?",
    ],
    answer: "Das finde ich auch.",
    why: "Auch means ‘too / also’: I think so too.",
  },
  {
    q: "Wie viel ___ der Tisch?",
    options: ["kosten", "kostest", "kostet"],
    answer: "kostet",
    why: "One table takes the singular kostet.",
  },
  {
    q: "How do you say 452?",
    options: [
      "vierhundertzweiundfünfzig",
      "vierhundertfünfundzwanzig",
      "zweihundertvierundfünfzig",
    ],
    answer: "vierhundertzweiundfünfzig",
    why: "400 + 2-and-50 = vierhundertzweiundfünfzig.",
  },
  {
    q: "Choose the plural of der Stuhl.",
    options: ["die Stuhlen", "die Stühle", "die Stuhls"],
    answer: "die Stühle",
    why: "The plural adds an umlaut and -e: Stuhl → Stühle.",
  },
  {
    q: "Write 1,000,000 in German.",
    options: ["ein Million", "eine Million", "eintausend"],
    answer: "eine Million",
    why: "Million is a feminine noun: eine Million.",
  },
];
export const courseChapters = [
  {
    number: 1,
    title: "Ich heiße Miriam.",
    topic: "Greetings & introductions",
    kb: 11,
    ab: 6,
  },
  {
    number: 2,
    title: "Was macht ihr beruflich?",
    topic: "Work & personal details",
    kb: 15,
    ab: 10,
  },
  {
    number: 3,
    title: "Das ist meine Schwester.",
    topic: "Family & languages",
    kb: 19,
    ab: 14,
  },
  {
    number: 4,
    title: "Das Bild ist so schön.",
    topic: "Furniture, opinions & prices",
    kb: 29,
    ab: 26,
  },
];
