/** English teaching glosses for the existing published conversation patterns. */
export const phraseMeanings: Record<string, string> = {
  "Wie alt bist du?": "How old are you? (informal)",
  "Wie alt sind Sie?": "How old are you? (formal)",
  "Ich bin … Jahre alt.": "I am … years old.",
  "Wer ist das?": "Who is that?",
  "Das ist …": "That is …",
  "Wie heißt du?": "What is your name? (informal)",
  "Wie heißen Sie?": "What is your name? (formal)",
  "Ich heiße …": "My name is …",
  "Mein Name ist …": "My name is …",
  "Woher kommst du?": "Where are you from? (informal)",
  "Woher kommen Sie?": "Where are you from? (formal)",
  "Ich komme aus …": "I come from …",
  "Was bist du von Beruf?": "What do you do for a living? (informal)",
  "Was sind Sie von Beruf?": "What do you do for a living? (formal)",
  "Ich bin … von Beruf.": "I am a … by profession.",
  "Ich bin …": "I am …",
  "Ich arbeite als …": "I work as a …",
  "Wo wohnst du?": "Where do you live? (informal)",
  "Wo wohnen Sie?": "Where do you live? (formal)",
  "Ich wohne in …": "I live in …",
  "Wie geht’s dir?": "How are you? (informal)",
  "Wie geht’s Ihnen?": "How are you? (formal)",
  "Super!": "Great!",
  "Sehr gut, danke.": "Very well, thank you.",
  "Gut, danke.": "Well, thank you.",
  "Es geht.": "So-so. / I'm okay.",
  "Nicht so gut.": "Not so well.",
  "Was macht ihr beruflich?": "What do you do for work? (informal, speaking to several people)",
  "Was machen Sie beruflich?": "What do you do for work? (formal)",
  "Ich arbeite bei …": "I work for …",
  "Ich studiere …": "I study … (at university)",
  "Ich arbeite im Moment nicht.": "I am not working at the moment.",
};

/** Teaching translations for complete utterances and useful chunks in Lesson 4. */
export const bookPhraseMeanings: Record<string, string> = {
  "Schau mal!": "Look! / Have a look!",
  "zu Hause": "at home",
  "im Möbelgeschäft": "in the furniture shop",
  "Das Bild ist teuer.": "The picture is expensive.",
  "Wie finden Sie das Bild?": "What do you think of the picture? (formal)",
  "Ich finde, das Bild ist teuer.": "I think the picture is expensive.",
  "nicht so schön.": "not so beautiful",
  "Der Stuhl ist so schön.": "The chair is so beautiful.",
  "Oh, das ist aber günstig!": "Oh, that is really good value!",
  "Oh ja! Das finde ich auch": "Oh yes! I think so too.",
  "Schau doch mal, da! Der Stuhl ist so schön.": "Just look, over there! The chair is so beautiful.",
  "Hmm? Wie viel kostet er denn?": "Hmm? How much does it cost, then? (er refers to the chair)",
  "Sie haben Glück! Der Stuhl kostet nur 59 Euro.": "You are in luck! The chair costs only 59 euros.",
  "Ja, er ist wirklich sehr schön.": "Yes, it really is very beautiful. (er refers to the chair)",
  "Wie viel kostet das?": "How much does that cost?",
  "Was kostet das?": "How much does that cost?",
  "Wie viel kostet …?": "How much does … cost?",
  "Was kostet …?": "How much does … cost?",
  "Schau mal, das Regal. Es ist sehr schön.": "Look at the shelving unit. It is very beautiful.",
  "Schau doch mal. Der Sessel ist so schön.": "Just look. The armchair is so beautiful.",
  "Ich finde, das Zimmer ist schön. Das Bett ist modern.": "I think the room is beautiful. The bed is modern.",
  "Das finde ich auch. Aber der Schrank ist nicht praktisch. Er ist zu klein.": "I think so too. But the wardrobe is not practical. It is too small.",
  "Wie finden Sie die Hotelzimmer?": "What do you think of the hotel rooms? (formal)",
  "ist zu groß.": "is too big",
  "ist zu klein.": "is too small",
};
