import {describe,it,expect} from "vitest";
import {readFileSync,existsSync} from "node:fs";
import {resolve} from "node:path";
import {loadBook,loadBookAnswers} from "../../apps/web/lib/study/catalog";
import {emptyStudy,parseStudy} from "../../apps/web/lib/study/storage";

describe("continuous books and source-bounded answers",()=>{
  const book=loadBook(),answers=loadBookAnswers();
  it("includes every source PDF page from the cover through the end of Lesson 7",()=>{
    for(const [kind,end] of [["coursebook",50],["workbook",49]] as const){const pages=book.pages.filter(p=>p.kind===kind&&p.printedPage<=end);expect(pages.map(p=>p.pdfPage)).toEqual(Array.from({length:end+2},(_,i)=>i+1));expect(pages.map(p=>p.printedPage)).toEqual(Array.from({length:end+2},(_,i)=>i-1));expect(pages[0]?.id).toBe(`${kind}-cover`);expect(pages[1]?.id).toBe(`${kind}-map`);for(const p of pages){expect(p.lines.length,p.id).toBeGreaterThan(0);expect(p.section).toBeTruthy();expect(existsSync(resolve(`apps/web/public${p.image}`)),p.id).toBe(true);}}
  });
  it("includes the previously skipped grammar, communication and review pages",()=>{expect(book.pages.find(p=>p.id==="coursebook-27")?.section).toBe("Module 1 · Grammar");expect(book.pages.find(p=>p.id==="coursebook-28")?.section).toBe("Module 1 · Communication");for(const page of [18,19,20,21,22,23,24,25])expect(book.pages.find(p=>p.id===`workbook-${page}`)?.section).toContain("Module 1");});
  it("preserves cover and map bookmarks, resume and completion through reload",()=>{const state={...emptyStudy(),resume:"coursebook-map",bookmarks:["workbook-cover","coursebook-27"],completedPages:["coursebook-cover"]};expect(parseStudy(JSON.stringify(state))).toEqual(state);});
  it("projects every known key entry onto its own exercise page",()=>{expect(answers).toHaveLength(113);expect(answers.filter(a=>a.source==="coursebook-key")).toHaveLength(95);expect(answers.filter(a=>a.source==="workbook-key")).toHaveLength(8);expect(answers.filter(a=>a.source==="workbook-transcript")).toHaveLength(10);expect(new Set(answers.map(a=>a.id)).size).toBe(113);expect(book.pages.flatMap(p=>p.answers??[])).toHaveLength(113);for(const a of answers){expect(a.id).toContain(a.pageId);expect(a.text).not.toMatch(/\uFFFD|Ã|Â/);expect(a.sourcePage).toBeGreaterThan(0);}});
  it("includes separate vocabulary, grammar and communication quick-test keys",()=>{for(const n of [14,18,22,32,36,40,50]){const quick=answers.filter(a=>a.pageId===`coursebook-${n}`&&a.exercise.startsWith("Quick test"));expect(quick).toHaveLength(3);for(const a of quick){expect(a.sourceTitle).toContain("Schnelltests");expect(a.sourcePage).toBe(203);}}});
  it("keeps number and pronoun solutions on coursebook 31",()=>{const page=book.pages.find(p=>p.id==="coursebook-31")!;expect(page.answers?.find(a=>a.exercise==="Exercise 5a")?.text).toBe("Sie, Er, Es");expect(page.answers?.find(a=>a.exercise==="Exercise 7b")?.text).toContain("249,95 Euro");expect(page.answers?.find(a=>a.exercise==="Exercise 6")?.text).toContain("vierhunderteinundfünfzig");});
  it("marks workbook model responses as examples and keeps missing answers absent",()=>{const samples=answers.filter(a=>a.source==="workbook-key"&&a.kind==="sample");expect(samples).toHaveLength(4);expect(samples[0]?.text).toContain("Hallo Eva!");expect(samples[1]?.text).toContain("Ich heiße Pablo.");expect(book.pages.find(p=>p.id==="workbook-27")?.answers).toEqual([]);expect(book.pages.find(p=>p.id==="coursebook-27")?.answers).toEqual([]);});
  it("keeps the original 64 audio bindings and adds 18 module recordings",()=>{const raw=JSON.parse(readFileSync(resolve("apps/web/generated/interactive-book.json"),"utf8"));expect(raw.audio.filter((a:{id:string})=>a.id.includes("-m1-"))).toHaveLength(18);expect(book.pages.find(p=>p.id==="coursebook-25")?.audioIds).toHaveLength(5);expect(book.pages.find(p=>p.id==="workbook-20")?.audioIds).toHaveLength(7);for(const a of book.audio)expect(a.transcript?.lines.length,a.id).toBeGreaterThan(0);});
});
